### ISSUE TITLE
NotADirectoryError When run run_docker.py

### ISSUE THREAD

**Issue by huanxian1995** [deepmind/alphafold#106]
(alphafold) [ec2-user@ip-172-31-4-73 alphafold-main]$ python3 docker/run_docker.py --fasta_paths=Dhinge.fa --max_template_date=2020-05-14
I0808 10:05:25.725758 140536868606144 run_docker.py:119] Mounting /home/ec2-user/alphafold-main -> /mnt/fasta_path_0
I0808 10:05:25.725876 140536868606144 run_docker.py:119] Mounting /data/database/uniref90 -> /mnt/uniref90_database_path
I0808 10:05:25.725962 140536868606144 run_docker.py:119] Mounting /data/database/mgnify -> /mnt/mgnify_database_path
I0808 10:05:25.726035 140536868606144 run_docker.py:119] Mounting /data/database/pdb70 -> /mnt/pdb70_database_path
I0808 10:05:25.726103 140536868606144 run_docker.py:119] Mounting /data -> /mnt/data_dir
I0808 10:05:25.726171 140536868606144 run_docker.py:119] Mounting /data/database/pdb_mmcif -> /mnt/template_mmcif_dir
I0808 10:05:25.726236 140536868606144 run_docker.py:119] Mounting /data/database/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0808 10:05:25.726302 140536868606144 run_docker.py:119] Mounting /data/database/uniclust30/uniclust30_2018_08 -> /mnt/uniclust30_database_path
I0808 10:05:25.726374 140536868606144 run_docker.py:119] Mounting /data/database/bfd -> /mnt/bfd_database_path
I0808 10:05:28.863047 140536868606144 run_docker.py:193] /opt/conda/lib/python3.7/site-packages/absl/flags/_validators.py:206: UserWarning: Flag --preset has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
I0808 10:05:28.863267 140536868606144 run_docker.py:193] 'command line!' % flag_name)
I0808 10:05:29.223468 140536868606144 run_docker.py:193] I0808 10:05:29.222831 140501330065216 templates.py:836] Using precomputed obsolete pdbs /mnt/obsolete_pdbs_path/obsolete.dat.
I0808 10:05:29.454206 140536868606144 run_docker.py:193] I0808 10:05:29.453686 140501330065216 tpu_client.py:54] Starting the local TPU driver.
I0808 10:05:29.454438 140536868606144 run_docker.py:193] I0808 10:05:29.453970 140501330065216 xla_bridge.py:214] Unable to initialize backend 'tpu_driver': Not found: Unable to find driver in registry given worker: local://
I0808 10:05:30.104188 140536868606144 run_docker.py:193] I0808 10:05:30.103670 140501330065216 xla_bridge.py:214] Unable to initialize backend 'tpu': Invalid argument: TpuPlatform is not available.
I0808 10:05:35.041861 140536868606144 run_docker.py:193] I0808 10:05:35.041266 140501330065216 run_alphafold.py:260] Have 5 models: ['model_1', 'model_2', 'model_3', 'model_4', 'model_5']
I0808 10:05:35.042193 140536868606144 run_docker.py:193] I0808 10:05:35.041440 140501330065216 run_alphafold.py:272] Using random seed 7601186452952218059 for the data pipeline
I0808 10:05:35.042940 140536868606144 run_docker.py:193] Traceback (most recent call last):
I0808 10:05:35.043086 140536868606144 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 302, in <module>
I0808 10:05:35.043199 140536868606144 run_docker.py:193] app.run(main)
I0808 10:05:35.043313 140536868606144 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
I0808 10:05:35.043413 140536868606144 run_docker.py:193] _run_main(main, args)
I0808 10:05:35.043524 140536868606144 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I0808 10:05:35.043607 140536868606144 run_docker.py:193] sys.exit(main(argv))
I0808 10:05:35.043685 140536868606144 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 284, in main
I0808 10:05:35.043761 140536868606144 run_docker.py:193] random_seed=random_seed)
I0808 10:05:35.043835 140536868606144 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 119, in predict_structure
I0808 10:05:35.043908 140536868606144 run_docker.py:193] os.makedirs(output_dir)
I0808 10:05:35.043980 140536868606144 run_docker.py:193] File "/opt/conda/lib/python3.7/os.py", line 223, in makedirs
I0808 10:05:35.044053 140536868606144 run_docker.py:193] mkdir(name, mode)
I0808 10:05:35.044138 140536868606144 run_docker.py:193] NotADirectoryError: [Errno 20] Not a directory: '/mnt/output/Dhinge'

**Comment by huanxian1995** [comment]
I‘ve solved the question. The main reason is that I put a file named 'alphafold' in the /tmp/. It is not a folder so get error when mount to docker.
