### ISSUE TITLE
Could not load dynamic library 'libcusolver.so.11'

### ISSUE THREAD

**Issue by ccgauvin94** [deepmind/alphafold#115]
openSUSE LEAP 15.2
2x A40s with driver version 460.84, CUDA version 11.2

Alphafold fails after running from docker/run_docker.py

```I0810 10:27:32.175092 139750471120192 run_docker.py:193] I0810 16:27:32.174497 140675273811712 templates.py:271] Found an exact template match 4f43_A.
I0810 10:27:32.478774 139750471120192 run_docker.py:193] I0810 16:27:32.478360 140675273811712 run_alphafold.py:141] Running model model_1
I0810 10:27:35.738799 139750471120192 run_docker.py:193] 2021-08-10 16:27:35.738126: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
I0810 10:27:35.760256 139750471120192 run_docker.py:193] 2021-08-10 16:27:35.759588: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
I0810 10:27:35.760537 139750471120192 run_docker.py:193] Skipping registering GPU devices...
I0810 10:27:36.830071 139750471120192 run_docker.py:193] I0810 16:27:36.829187 140675273811712 model.py:132] Running predict with shape(feat) = {'aatype': (4, 340), 'residue_index': (4, 340), 'seq_length': (4,), 'template_aatype': (4, 4, 340), 'template_all_atom_masks': (4, 4, 340, 37), 'template_all_atom_positions': (4, 4, 340, 37, 3), 'template_sum_probs': (4, 4, 1), 'is_distillation': (4,), 'seq_mask': (4, 340), 'msa_mask': (4, 508, 340), 'msa_row_mask': (4, 508), 'random_crop_to_size_seed': (4, 2), 'template_mask': (4, 4), 'template_pseudo_beta': (4, 4, 340, 3), 'template_pseudo_beta_mask': (4, 4, 340), 'atom14_atom_exists': (4, 340, 14), 'residx_atom14_to_atom37': (4, 340, 14), 'residx_atom37_to_atom14': (4, 340, 37), 'atom37_atom_exists': (4, 340, 37), 'extra_msa': (4, 5120, 340), 'extra_msa_mask': (4, 5120, 340), 'extra_msa_row_mask': (4, 5120), 'bert_mask': (4, 508, 340), 'true_msa': (4, 508, 340), 'extra_has_deletion': (4, 5120, 340), 'extra_deletion_value': (4, 5120, 340), 'msa_feat': (4, 508, 340, 49), 'target_feat': (4, 340, 22)}
I0810 10:27:37.571571 139750471120192 run_docker.py:193] 2021-08-10 16:27:37.570928: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:235] Falling back to the CUDA driver for PTX compilation; ptxas does not support CC 8.6
I0810 10:27:37.571787 139750471120192 run_docker.py:193] 2021-08-10 16:27:37.571002: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:238] Used ptxas at ptxas
I0810 10:27:37.573128 139750471120192 run_docker.py:193] 2021-08-10 16:27:37.572480: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:625] failed to get PTX kernel "shift_right_logical_3" from module: CUDA_ERROR_NOT_FOUND: named symbol not found
I0810 10:27:37.573509 139750471120192 run_docker.py:193] 2021-08-10 16:27:37.572543: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2040] Execution of replica 0 failed: Internal: Could not find the corresponding function
I0810 10:27:37.601842 139750471120192 run_docker.py:193] Traceback (most recent call last):
I0810 10:27:37.601936 139750471120192 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 302, in <module>
I0810 10:27:37.602026 139750471120192 run_docker.py:193] app.run(main)
I0810 10:27:37.602137 139750471120192 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
I0810 10:27:37.602226 139750471120192 run_docker.py:193] _run_main(main, args)
I0810 10:27:37.602313 139750471120192 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I0810 10:27:37.602401 139750471120192 run_docker.py:193] sys.exit(main(argv))
I0810 10:27:37.602487 139750471120192 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 284, in main
I0810 10:27:37.602574 139750471120192 run_docker.py:193] random_seed=random_seed)
I0810 10:27:37.602665 139750471120192 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 148, in predict_structure
I0810 10:27:37.602751 139750471120192 run_docker.py:193] prediction_result = model_runner.predict(processed_feature_dict)
I0810 10:27:37.602837 139750471120192 run_docker.py:193] File "/app/alphafold/alphafold/model/model.py", line 133, in predict
I0810 10:27:37.602923 139750471120192 run_docker.py:193] result = self.apply(self.params, jax.random.PRNGKey(0), feat)
I0810 10:27:37.603020 139750471120192 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/_src/random.py", line 75, in PRNGKey
I0810 10:27:37.603107 139750471120192 run_docker.py:193] k1 = convert(lax.shift_right_logical(seed_arr, lax._const(seed_arr, 32)))
I0810 10:27:37.603193 139750471120192 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/_src/lax/lax.py", line 382, in shift_right_logical
I0810 10:27:37.603280 139750471120192 run_docker.py:193] return shift_right_logical_p.bind(x, y)
I0810 10:27:37.603366 139750471120192 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 264, in bind
I0810 10:27:37.603452 139750471120192 run_docker.py:193] out = top_trace.process_primitive(self, tracers, params)
I0810 10:27:37.603537 139750471120192 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 604, in process_primitive
I0810 10:27:37.603623 139750471120192 run_docker.py:193] return primitive.impl(*tracers, **params)
I0810 10:27:37.603709 139750471120192 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 262, in apply_primitive
I0810 10:27:37.603795 139750471120192 run_docker.py:193] return compiled_fun(*args)
I0810 10:27:37.603881 139750471120192 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 378, in _execute_compiled_primitive
I0810 10:27:37.603967 139750471120192 run_docker.py:193] out_bufs = compiled.execute(input_bufs)
I0810 10:27:37.604053 139750471120192 run_docker.py:193] RuntimeError: Internal: Could not find the corresponding function```

**Comment by ccgauvin94** [comment]
Running `echo $LD_LIBRARY_PATH` returns `/usr/lib64/mpi/gcc/openmpi4/lib64`, and `/usr/local/nvidia` doesn't exist on the host system, instead it's under `/usr/local/cuda-11.2`

**Comment by Feng-Zhang** [comment]
Hi tomwardio,
I have the same issue. 
```
docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi
Sat Jan 22 14:06:50 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.106.00   Driver Version: 460.106.00   CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  RTX A6000           On   | 00000000:02:00.0  On |                  Off |
| 30%   20C    P8     7W / 300W |     84MiB / 48676MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

```
Thanks.
