### ISSUE TITLE
pdbfixer not listed in requirements.txt or setup.py

### ISSUE THREAD

**Issue by branfosj** [deepmind/alphafold#131]
`pdbfixer` is imported at https://github.com/deepmind/alphafold/blob/main/alphafold/relax/cleanup.py#L22, however it is not included in [`requirements.txt`](https://github.com/deepmind/alphafold/blob/main/requirements.txt) or [`setup.py`](https://github.com/deepmind/alphafold/blob/main/steup.py).

```
$ python -c "from alphafold.relax import relax"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/rds/projects/2017/branfosj-rse/alphafold/alphafold/alphafold/relax/relax.py", line 18, in <module>
    from alphafold.relax import amber_minimize
  File "/rds/projects/2017/branfosj-rse/alphafold/alphafold/alphafold/relax/amber_minimize.py", line 25, in <module>
    from alphafold.relax import cleanup
  File "/rds/projects/2017/branfosj-rse/alphafold/alphafold/alphafold/relax/cleanup.py", line 22, in <module>
    import pdbfixer
ModuleNotFoundError: No module named 'pdbfixer'
```

**Comment by andyballard** [comment]
Hi, pdbfixer isn't in requirements.txt or setup.py because it's not installed as a python module, but rather as an independent package by Conda in the Docker container. You can see how it's installed in the [Dockerfile](https://github.com/deepmind/alphafold/blob/main/docker/Dockerfile).
