### ISSUE TITLE
CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered

### ISSUE THREAD

**Issue by jiyanbio** [deepmind/alphafold#140]
2021-08-19 10:05:03.498 Traceback (most recent call last):
2021-08-19 10:05:03.498 File "run_alphafold2_complex.py", line 384, in <module>
2021-08-19 10:05:03.498 plddts, paes = predict_structure(jobname, feature_dict, Ls=Ls, num_models=num_models)
2021-08-19 10:05:03.498 File "run_alphafold2_complex.py", line 152, in predict_structure
2021-08-19 10:05:03.498 prediction_result=model_runner.predict(processed_feature_dict)
2021-08-19 10:05:03.498 File "/ceph/bbkjfeng/buddy1/alphafold/tmp/proteinComplex/alphafold/model/model.py", line 133, in predict
2021-08-19 10:05:03.498 result = self.apply(self.params, jax.random.PRNGKey(0), feat)
2021-08-19 10:05:03.498 File "/opt/conda/lib/python3.8/site-packages/jax/interpreters/xla.py", line 893, in _execute_compiled
2021-08-19 10:05:03.498 out_bufs = compiled.execute(input_bufs)
2021-08-19 10:05:03.498 RuntimeError: Internal: Failed to launch CUDA kernel: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-08-19 10:05:04.659 2021-08-19 10:05:04.658984: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:1039] could not synchronize on CUDA context: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered :: *** Begin stack trace ***

**Comment by boegel** [comment]
@jiyanbio Do you have more information on this? On what type of system/GPUs were you hitting this?

**Comment by Jorisvansteenbrugge** [comment]
@boegel I run into the same issue. Perhaps I can provide more details\

I run alphafold using docker, e.g. `python /home/joris/tools/alphafold/docker/run_docker.py --fasta_paths=test_gpa2.fasta --preset=casp14 --max_template_date=2021-10-1` 

OS: Ubuntu 20.04.3 LTS
GPU: RTX3080 ti

I was able to predict the structure of a different sequence, but the one I tried later gave me this error. Let me know if you need ano other information

Full log: [alphafold_error_log.txt](https://github.com/deepmind/alphafold/files/7265858/alphafold_error_log.txt)

**Comment by Professor333** [comment]
I'm getting the same error on A100 GPUs. Looks like we're both using unified memory (XLA, Jaxlib). I have used unified memory to fold several other proteins, but for some reason I have one protein that fails with this CUDA synchronization error.

**Comment by boegel** [comment]
For what it's worth: I could get things running by not using unified memory, by making sure the `$TF_FORCE_UNIFIED_MEMORY` environment variable is not set:

```shell
unset TF_FORCE_UNIFIED_MEMORY
```

**Comment by Augustin-Zidek** [comment]
Is this still an issue with the most recent version of AlphaFold?

**Comment by Augustin-Zidek** [comment]
Closing this issue for now, feel free to reopen if this is still a problem.
