### ISSUE TITLE
pdb70_cs219.ffdata not found

### ISSUE THREAD

**Issue by GeoMicroSoares** [deepmind/alphafold#145]
Hi there - this seems really basic, but I'm honestly out of ideas as to why it's failing. Below you'll see that running `alphafold`, uniref90 and mgy databases are found, but not pdb70. They're set in the same way in `docker/run_docker.py` and I previoulsy ran `scripts/download_all_data.sh /mnt/XIO_4_via_NFS/databases/alphafold/` that having gone normally. The file being searched is also present in the pdb70 folder:

```
$ ll /mnt/XIO_4_via_NFS/databases/alphafold/pdb70/
total 58687056
drwxrwxr-x 2 andre andre        4096 Aug 18 20:27 ./
drwxrwxr-x 9 andre andre        4096 Aug 18 23:40 ../
-rw------- 1 andre andre         410 Apr  1  2020 md5sum
-rw------- 1 andre andre 56554823611 Apr  1  2020 pdb70_a3m.ffdata
-rw------- 1 andre andre     2049264 Apr  1  2020 pdb70_a3m.ffindex
-rw------- 1 andre andre     6967926 Apr  1  2020 pdb70_clu.tsv
-rw------- 1 andre andre    22338334 Apr  1  2020 pdb70_cs219.ffdata
-rw------- 1 andre andre     1562700 Apr  1  2020 pdb70_cs219.ffindex
-rw------- 1 andre andre  3485614545 Apr  1  2020 pdb70_hhm.ffdata
-rw------- 1 andre andre     1884124 Apr  1  2020 pdb70_hhm.ffindex
-rw------- 1 andre andre    20263781 Apr  1  2020 pdb_filter.dat
```

Any ideas on why this is going wrong?

```
$ python3 docker/run_docker.py --fasta_paths=test_alti_protein.fasta --max_template_date=2021-08-19 --preset full_dbs
I0820 11:39:44.362042 139904655151936 run_docker.py:122] Mounting /home/andre/alphafold -> /mnt/fasta_path_0
I0820 11:39:44.362154 139904655151936 run_docker.py:122] Mounting /mnt/XIO_4_via_NFS/databases/alphafold/uniref90 -> /mnt/uniref90_database_path
I0820 11:39:44.362221 139904655151936 run_docker.py:122] Mounting /mnt/XIO_4_via_NFS/databases/alphafold/mgnify -> /mnt/mgnify_database_path
I0820 11:39:44.362277 139904655151936 run_docker.py:122] Mounting /mnt/XIO_4_via_NFS/databases/alphafold/pdb70 -> /mnt/pdb70_database_path
I0820 11:39:44.362322 139904655151936 run_docker.py:122] Mounting /mnt/XIO_4_via_NFS/databases -> /mnt/data_dir
I0820 11:39:44.362365 139904655151936 run_docker.py:122] Mounting /mnt/XIO_4_via_NFS/databases/alphafold/pdb_mmcif -> /mnt/template_mmcif_dir
I0820 11:39:44.362411 139904655151936 run_docker.py:122] Mounting /mnt/XIO_4_via_NFS/databases/alphafold/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0820 11:39:44.362453 139904655151936 run_docker.py:122] Mounting /mnt/XIO_4_via_NFS/databases/alphafold/uniclust30/uniclust30_2018_08 -> /mnt/uniclust30_database_path
I0820 11:39:44.362498 139904655151936 run_docker.py:122] Mounting /mnt/XIO_4_via_NFS/databases/alphafold/bfd -> /mnt/bfd_database_path
I0820 11:39:46.960751 139904655151936 run_docker.py:196] /opt/conda/lib/python3.7/site-packages/absl/flags/_validators.py:206: UserWarning: Flag --preset has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
I0820 11:39:46.960999 139904655151936 run_docker.py:196] 'command line!' % flag_name)
I0820 11:39:47.377755 139904655151936 run_docker.py:196] I0820 09:39:47.376356 139671888074560 templates.py:836] Using precomputed obsolete pdbs /mnt/obsolete_pdbs_path/obsolete.dat.
I0820 11:39:47.753161 139904655151936 run_docker.py:196] I0820 09:39:47.752050 139671888074560 xla_bridge.py:236] Unable to initialize backend 'tpu_driver': Not found: Unable to find driver in registry given worker:
I0820 11:39:47.869765 139904655151936 run_docker.py:196] I0820 09:39:47.869026 139671888074560 xla_bridge.py:236] Unable to initialize backend 'tpu': Invalid argument: TpuPlatform is not available.
I0820 11:39:53.370578 139904655151936 run_docker.py:196] I0820 09:39:53.368890 139671888074560 run_alphafold.py:268] Have 5 models: ['model_1', 'model_2', 'model_3', 'model_4', 'model_5']
I0820 11:39:53.370871 139904655151936 run_docker.py:196] I0820 09:39:53.369265 139671888074560 run_alphafold.py:280] Using random seed 1214462081521001844 for the data pipeline
I0820 11:39:53.371992 139904655151936 run_docker.py:196] I0820 09:39:53.371241 139671888074560 jackhmmer.py:130] Launching subprocess "/usr/bin/jackhmmer -o /dev/null -A /tmp/tmpylxu3rmz/output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 /mnt/fasta_path_0/test_alti_protein.fasta /mnt/uniref90_database_path/uniref90.fasta"
I0820 11:39:53.437052 139904655151936 run_docker.py:196] I0820 09:39:53.435985 139671888074560 utils.py:36] Started Jackhmmer (uniref90.fasta) query
I0820 11:46:02.965183 139904655151936 run_docker.py:196] I0820 09:46:02.943167 139671888074560 utils.py:40] Finished Jackhmmer (uniref90.fasta) query in 369.507 seconds
I0820 11:46:03.011880 139904655151936 run_docker.py:196] I0820 09:46:03.010892 139671888074560 jackhmmer.py:130] Launching subprocess "/usr/bin/jackhmmer -o /dev/null -A /tmp/tmpv1ajpeo4/output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 /mnt/fasta_path_0/test_alti_protein.fasta /mnt/mgnify_database_path/mgy_clusters_2018_12.fa"
I0820 11:46:03.073172 139904655151936 run_docker.py:196] I0820 09:46:03.072067 139671888074560 utils.py:36] Started Jackhmmer (mgy_clusters_2018_12.fa) query
I0820 11:53:41.428847 139904655151936 run_docker.py:196] I0820 09:53:41.427574 139671888074560 utils.py:40] Finished Jackhmmer (mgy_clusters_2018_12.fa) query in 458.355 seconds
I0820 11:53:43.486619 139904655151936 run_docker.py:196] I0820 09:53:43.485320 139671888074560 hhsearch.py:76] Launching subprocess "/usr/bin/hhsearch -i /tmp/tmpzep3kfy_/query.a3m -o /tmp/tmpzep3kfy_/output.hhr -maxseq 1000000 -d /mnt/pdb70_database_path/pdb70"
I0820 11:53:43.555775 139904655151936 run_docker.py:196] I0820 09:53:43.554538 139671888074560 utils.py:36] Started HHsearch query
I0820 11:53:43.577885 139904655151936 run_docker.py:196] I0820 09:53:43.577152 139671888074560 utils.py:40] Finished HHsearch query in 0.022 seconds
I0820 11:53:43.583618 139904655151936 run_docker.py:196] Traceback (most recent call last):
I0820 11:53:43.583730 139904655151936 run_docker.py:196] File "/app/alphafold/run_alphafold.py", line 310, in <module>
I0820 11:53:43.583805 139904655151936 run_docker.py:196] app.run(main)
I0820 11:53:43.583873 139904655151936 run_docker.py:196] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
I0820 11:53:43.583938 139904655151936 run_docker.py:196] _run_main(main, args)
I0820 11:53:43.584000 139904655151936 run_docker.py:196] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I0820 11:53:43.584063 139904655151936 run_docker.py:196] sys.exit(main(argv))
I0820 11:53:43.584125 139904655151936 run_docker.py:196] File "/app/alphafold/run_alphafold.py", line 292, in main
I0820 11:53:43.584188 139904655151936 run_docker.py:196] random_seed=random_seed)
I0820 11:53:43.584247 139904655151936 run_docker.py:196] File "/app/alphafold/run_alphafold.py", line 129, in predict_structure
I0820 11:53:43.584307 139904655151936 run_docker.py:196] msa_output_dir=msa_output_dir)
I0820 11:53:43.584367 139904655151936 run_docker.py:196] File "/app/alphafold/alphafold/data/pipeline.py", line 140, in process
I0820 11:53:43.584458 139904655151936 run_docker.py:196] hhsearch_result = self.hhsearch_pdb70_runner.query(uniref90_msa_as_a3m)
I0820 11:53:43.584520 139904655151936 run_docker.py:196] File "/app/alphafold/alphafold/data/tools/hhsearch.py", line 87, in query
I0820 11:53:43.584579 139904655151936 run_docker.py:196] stdout.decode('utf-8'), stderr[:100_000].decode('utf-8')))
I0820 11:53:43.584639 139904655151936 run_docker.py:196] RuntimeError: HHSearch failed:
I0820 11:53:43.584697 139904655151936 run_docker.py:196] stdout:
I0820 11:53:43.584758 139904655151936 run_docker.py:196]
I0820 11:53:43.584817 139904655151936 run_docker.py:196]
I0820 11:53:43.584875 139904655151936 run_docker.py:196] stderr:
I0820 11:53:43.584933 139904655151936 run_docker.py:196] - 09:53:43.576 ERROR: In /tmp/hh-suite/src/ffindexdatabase.cpp:11: FFindexDatabase:
I0820 11:53:43.584993 139904655151936 run_docker.py:196]
I0820 11:53:43.585054 139904655151936 run_docker.py:196] - 09:53:43.576 ERROR: 	could not open file '/mnt/pdb70_database_path/pdb70_cs219.ffdata'
I0820 11:53:43.585114 139904655151936 run_docker.py:196]
I0820 11:53:43.585174 139904655151936 run_docker.py:196]
I0820 11:53:43.585233 139904655151936 run_docker.py:196]
```

**Comment by GeoMicroSoares** [comment]
Hi @abridgland, any news on this by any chance? We have really interesting data here we'd love to run through `alphafold` but this error seems to be in our way...

**Comment by abridgland** [comment]
Hi @GeoMicroSoares, I'm afraid I haven't encountered this before or seen any similar reports. The fact that uniref90 and mgnify succeeded suggests that the data is indeed mounted correctly. However those two databases are searched with Jackhmmer rather than HH-suite (HHsearch and HHblits), which is used for BFD and PDB70. This might indicate that the problem is with your HHsearch installation not being able to see the mounted data. I don't know for sure but this might be something like a permissions issue. I'd suggest trying to run the HH-suite query manually to see if you get the same error. Looking at the logs that would probably be:
```
/usr/bin/hhsearch -i /tmp/tmpzep3kfy_/query.a3m -o /tmp/tmpzep3kfy_/output.hhr -maxseq 1000000 -d /mnt/XIO_4_via_NFS/databases/alphafold/pdb70/pdb70
```
except you might have to find a new a3m file if that temp file doesn't exist any more. If that also fails then it suggests the issue is with your HH-suite installation.

In the meantime you can always use the AlphaFold colab or one of the other hosted solutions to get some predictions.

I hope that helps!

**Comment by tomgreen66** [comment]
Hi, also hit the issue.  Looks like the permissions on the files when extracted in the download scripts are not set to be globally readable.  I am just running the example I have again to see if it works with the correct permissions to allow my user to read the data but it does look like it should fix the problem (I had converted the script from Docker to Singularity to use on our HPC system so spent a bit of time assuming it was my conversion which was the problem).

**Comment by tomgreen66** [comment]
Quick update - seems to have worked - onto the next part `hhblits` that is after `hhsearch`.

**Comment by ailiqiangCSU** [comment]
I have this same issue. How were you able to solve this?

**Comment by ilbarsukov** [comment]
I had the same error. Files in uniclust30/uniclust30_2018_08/ did not have read permission for my user name by default. Changed them with chmod a+r, works fine now.
