### ISSUE TITLE
Obsolete template not handled

### ISSUE THREAD

**Issue by PawelSzczerbiak** [deepmind/alphafold#163]
I'm getting the following error during the template searching step:
```
W0829 10:33:02.973526 47624331708224 templates.py:131] Template structure not in release dates dict: 4zon
I0829 10:33:02.973682 47624331708224 templates.py:716] Reading PDB entry from /net/scratch/datasets/alphafold//pdb_mmcif/mmcif_files/4zon.cif. Query: MRAAEPPSSTSGTRLSATVVTVRAMAEVTIVDESTGGAAPSTWTLEFLEERITVRELIRRRVYQEVGEYHASGGEFRGLVRPTARERALNGSPVGHGRVDWEEQADLAEKAFTRNGLVILVGDRQLVELDEEVDLTVHTEVTFLRLVALVGG, template: LAADADVDRMCRLLEEDGAFILKGLLPFDVVESFNRELDV
Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 310, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/app/alphafold/run_alphafold.py", line 292, in main
    random_seed=random_seed)
  File "/app/alphafold/run_alphafold.py", line 129, in predict_structure
    msa_output_dir=msa_output_dir)
  File "/app/alphafold/alphafold/data/pipeline.py", line 187, in process
    hits=hhsearch_hits)
  File "/app/alphafold/alphafold/data/templates.py", line 882, in get_templates
    kalign_binary_path=self._kalign_binary_path)
  File "/app/alphafold/alphafold/data/templates.py", line 718, in _process_single_hit
    with open(cif_path, 'r') as cif_file:
FileNotFoundError: [Errno 2] No such file or directory: '/net/scratch/datasets/alphafold/pdb_mmcif/mmcif_files/4zon.cif'
```
However, this specific PDB ID is present in the `obsolete.dat` file:
```
OBSLTE    02-JUN-21 4ZON     
```
I wonder why the app didn't handle this obsolete structure properly. Or, maybe, I missed something...

**Comment by Augustin-Zidek** [comment]
Hi Pawel, you are right, this is indeed a bug. I have a fix, we will try to push it soon. I will update this issue once it is submitted.
