### ISSUE TITLE
Fails to predict large fasta file ie Q8WZ42

### ISSUE THREAD

**Issue by obonyojimmy** [deepmind/alphafold#172]
Jackhammer fails to predict a huge fasta file 34kb of uniprotId Q8WZ42 , https://www.uniprot.org/uniprot/Q8WZ42.fasta , using reduced-dbs preset , throws error 

```
I0914 18:27:30.618590 139856854585728 run_docker.py:194] I0915 01:27:30.618098 140641092839232 run_alphafold.py:268] Have 3 models: ['model_1', 'model_2', 'model_3']
I0914 18:27:30.618706 139856854585728 run_docker.py:194] I0915 01:27:30.618213 140641092839232 run_alphafold.py:280] Using random seed 7428576221945985241 for the data pipeline
I0914 18:27:30.619273 139856854585728 run_docker.py:194] I0915 01:27:30.618959 140641092839232 jackhmmer.py:130] Launching subprocess "/usr/bin/jackhmmer -o /dev/null -A /tmp/tmpend58zz0/output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 /mnt/fasta_path_0/Q8WZ42.fasta /mnt/uniref90_database_path/uniref90.fasta"
I0914 18:27:30.762149 139856854585728 run_docker.py:194] I0915 01:27:30.761583 140641092839232 utils.py:36] Started Jackhmmer (uniref90.fasta) query
I0914 18:27:44.662442 139856854585728 run_docker.py:194] I0915 01:27:44.630804 140641092839232 utils.py:40] Finished Jackhmmer (uniref90.fasta) query in 13.868 seconds
I0914 18:27:44.665832 139856854585728 run_docker.py:194] Traceback (most recent call last):
I0914 18:27:44.665909 139856854585728 run_docker.py:194] File "/app/alphafold/run_alphafold.py", line 310, in <module>
I0914 18:27:44.665965 139856854585728 run_docker.py:194] app.run(main)
I0914 18:27:44.666018 139856854585728 run_docker.py:194] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
I0914 18:27:44.666068 139856854585728 run_docker.py:194] _run_main(main, args)
I0914 18:27:44.666118 139856854585728 run_docker.py:194] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I0914 18:27:44.666167 139856854585728 run_docker.py:194] sys.exit(main(argv))
I0914 18:27:44.666216 139856854585728 run_docker.py:194] File "/app/alphafold/run_alphafold.py", line 292, in main
I0914 18:27:44.666265 139856854585728 run_docker.py:194] random_seed=random_seed)
I0914 18:27:44.666313 139856854585728 run_docker.py:194] File "/app/alphafold/run_alphafold.py", line 129, in predict_structure
I0914 18:27:44.666361 139856854585728 run_docker.py:194] msa_output_dir=msa_output_dir)
I0914 18:27:44.666410 139856854585728 run_docker.py:194] File "/app/alphafold/alphafold/data/pipeline.py", line 134, in process
I0914 18:27:44.666459 139856854585728 run_docker.py:194] input_fasta_path)[0]
I0914 18:27:44.666507 139856854585728 run_docker.py:194] File "/app/alphafold/alphafold/data/tools/jackhmmer.py", line 163, in query
I0914 18:27:44.666556 139856854585728 run_docker.py:194] return [self._query_chunk(input_fasta_path, self.database_path)]
I0914 18:27:44.666604 139856854585728 run_docker.py:194] File "/app/alphafold/alphafold/data/tools/jackhmmer.py", line 140, in _query_chunk
I0914 18:27:44.666653 139856854585728 run_docker.py:194] 'Jackhmmer failed\nstderr:\n%s\n' % stderr)
I0914 18:27:44.666702 139856854585728 run_docker.py:194] RuntimeError: Jackhmmer failed
I0914 18:27:44.666752 139856854585728 run_docker.py:194] stderr:
I0914 18:27:44.666800 139856854585728 run_docker.py:194] b''
I0914 18:27:44.666849 139856854585728 run_docker.py:194] 

```

**Comment by Augustin-Zidek** [comment]
Hi, unfortunately AlphaFold can't handle sequences that are so long, we have validated AlphaFold for sequences up to 2,700 residues. 

However, since this is a human protein, we folded all of its 1,400-residue fragments (with 200-residue overlaps) and it is available for download from the AlphaFold Protein Structure Database here: https://alphafold.com/download -> https://ftp.ebi.ac.uk/pub/databases/alphafold/UP000005640_9606_HUMAN.tar

You can then align and combine the predictions into a single structure using e.g. ChimeraX, see the tutorial here: https://rbvi.github.io/chimerax-recipes/big_alphafold/bigalpha.html

Note also that this has already been done for titin: https://mobile.twitter.com/UCSFChimeraX/status/1435760774824169474
