### ISSUE TITLE
ModuleNotFoundError: No module named 'absl'

### ISSUE THREAD

**Issue by lucajovine** [deepmind/alphafold#178]
Hello, after updating to the last commit I get this error when running the program:

Traceback (most recent call last):
  File "/usr/local/alphafold/alphafold/docker/run_docker.py", line 21, in <module>
    from absl import app
ModuleNotFoundError: No module named 'absl'

which I never encountered before. Any idea of how to solve this? Thanks!

**Comment by lucajovine** [comment]
Actually, I could fix this with the following:

pip install absl-py

which then led to a similar issue with the docker module:

Traceback (most recent call last):
  File "/usr/local/alphafold/alphafold/docker/run_docker.py", line 24, in <module>
    import docker
ModuleNotFoundError: No module named 'docker'

that could also be fixed with:

pip install docker

...after which the programs ran as before. But I suppose I should still report this because, as I wrote in my original message, it did not seem to happen with previous commits.
