### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'hhblits'

### ISSUE THREAD

**Issue by Sam-Lee-Github-Account** [deepmind/alphafold#191]
**Anyone heve some Error?**

### more message about the error:

Traceback (most recent call last):
  File "run_alphafold.py", line 339, in <module>
    app.run(main)
  File "/root/miniconda3/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/root/miniconda3/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "run_alphafold.py", line 311, in main
    predict_structure(
  File "run_alphafold.py", line 171, in predict_structure
    feature_dict = data_pipeline.process(
  File "/home/lisen_data/alphafold/alphafold_no_docker/alphafold/alphafold/data/pipeline.py", line 154, in process
    hhblits_bfd_uniclust_result = self.hhblits_bfd_uniclust_runner.query(
  File "/home/lisen_data/alphafold/alphafold_no_docker/alphafold/alphafold/data/tools/hhblits.py", line 129, in query
    process = subprocess.Popen(
  File "/root/miniconda3/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/root/miniconda3/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'hhblits'

**Comment by kgerman73** [comment]
I'm getting a similar error starting the contaioner, any ideas what's causing this?

$ python3 docker/run_docker.py --fasta_paths=T1050.fasta --max_template_date=2020-05-14
I1001 17:10:07.189580 139913278838592 run_docker.py:119] Mounting /home/kgerman/alphafold -> /mnt/fasta_path_0
I1001 17:10:07.189983 139913278838592 run_docker.py:119] Mounting /disk1/alphafold_db/uniref90 -> /mnt/uniref90_database_path
I1001 17:10:07.190194 139913278838592 run_docker.py:119] Mounting /disk1/alphafold_db/mgnify -> /mnt/mgnify_database_path
I1001 17:10:07.190383 139913278838592 run_docker.py:119] Mounting /disk1/alphafold_db/pdb70 -> /mnt/pdb70_database_path
I1001 17:10:07.190559 139913278838592 run_docker.py:119] Mounting /disk1 -> /mnt/data_dir
I1001 17:10:07.190734 139913278838592 run_docker.py:119] Mounting /disk1/alphafold_db/pdb_mmcif -> /mnt/template_mmcif_dir
I1001 17:10:07.190918 139913278838592 run_docker.py:119] Mounting /disk1/alphafold_db/pdb_mmcif -> /mnt/obsolete_pdbs_path
I1001 17:10:07.191104 139913278838592 run_docker.py:119] Mounting /disk1/alphafold_db/uniclust30/uniclust30_2018_08 -> /mnt/uniclust30_database_path
I1001 17:10:07.191277 139913278838592 run_docker.py:119] Mounting /disk1/alphafold_db/bfd -> /mnt/bfd_database_path
I1001 17:10:11.354830 139913278838592 run_docker.py:193] /opt/conda/lib/python3.7/site-packages/absl/flags/_validators.py:206: UserWarning: Flag --preset has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
I1001 17:10:11.355509 139913278838592 run_docker.py:193] 'command line!' % flag_name)
I1001 17:10:11.845108 139913278838592 run_docker.py:193] I1001 21:10:11.843507 140190630266688 templates.py:836] Using precomputed obsolete pdbs /mnt/obsolete_pdbs_path/obsolete.dat.
I1001 17:10:11.846926 139913278838592 run_docker.py:193] Traceback (most recent call last):
I1001 17:10:11.847382 139913278838592 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 310, in <module>
I1001 17:10:11.847749 139913278838592 run_docker.py:193] app.run(main)
I1001 17:10:11.848105 139913278838592 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
I1001 17:10:11.848434 139913278838592 run_docker.py:193] _run_main(main, args)
I1001 17:10:11.848757 139913278838592 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I1001 17:10:11.849090 139913278838592 run_docker.py:193] sys.exit(main(argv))
I1001 17:10:11.849403 139913278838592 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 243, in main
I1001 17:10:11.849754 139913278838592 run_docker.py:193] obsolete_pdbs_path=FLAGS.obsolete_pdbs_path)
I1001 17:10:11.850081 139913278838592 run_docker.py:193] File "/app/alphafold/alphafold/data/templates.py", line 837, in __init__
I1001 17:10:11.850404 139913278838592 run_docker.py:193] self._obsolete_pdbs = _parse_obsolete(obsolete_pdbs_path)
I1001 17:10:11.850715 139913278838592 run_docker.py:193] File "/app/alphafold/alphafold/data/templates.py", line 137, in _parse_obsolete
I1001 17:10:11.851038 139913278838592 run_docker.py:193] with open(obsolete_file_path) as f:
I1001 17:10:11.851351 139913278838592 run_docker.py:193] FileNotFoundError: [Errno 2] No such file or directory: '/mnt/obsolete_pdbs_path/obsolete.dat'

**Comment by Sam-Lee-Github-Account** [comment]
Hi，Do you slove it?  last line in your log :'/mnt/obsolete_pdbs_path/obsolete.dat',so you need to add this path to parm like this:
--obsolete_pdbs_path=/mnt/obsolete_pdbs_path/obsolete.dat
Or you need to check the database path in run_docker.py file.

**Comment by Sam-Lee-Github-Account** [comment]
> I'm getting a similar error starting the contaioner, any ideas what's causing this?
> 
> $ python3 docker/run_docker.py --fasta_paths=T1050.fasta --max_template_date=2020-05-14 I1001 17:10:07.189580 139913278838592 run_docker.py:119] Mounting /home/kgerman/alphafold -> /mnt/fasta_path_0 I1001 17:10:07.189983 139913278838592 run_docker.py:119] Mounting /disk1/alphafold_db/uniref90 -> /mnt/uniref90_database_path I1001 17:10:07.190194 139913278838592 run_docker.py:119] Mounting /disk1/alphafold_db/mgnify -> /mnt/mgnify_database_path I1001 17:10:07.190383 139913278838592 run_docker.py:119] Mounting /disk1/alphafold_db/pdb70 -> /mnt/pdb70_database_path I1001 17:10:07.190559 139913278838592 run_docker.py:119] Mounting /disk1 -> /mnt/data_dir I1001 17:10:07.190734 139913278838592 run_docker.py:119] Mounting /disk1/alphafold_db/pdb_mmcif -> /mnt/template_mmcif_dir I1001 17:10:07.190918 139913278838592 run_docker.py:119] Mounting /disk1/alphafold_db/pdb_mmcif -> /mnt/obsolete_pdbs_path I1001 17:10:07.191104 139913278838592 run_docker.py:119] Mounting /disk1/alphafold_db/uniclust30/uniclust30_2018_08 -> /mnt/uniclust30_database_path I1001 17:10:07.191277 139913278838592 run_docker.py:119] Mounting /disk1/alphafold_db/bfd -> /mnt/bfd_database_path I1001 17:10:11.354830 139913278838592 run_docker.py:193] /opt/conda/lib/python3.7/site-packages/absl/flags/_validators.py:206: UserWarning: Flag --preset has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line! I1001 17:10:11.355509 139913278838592 run_docker.py:193] 'command line!' % flag_name) I1001 17:10:11.845108 139913278838592 run_docker.py:193] I1001 21:10:11.843507 140190630266688 templates.py:836] Using precomputed obsolete pdbs /mnt/obsolete_pdbs_path/obsolete.dat. I1001 17:10:11.846926 139913278838592 run_docker.py:193] Traceback (most recent call last): I1001 17:10:11.847382 139913278838592 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 310, in I1001 17:10:11.847749 139913278838592 run_docker.py:193] app.run(main) I1001 17:10:11.848105 139913278838592 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run I1001 17:10:11.848434 139913278838592 run_docker.py:193] _run_main(main, args) I1001 17:10:11.848757 139913278838592 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main I1001 17:10:11.849090 139913278838592 run_docker.py:193] sys.exit(main(argv)) I1001 17:10:11.849403 139913278838592 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 243, in main I1001 17:10:11.849754 139913278838592 run_docker.py:193] obsolete_pdbs_path=FLAGS.obsolete_pdbs_path) I1001 17:10:11.850081 139913278838592 run_docker.py:193] File "/app/alphafold/alphafold/data/templates.py", line 837, in **init** I1001 17:10:11.850404 139913278838592 run_docker.py:193] self._obsolete_pdbs = _parse_obsolete(obsolete_pdbs_path) I1001 17:10:11.850715 139913278838592 run_docker.py:193] File "/app/alphafold/alphafold/data/templates.py", line 137, in _parse_obsolete I1001 17:10:11.851038 139913278838592 run_docker.py:193] with open(obsolete_file_path) as f: I1001 17:10:11.851351 139913278838592 run_docker.py:193] FileNotFoundError: [Errno 2] No such file or directory: '/mnt/obsolete_pdbs_path/obsolete.dat'

Hi，Do you slove it? last line in your log :'/mnt/obsolete_pdbs_path/obsolete.dat',so you need to add this path to parm like this:
--obsolete_pdbs_path=/mnt/obsolete_pdbs_path/obsolete.dat
Or you need to check the database path in run_docker.py file.
