### ISSUE TITLE
jaxlib build RuntimeError

### ISSUE THREAD

**Issue by rothita** [deepmind/alphafold#200]
Hi,
thank you for the great tool!
I've tried to run the  the README-example command: 
python3 docker/run_docker.py --fasta_paths=<path/to/my/protein>.fasta --max_template_date=2020-05-14
However . I get the following error:

```
itair> python3 docker/run_docker.py --fasta_paths=/home/path/to/protein.fa --max_template_date=2021-08-14
I1007 12:01:53.817858 140395800868672 run_docker.py:119] Mounting /home/path/to/protein -> /mnt/fasta_path_0
I1007 12:01:53.818213 140395800868672 run_docker.py:119] Mounting /home/databases/AlphaFold/DataBases/uniref90 -> /mnt/uniref90_database_path
I1007 12:01:53.818374 140395800868672 run_docker.py:119] Mounting /home/databases/AlphaFold/DataBases/mgnify -> /mnt/mgnify_database_path
I1007 12:01:53.818537 140395800868672 run_docker.py:119] Mounting /home/databases/AlphaFold/DataBases/pdb70 -> /mnt/pdb70_database_path
I1007 12:01:53.818686 140395800868672 run_docker.py:119] Mounting /home/databases/AlphaFold -> /mnt/data_dir
I1007 12:01:53.818843 140395800868672 run_docker.py:119] Mounting /home/databases/AlphaFold/DataBases/pdb_mmcif -> /mnt/template_mmcif_dir
I1007 12:01:53.818995 140395800868672 run_docker.py:119] Mounting /home/databases/AlphaFold/DataBases/pdb_mmcif -> /mnt/obsolete_pdbs_path
I1007 12:01:53.819147 140395800868672 run_docker.py:119] Mounting /home/databases/AlphaFold/DataBases/uniclust30/uniclust30_2018_08 -> /mnt/uniclust30_database_path
I1007 12:01:53.819298 140395800868672 run_docker.py:119] Mounting /home/databases/AlphaFold/DataBases/bfd -> /mnt/bfd_database_path
-----> /var/run/docker.sock <---
-----> /var/run/docker.sock <---
-----> /var/run/docker.sock <---
-----> /var/run/docker.sock <---
-----> /var/run/docker.sock <---
I1007 12:01:55.300768 140395800868672 run_docker.py:193] Traceback (most recent call last):
I1007 12:01:55.300985 140395800868672 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 31, in <module>
I1007 12:01:55.301120 140395800868672 run_docker.py:193] from alphafold.model import data
I1007 12:01:55.301282 140395800868672 run_docker.py:193] File "/app/alphafold/alphafold/model/data.py", line 20, in <module>
I1007 12:01:55.301428 140395800868672 run_docker.py:193] from alphafold.model import utils
I1007 12:01:55.301571 140395800868672 run_docker.py:193] File "/app/alphafold/alphafold/model/utils.py", line 21, in <module>
I1007 12:01:55.301706 140395800868672 run_docker.py:193] import haiku as hk
I1007 12:01:55.301839 140395800868672 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/haiku/__init__.py", line 17, in <module>
I1007 12:01:55.301974 140395800868672 run_docker.py:193] from haiku import data_structures
I1007 12:01:55.302108 140395800868672 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/haiku/data_structures.py", line 17, in <module>
I1007 12:01:55.302242 140395800868672 run_docker.py:193] from haiku._src.data_structures import to_immutable_dict
I1007 12:01:55.302376 140395800868672 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/data_structures.py", line 30, in <module>
I1007 12:01:55.302523 140395800868672 run_docker.py:193] from haiku._src import utils
I1007 12:01:55.302658 140395800868672 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/utils.py", line 24, in <module>
I1007 12:01:55.302792 140395800868672 run_docker.py:193] import jax
I1007 12:01:55.302926 140395800868672 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/__init__.py", line 37, in <module>
I1007 12:01:55.303060 140395800868672 run_docker.py:193] from . import config as _config_module
I1007 12:01:55.303195 140395800868672 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/config.py", line 18, in <module>
I1007 12:01:55.303330 140395800868672 run_docker.py:193] from jax._src.config import config
I1007 12:01:55.303482 140395800868672 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/_src/config.py", line 27, in <module>
I1007 12:01:55.303618 140395800868672 run_docker.py:193] from jax._src import lib
I1007 12:01:55.303753 140395800868672 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/_src/lib/__init__.py", line 71, in <module>
I1007 12:01:55.303889 140395800868672 run_docker.py:193] cpu_feature_guard.check_cpu_features()
I1007 12:01:55.304023 140395800868672 run_docker.py:193] RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source.
```

my environment:
OS: centos7
CUDA Version: 11.4
jaxlib==0.1.69
thanks!

**Comment by tomwardio** [comment]
Hi @juliandehne and @truatpasteurdotfr 

Thanks for reporting this issue, unfortunately we are unable to support all types of virtualization environments. Please do let us know if you have any further issues once your virtualization environment supports AVX.

Regards,
Tom
