### ISSUE TITLE
HHblits failed: no stdout and no stderr message 

### ISSUE THREAD

**Issue by alejocrojo09** [deepmind/alphafold#211]
Dear all,

I am trying to run Alphafold using a singularity image built from docker image. I get the following error with no explained reason:

```
(alphafold) Singularity> ./run.sh -d /mnt -o /mnt -m model_1 -f /mnt/P04637.fasta -t 2020-10-21
/opt/miniconda3/envs/alphafold/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --preset has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
I1021 13:49:13.586515 140089945392960 templates.py:848] Using precomputed obsolete pdbs /mnt/pdb_mmcif/obsolete.dat.
I1021 13:49:13.965163 140089945392960 tpu_client.py:54] Starting the local TPU driver.
I1021 13:49:13.982826 140089945392960 xla_bridge.py:212] Unable to initialize backend 'tpu_driver': Not found: Unable to find driver in registry given worker: local://
I1021 13:49:15.071753 140089945392960 xla_bridge.py:212] Unable to initialize backend 'tpu': Invalid argument: TpuPlatform is not available.
I1021 13:49:16.236475 140089945392960 run_alphafold.py:267] Have 1 models: ['model_1']
I1021 13:49:16.236614 140089945392960 run_alphafold.py:280] Using random seed 2748227342241422278 for the data pipeline
I1021 13:49:16.237159 140089945392960 jackhmmer.py:130] Launching subprocess "/opt/miniconda3/envs/alphafold/bin/jackhmmer -o /dev/null -A /tmp/tmp_k0s27ej/output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 /mnt/P04637.fasta /mnt/uniref90/uniref90.fasta"
I1021 13:49:16.304537 140089945392960 utils.py:36] Started Jackhmmer (uniref90.fasta) query
I1021 14:00:35.346851 140089945392960 utils.py:40] Finished Jackhmmer (uniref90.fasta) query in 679.041 seconds
I1021 14:00:35.352658 140089945392960 jackhmmer.py:130] Launching subprocess "/opt/miniconda3/envs/alphafold/bin/jackhmmer -o /dev/null -A /tmp/tmpm7v_s90g/output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 /mnt/P04637.fasta /mnt/mgnify/mgy_clusters_2018_12.fa"
I1021 14:00:35.414126 140089945392960 utils.py:36] Started Jackhmmer (mgy_clusters_2018_12.fa) query
I1021 14:12:38.146909 140089945392960 utils.py:40] Finished Jackhmmer (mgy_clusters_2018_12.fa) query in 722.732 seconds
I1021 14:12:38.300453 140089945392960 hhsearch.py:76] Launching subprocess "/opt/miniconda3/envs/alphafold/bin/hhsearch -i /tmp/tmp7h3asaho/query.a3m -o /tmp/tmp7h3asaho/output.hhr -maxseq 1000000 -d /mnt/pdb70/pdb70"
I1021 14:12:38.363389 140089945392960 utils.py:36] Started HHsearch query
I1021 14:13:46.305898 140089945392960 utils.py:40] Finished HHsearch query in 67.942 seconds
I1021 14:13:46.556297 140089945392960 hhblits.py:128] Launching subprocess "/opt/miniconda3/envs/alphafold/bin/hhblits -i /mnt/P04637.fasta -cpu 4 -oa3m /tmp/tmph6bdp5f3/output.a3m -o /dev/null -n 3 -e 0.001 -maxseq 1000000 -realign_max 100000 -maxfilt 100000 -min_prefilter_hits 1000 -d /mnt/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt -d /mnt/uniclust30/uniclust30_2018_08/uniclust30_2018_08"
I1021 14:13:46.619905 140089945392960 utils.py:36] Started HHblits query
I1021 14:13:55.527817 140089945392960 utils.py:40] Finished HHblits query in 8.905 seconds
E1021 14:13:55.537471 140089945392960 hhblits.py:138] HHblits failed. HHblits stderr begin:
E1021 14:13:55.537573 140089945392960 hhblits.py:142] HHblits stderr end
Traceback (most recent call last):
  File "/opt/alphafold/run_alphafold.py", line 310, in <module>
    app.run(main)
  File "/opt/miniconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/miniconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/opt/alphafold/run_alphafold.py", line 284, in main
    predict_structure(
  File "/opt/alphafold/run_alphafold.py", line 127, in predict_structure
    feature_dict = data_pipeline.process(
  File "/opt/alphafold/alphafold/data/pipeline.py", line 173, in process
    hhblits_bfd_uniclust_result = self.hhblits_bfd_uniclust_runner.query(
  File "/opt/alphafold/alphafold/data/tools/hhblits.py", line 143, in query
    raise RuntimeError('HHblits failed\nstdout:\n%s\n\nstderr:\n%s\n' % (
RuntimeError: HHblits failed
stdout:


stderr:

```

Do you have any suggestions for this issue?

Thank you very much your help!

Kind regards.

**Comment by Augustin-Zidek** [comment]
Unfortunately we don't have the capacity to maintain and support running AlphaFold using Singularity -- I recommend running AlphaFold using the Docker setup we provide.

**Comment by celalp** [comment]
I saw this happen in other contexts make sure that whatever cpu you are using is avx2 compatible. I think that should be included in the documentations.
