### ISSUE TITLE
RuntimeError: hmmsearch failed:

### ISSUE THREAD

**Issue by wangyanmin123** [deepmind/alphafold#267]
Hello, this error is reported when we run the 2.1.1 version to the comparison

This is the command to run                                                                                                                                                 
  --fasta_paths=/home/zhangli_lab/wangyanmin/scratch60/AL/ENSANAP00000023235_Anan.fasta --output_dir=/home/zhangli_lab/wangyanmin/scratch60/AL --max_template_date=2020-05-04 --model_preset=multimer --is_prokaryote_list=true

I1122 07:56:56.952677 47867200451136 templates.py:857] Using precomputed obsolete pdbs /GPFS/PUB/alphafold/Genetic_databases_2.1.1/pdb_mmcif/obsolete.dat.
I1122 07:56:57.172171 47867200451136 xla_bridge.py:231] Unable to initialize backend 'tpu_driver': Not found: Unable to find driver in registry given worker: 
I1122 07:56:58.268981 47867200451136 xla_bridge.py:231] Unable to initialize backend 'tpu': Invalid argument: TpuPlatform is not available.
I1122 07:57:03.161936 47867200451136 run_alphafold.py:385] Have 5 models: ['model_1_multimer', 'model_2_multimer', 'model_3_multimer', 'model_4_multimer', 'mode
l_5_multimer']I1122 07:57:03.162114 47867200451136 run_alphafold.py:397] Using random seed 1573723199699798384 for the data pipeline
I1122 07:57:03.162298 47867200451136 run_alphafold.py:150] Predicting ENSANAP00000023235_Anan
I1122 07:57:03.163925 47867200451136 pipeline_multimer.py:211] Running monomer pipeline on chain A: ENSANAP00000023235_Anan
I1122 07:57:03.165411 47867200451136 jackhmmer.py:130] Launching subprocess "/usr/bin/jackhmmer -o /dev/null -A /tmp/tmp0ds5xc42/output.sto --noali --F1 0.0005 
--F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 /tmp/tmpf3k38a5l.fasta /GPFS/PUB/alphafold/Genetic_databases_2.1.1/uniref90/uniref90.fasta"I1122 07:57:03.179512 47867200451136 utils.py:36] Started Jackhmmer (uniref90.fasta) query
I1122 08:02:06.785325 47867200451136 utils.py:40] Finished Jackhmmer (uniref90.fasta) query in 303.606 seconds
I1122 08:02:06.861017 47867200451136 jackhmmer.py:130] Launching subprocess "/usr/bin/jackhmmer -o /dev/null -A /tmp/tmpvfniwqjh/output.sto --noali --F1 0.0005 
--F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 /tmp/tmpf3k38a5l.fasta /GPFS/PUB/alphafold/Genetic_databases_2.1.1/mgnify/mgy_clusters_2018_12.fa"I1122 08:02:06.873820 47867200451136 utils.py:36] Started Jackhmmer (mgy_clusters_2018_12.fa) query
I1122 08:07:23.341028 47867200451136 utils.py:40] Finished Jackhmmer (mgy_clusters_2018_12.fa) query in 316.467 seconds
I1122 08:07:25.624193 47867200451136 hmmbuild.py:121] Launching subprocess ['/usr/bin/hmmbuild', '--hand', '--amino', '/tmp/tmp5fssblae/output.hmm', '/tmp/tmp5fssblae/query.msa']
I1122 08:07:25.639650 47867200451136 utils.py:36] Started hmmbuild query
I1122 08:07:26.899096 47867200451136 hmmbuild.py:129] hmmbuild stdout:
# hmmbuild :: profile HMM construction from multiple sequence alignments
# HMMER 3.1b2 (February 2015); http://hmmer.org/
# Copyright (C) 2015 Howard Hughes Medical Institute.
# Freely distributed under the GNU General Public License (GPLv3).
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# input alignment file:             /tmp/tmp5fssblae/query.msa
# output HMM file:                  /tmp/tmp5fssblae/output.hmm
# input alignment is asserted as:   protein
# model architecture construction:  hand-specified by RF annotation
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# idx name                  nseq  alen  mlen eff_nseq re/pos description
#---- -------------------- ----- ----- ----- -------- ------ -----------
1     query                 5318  2946   596     6.21  0.590 

# CPU time: 1.19u 0.04s 00:00:01.23 Elapsed: 00:00:01.23

stderr:

I1122 08:07:26.899223 47867200451136 utils.py:40] Finished hmmbuild query in 1.259 seconds
I1122 08:07:26.914727 47867200451136 hmmsearch.py:103] Launching sub-process ['/usr/bin/hmmsearch', '--noali', '--cpu', '8', '--F1', '0.1', '--F2', '0.1', '--F3', '0.1', '--incE', '100', '-E',
 '100', '--domE', '100', '--incdomE', '100', '-A', '/tmp/tmp7f8_b9as/output.sto', '/tmp/tmp7f8_b9as/query.hmm', '/GPFS/PUB/alphafold/Genetic_databases_2.1.1/pdb_seqres']I1122 08:07:26.929349 47867200451136 utils.py:36] Started hmmsearch (pdb_seqres) query
I1122 08:07:26.933438 47867200451136 utils.py:40] Finished hmmsearch (pdb_seqres) query in 0.004 seconds
Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 427, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/app/alphafold/run_alphafold.py", line 412, in main
    is_prokaryote=is_prokaryote)
  File "/app/alphafold/run_alphafold.py", line 169, in predict_structure
    is_prokaryote=is_prokaryote)
  File "/app/alphafold/alphafold/data/pipeline_multimer.py", line 271, in process
    is_homomer_or_monomer=is_homomer_or_monomer)
  File "/app/alphafold/alphafold/data/pipeline_multimer.py", line 214, in _process_single_chain
    msa_output_dir=chain_msa_output_dir)
  File "/app/alphafold/alphafold/data/pipeline.py", line 176, in process
    pdb_templates_result = self.template_searcher.query(msa_for_templates)
  File "/app/alphafold/alphafold/data/tools/hmmsearch.py", line 79, in query
    return self.query_with_hmm(hmm)
  File "/app/alphafold/alphafold/data/tools/hmmsearch.py", line 114, in query_with_hmm
    stdout.decode('utf-8'), stderr.decode('utf-8')))
RuntimeError: hmmsearch failed:
stdout:

stderr:
Fatal exception (source file esl_buffer.c, line 1608):
failed to slurp /GPFS/PUB/alphafold/Genetic_databases_2.1.1/pdb_seqres

May i ask what is the problem，thanks

**Comment by Augustin-Zidek** [comment]
It looks like the PDB seqres database path (`/GPFS/PUB/alphafold/Genetic_databases_2.1.1/pdb_seqres`) is not correct, or inaccessible to Hmmsearch.

**Comment by wangyanmin123** [comment]
> It looks like the PDB seqres database path (`/GPFS/PUB/alphafold/Genetic_databases_2.1.1/pdb_seqres`) is not correct, or inaccessible to Hmmsearch.


Hello, I checked my setting path and there seems to be no problem. This is the storage path of the database
[root@login01 pdb_seqres]# ll
total 214016
-rw-r--r-- 1 root root 218895790 Nov 22 13:29 pdb_seqres.txt
[root@login01 pdb_seqres]# pwd
/GPFS/PUB/alphafold/Genetic_databases_2.1.1/pdb_seqres
This is the database path set at runtime
--pdb_seqres_database_path=/GPFS/PUB/alphafold/Genetic_databases_2.1.1/pdb_seqres/
I don’t know if there are other special settings

**Comment by wangyanmin123** [comment]
> It looks like the PDB seqres database path (`/GPFS/PUB/alphafold/Genetic_databases_2.1.1/pdb_seqres`) is not correct, or inaccessible to Hmmsearch.

Just set it to this path path/pdb_seqres/pdb_seqres.txt Thank you very much

**Comment by Lsz-20** [comment]
Hello~ maybe the same question?
when i run monomer  it works well, but multimer it show me this :
![QQ图片20211205232246](https://user-images.githubusercontent.com/60343452/144778094-6ade34c0-9ceb-4995-91a1-544865ae8f4f.jpg)
if you have any ideas to solve this? @wangyanmin123 @Augustin-Zidek 
Thanks!

**Comment by berjeh** [comment]
@Lsz-20 were you able to solve your issue? If yes please share also with us

**Comment by Lsz-20** [comment]
> @Lsz-20 were you able to solve your issue? If yes please share also with us

Seems to be a problem with several of these package versions, in particular the jax jaxlib tensorflow.
Now i have use jax==0.2.24 & tensorflow_gpu-2.5.0 & jaxlib-0.1.71. It works properly

**Comment by meatball1982** [comment]
Another option,( May not for all the uniref90 and 1608 problem), just an option to try. 

I modified 
openfold-pl_upgrades/openfold/data/tools/jackhmmer.py

from
 40 #        e_value: float = 0.0001,
to
 41         e_value: float = 0.001,
 
 It also works, and fix the problem.
 
 "Fatal exception (source file esl_buffer.c, line 1608):"

I used openfold, not alphafold. 
I believe that some sequences( Here, in my case, 6KWC is shown below) may not get an output with E = 0.0001. Then, the command 
jackhmmer input.fasta uniref90.fasta 

give the error output.

>6KWC_1
GSTIQPGTGYNNGYFYSYWNDGHGGVTYTNGPGGQFSVNWSNSGEFVGGKGWQPGTKNKVINFSGSYNPNGNSYLSVYGWSRNPLIEYYIVENFGTYNPSTGATKLGEVTSDGSVYDIYRTQRVNQPSIIGTATFYQYWSVRRNHRSSGSVNTANHFNAWAQQGLTLGTMDYQIVAVQGYFSSGSASITVS
