### ISSUE TITLE
Docker build conda error

### ISSUE THREAD

**Issue by gerdos** [deepmind/alphafold#270]
I am trying to install AlphaFold on a new machine and I get the following conda error while building:

docker build -f docker/Dockerfile -t alphafold .

```Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.9/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/opt/conda/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/opt/conda/lib/python3.9/site-packages/conda/cli/main_update.py", line 20, in execute
        install(args, parser, 'update')
      File "/opt/conda/lib/python3.9/site-packages/conda/cli/install.py", line 317, in install
        handle_txn(unlink_link_transaction, prefix, args, newenv)
      File "/opt/conda/lib/python3.9/site-packages/conda/cli/install.py", line 346, in handle_txn
        unlink_link_transaction.execute()
      File "/opt/conda/lib/python3.9/site-packages/conda/core/link.py", line 250, in execute
        self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
      File "/opt/conda/lib/python3.9/site-packages/conda/core/link.py", line 722, in _execute
        action.cleanup()
      File "/opt/conda/lib/python3.9/site-packages/conda/core/path_actions.py", line 1021, in cleanup
        rm_rf(self.holding_full_path, clean_empty_parents=True)
      File "/opt/conda/lib/python3.9/site-packages/conda/gateways/disk/delete.py", line 179, in rm_rf
        remove_empty_parent_paths(path)
      File "/opt/conda/lib/python3.9/site-packages/conda/gateways/disk/delete.py", line 152, in remove_empty_parent_paths
        rmdir(parent_path)
    OSError: [Errno 22] Invalid argument: '/opt/conda/lib/python3.9/site-packages/requests-2.25.1.dist-info'

`$ /opt/conda/bin/conda update -qy conda`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/opt/conda
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
                     PATH=/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sb
                          in:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __linux=4.4.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.9.5 Linux/4.4.0-217-generic ubuntu/18.04.5 glibc/2.27
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

Upload successful.
The command '/bin/bash -c conda update -qy conda     && conda install -y -c conda-forge       openmm=7.5.1       cudatoolkit==${CUDA_VERSION}       pdbfixer       pip       python=3.7' returned a non-zero code: 1
```

**Comment by truatpasteurdotfr** [comment]
Hi,

It was building fine 3 days ago from a slighly modifierd Dockerfile https://github.com/truatpasteurdotfr/alphafold/runs/4367346072 
I have manually restarted a build https://github.com/truatpasteurdotfr/alphafold/runs/4405601427

**Comment by Augustin-Zidek** [comment]
Closing this issue for now, feel free to reopen if this is still a problem.
