### ISSUE TITLE
Failed to load in-memory CUBIN: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure

### ISSUE THREAD

**Issue by ShannonTown** [deepmind/alphafold#277]
Hi, I'm running alphafold in docker with 4 K80 GPU cores, CUDA version 10.1, cuDNN version 7.6.5, and I ran into the "Failed to load in-memory CUBIN: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure" error if I set `--gpu_devices=0,1,2,3` (more relevant output pasted below). 
On the other hand, iff I specify only one GPU core, such as `--gpu_devices=1`, initially it would return the error "failed to alloc 16732312576 bytes unified memory; result: CUDA_ERROR_OUT_OF_MEMORY: out of memory", but it can eventually complete the prediction on a fasta file with a single sequence (although still never finishes predicting a fasta file with multimer sequences of total length <500 aa).

Has anyone encountered similar issue that can help trouble shooting? Thank you!

```
I1127 19:30:07.407217 139917319264064 run_docker.py:222] I1128 00:30:07.406113 139678588670144 model.py:176] Output shape was {'distogram': {'bin_edges': (63,), 'logits': (63, 63, 64)}, 'experimentally_resolved': {'logits': (63, 37)}, 'masked_msa': {'logits': (508, 63, 23)}, 'predicted_lddt': {'logits': (63, 50)}, 'structure_module': {'final_atom_mask': (63, 37), 'final_atom_positions': (63, 37, 3)}, 'plddt': (63,), 'ranking_confidence': ()}
I1127 19:30:07.407442 139917319264064 run_docker.py:222] I1128 00:30:07.406480 139678588670144 run_alphafold.py:199] Total JAX model model_1 on DBD predict time (includes compilation time, see --benchmark): 888.2s
I1127 19:30:17.694299 139917319264064 run_docker.py:222] I1128 00:30:17.693355 139678588670144 amber_minimize.py:176] alterations info: {'nonstandard_residues': [], 'removed_heterogens': set(), 'missing_residues': {}, 'missing_heavy_atoms': {}, 'missing_terminals': {<Residue 62 (VAL) of chain 0>: ['OXT']}, 'Se_in_MET': [], 'removed_chains': {0: []}}
I1127 19:30:17.803968 139917319264064 run_docker.py:222] I1128 00:30:17.803377 139678588670144 amber_minimize.py:405] Minimizing protein, attempt 1 of 100.
I1127 19:30:18.022173 139917319264064 run_docker.py:222] I1128 00:30:18.021294 139678588670144 amber_minimize.py:69] Restraining 492 / 1003 particles.
I1127 19:30:25.255502 139917319264064 run_docker.py:222] I1128 00:30:25.254601 139678588670144 amber_minimize.py:176] alterations info: {'nonstandard_residues': [], 'removed_heterogens': set(), 'missing_residues': {}, 'missing_heavy_atoms': {}, 'missing_terminals': {}, 'Se_in_MET': [], 'removed_chains': {0: []}}
I1127 19:30:25.522432 139917319264064 run_docker.py:222] 2021-11-28 00:30:25.521781: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2040] Execution of replica 0 failed: Internal: Failed to load in-memory CUBIN: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
I1127 19:30:25.539318 139917319264064 run_docker.py:222] Traceback (most recent call last):
I1127 19:30:25.539550 139917319264064 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 427, in <module>
I1127 19:30:25.539715 139917319264064 run_docker.py:222] app.run(main)
I1127 19:30:25.539821 139917319264064 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
I1127 19:30:25.539974 139917319264064 run_docker.py:222] _run_main(main, args)
I1127 19:30:25.540073 139917319264064 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I1127 19:30:25.540174 139917319264064 run_docker.py:222] sys.exit(main(argv))
I1127 19:30:25.540267 139917319264064 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 412, in main
I1127 19:30:25.540380 139917319264064 run_docker.py:222] is_prokaryote=is_prokaryote)
I1127 19:30:25.540477 139917319264064 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 237, in predict_structure
I1127 19:30:25.540588 139917319264064 run_docker.py:222] relaxed_pdb_str, _, _ = amber_relaxer.process(prot=unrelaxed_protein)
I1127 19:30:25.540682 139917319264064 run_docker.py:222] File "/app/alphafold/alphafold/relax/relax.py", line 62, in process
I1127 19:30:25.540771 139917319264064 run_docker.py:222] max_outer_iterations=self._max_outer_iterations)
I1127 19:30:25.540861 139917319264064 run_docker.py:222] File "/app/alphafold/alphafold/relax/amber_minimize.py", line 482, in run_pipeline
I1127 19:30:25.540950 139917319264064 run_docker.py:222] ret.update(get_violation_metrics(prot))
I1127 19:30:25.541038 139917319264064 run_docker.py:222] File "/app/alphafold/alphafold/relax/amber_minimize.py", line 356, in get_violation_metrics
I1127 19:30:25.541127 139917319264064 run_docker.py:222] structural_violations, struct_metrics = find_violations(prot)
I1127 19:30:25.541215 139917319264064 run_docker.py:222] File "/app/alphafold/alphafold/relax/amber_minimize.py", line 343, in find_violations
I1127 19:30:25.541304 139917319264064 run_docker.py:222] "clash_overlap_tolerance": 1.5,  # Taken from model config.
I1127 19:30:25.541408 139917319264064 run_docker.py:222] File "/app/alphafold/alphafold/model/folding.py", line 748, in find_structural_violations
I1127 19:30:25.541498 139917319264064 run_docker.py:222] tolerance_factor_hard=config.violation_tolerance_factor)
I1127 19:30:25.541586 139917319264064 run_docker.py:222] File "/app/alphafold/alphafold/model/all_atom.py", line 664, in between_residue_bond_loss
I1127 19:30:25.541674 139917319264064 run_docker.py:222] 1e-6 + jnp.sum(squared_difference(this_c_pos, next_n_pos), axis=-1))
I1127 19:30:25.541762 139917319264064 run_docker.py:222] File "/app/alphafold/alphafold/model/all_atom.py", line 47, in squared_difference
I1127 19:30:25.541850 139917319264064 run_docker.py:222] return jnp.square(x - y)
I1127 19:30:25.541939 139917319264064 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
I1127 19:30:25.542027 139917319264064 run_docker.py:222] return fun(*args, **kwargs)
I1127 19:30:25.542114 139917319264064 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/_src/api.py", line 419, in cache_miss
I1127 19:30:25.542222 139917319264064 run_docker.py:222] donated_invars=donated_invars, inline=inline)
I1127 19:30:25.542315 139917319264064 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 1632, in bind
I1127 19:30:25.542421 139917319264064 run_docker.py:222] return call_bind(self, fun, *args, **params)
I1127 19:30:25.542540 139917319264064 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 1623, in call_bind
I1127 19:30:25.542629 139917319264064 run_docker.py:222] outs = primitive.process(top_trace, fun, tracers, params)
I1127 19:30:25.542717 139917319264064 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 1635, in process
I1127 19:30:25.542805 139917319264064 run_docker.py:222] return trace.process_call(self, fun, tracers, params)
I1127 19:30:25.542893 139917319264064 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 627, in process_call
I1127 19:30:25.542980 139917319264064 run_docker.py:222] return primitive.impl(f, *tracers, **params)
I1127 19:30:25.543067 139917319264064 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 690, in _xla_call_impl
I1127 19:30:25.543155 139917319264064 run_docker.py:222] out = compiled_fun(*args)
I1127 19:30:25.543245 139917319264064 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 1100, in _execute_compiled
I1127 19:30:25.543345 139917319264064 run_docker.py:222] out_bufs = compiled.execute(input_bufs)
I1127 19:30:25.543439 139917319264064 run_docker.py:222] jax._src.traceback_util.UnfilteredStackTrace: RuntimeError: Internal: Failed to load in-memory CUBIN: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
I1127 19:30:25.543529 139917319264064 run_docker.py:222]
I1127 19:30:25.543617 139917319264064 run_docker.py:222] The stack trace below excludes JAX-internal frames.
I1127 19:30:25.543704 139917319264064 run_docker.py:222] The preceding is the original exception that occurred, unmodified.
I1127 19:30:25.543809 139917319264064 run_docker.py:222]
I1127 19:30:25.543896 139917319264064 run_docker.py:222] --------------------
I1127 19:30:25.544003 139917319264064 run_docker.py:222]
I1127 19:30:25.544089 139917319264064 run_docker.py:222] The above exception was the direct cause of the following exception:
I1127 19:30:25.544178 139917319264064 run_docker.py:222]
I1127 19:30:25.544282 139917319264064 run_docker.py:222] Traceback (most recent call last):
I1127 19:30:25.544378 139917319264064 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 427, in <module>
I1127 19:30:25.544466 139917319264064 run_docker.py:222] app.run(main)
I1127 19:30:25.544565 139917319264064 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
I1127 19:30:25.544672 139917319264064 run_docker.py:222] _run_main(main, args)
I1127 19:30:25.544762 139917319264064 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I1127 19:30:25.544850 139917319264064 run_docker.py:222] sys.exit(main(argv))
I1127 19:30:25.544938 139917319264064 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 412, in main
I1127 19:30:25.545041 139917319264064 run_docker.py:222] is_prokaryote=is_prokaryote)
I1127 19:30:25.545126 139917319264064 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 237, in predict_structure
I1127 19:30:25.545235 139917319264064 run_docker.py:222] relaxed_pdb_str, _, _ = amber_relaxer.process(prot=unrelaxed_protein)
I1127 19:30:25.545325 139917319264064 run_docker.py:222] File "/app/alphafold/alphafold/relax/relax.py", line 62, in process
I1127 19:30:25.545425 139917319264064 run_docker.py:222] max_outer_iterations=self._max_outer_iterations)
I1127 19:30:25.545528 139917319264064 run_docker.py:222] File "/app/alphafold/alphafold/relax/amber_minimize.py", line 482, in run_pipeline
I1127 19:30:25.545613 139917319264064 run_docker.py:222] ret.update(get_violation_metrics(prot))
I1127 19:30:25.545698 139917319264064 run_docker.py:222] File "/app/alphafold/alphafold/relax/amber_minimize.py", line 356, in get_violation_metrics
I1127 19:30:25.545783 139917319264064 run_docker.py:222] structural_violations, struct_metrics = find_violations(prot)
I1127 19:30:25.545868 139917319264064 run_docker.py:222] File "/app/alphafold/alphafold/relax/amber_minimize.py", line 343, in find_violations
I1127 19:30:25.545953 139917319264064 run_docker.py:222] "clash_overlap_tolerance": 1.5,  # Taken from model config.
I1127 19:30:25.546056 139917319264064 run_docker.py:222] File "/app/alphafold/alphafold/model/folding.py", line 748, in find_structural_violations
I1127 19:30:25.546146 139917319264064 run_docker.py:222] tolerance_factor_hard=config.violation_tolerance_factor)
I1127 19:30:25.546256 139917319264064 run_docker.py:222] File "/app/alphafold/alphafold/model/all_atom.py", line 664, in between_residue_bond_loss
I1127 19:30:25.546377 139917319264064 run_docker.py:222] 1e-6 + jnp.sum(squared_difference(this_c_pos, next_n_pos), axis=-1))
I1127 19:30:25.546485 139917319264064 run_docker.py:222] File "/app/alphafold/alphafold/model/all_atom.py", line 47, in squared_difference
I1127 19:30:25.546573 139917319264064 run_docker.py:222] return jnp.square(x - y)
I1127 19:30:25.546659 139917319264064 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 1100, in _execute_compiled
I1127 19:30:25.546745 139917319264064 run_docker.py:222] out_bufs = compiled.execute(input_bufs)
I1127 19:30:25.546830 139917319264064 run_docker.py:222] RuntimeError: Internal: Failed to load in-memory CUBIN: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
I1127 19:30:27.907152 139917319264064 run_docker.py:222] 2021-11-28 00:30:27.906009: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:1039] could not synchronize on CUDA context: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure :: *** Begin stack trace ***
I1127 19:30:27.907420 139917319264064 run_docker.py:222]
I1127 19:30:27.907521 139917319264064 run_docker.py:222]
I1127 19:30:27.907611 139917319264064 run_docker.py:222]
I1127 19:30:27.907698 139917319264064 run_docker.py:222]
I1127 19:30:27.907818 139917319264064 run_docker.py:222]
I1127 19:30:27.907940 139917319264064 run_docker.py:222]
I1127 19:30:27.908030 139917319264064 run_docker.py:222]
I1127 19:30:27.908126 139917319264064 run_docker.py:222]
I1127 19:30:27.908209 139917319264064 run_docker.py:222]
I1127 19:30:27.908291 139917319264064 run_docker.py:222]
I1127 19:30:27.908371 139917319264064 run_docker.py:222]
I1127 19:30:27.908452 139917319264064 run_docker.py:222]
I1127 19:30:27.908533 139917319264064 run_docker.py:222]
I1127 19:30:27.908648 139917319264064 run_docker.py:222]
I1127 19:30:27.908729 139917319264064 run_docker.py:222]
I1127 19:30:27.908809 139917319264064 run_docker.py:222]
I1127 19:30:27.908889 139917319264064 run_docker.py:222]
I1127 19:30:27.908969 139917319264064 run_docker.py:222]
I1127 19:30:27.909051 139917319264064 run_docker.py:222]
I1127 19:30:27.909131 139917319264064 run_docker.py:222]
I1127 19:30:27.909212 139917319264064 run_docker.py:222]
I1127 19:30:27.909293 139917319264064 run_docker.py:222]
I1127 19:30:27.909373 139917319264064 run_docker.py:222]
I1127 19:30:27.909454 139917319264064 run_docker.py:222] _PyModule_ClearDict
I1127 19:30:27.909535 139917319264064 run_docker.py:222] PyImport_Cleanup
I1127 19:30:27.909617 139917319264064 run_docker.py:222] Py_FinalizeEx
I1127 19:30:27.909764 139917319264064 run_docker.py:222]
I1127 19:30:27.909862 139917319264064 run_docker.py:222] _Py_UnixMain
I1127 19:30:27.909946 139917319264064 run_docker.py:222] __libc_start_main
I1127 19:30:27.910058 139917319264064 run_docker.py:222]
I1127 19:30:27.910137 139917319264064 run_docker.py:222] *** End stack trace ***
I1127 19:30:27.910241 139917319264064 run_docker.py:222]
I1127 19:30:27.910323 139917319264064 run_docker.py:222] 2021-11-28 00:30:27.906232: F external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_executable.cc:99] Check failed: pair.first->SynchronizeAllActivity()
I1127 19:30:27.910407 139917319264064 run_docker.py:222] Fatal Python error: Aborted
I1127 19:30:27.910503 139917319264064 run_docker.py:222]
I1127 19:30:27.910581 139917319264064 run_docker.py:222] Current thread 0x00007f0974a910c0 (most recent call first):
I1127 19:30:44.025791 139917319264064 run_docker.py:222] /app/run_alphafold.sh: line 3:     8 Aborted                 (core dumped) python /app/alphafold/run_alphafold.py "$@"
```

**Comment by truatpasteurdotfr** [comment]
If I recall correctly, the K80 is a dual gpu on a single PCIe card, and is seen as 2x 12 GB memory gpu. I am not sure that you can combine the multiple gpu memory from those gpus on the old kepler generation...

**Comment by ShannonTown** [comment]
> If I recall correctly, the K80 is a dual gpu on a single PCIe card, and is seen as 2x 12 GB memory gpu. I am not sure that you can combine the multiple gpu memory from those gpus on the old kepler generation...

Yes, K80 is dual GPUs on a single card and we have two cards. I found this blog (https://developer.nvidia.com/blog/unified-memory-cuda-beginners/) and quote below:

"The Pascal GPU architecture is the first with hardware support for virtual memory page faulting and migration, via its Page Migration Engine. Older GPUs based on the Kepler and Maxwell architectures also support a more limited form of Unified Memory." 

The rest of the article is really hard for me to understand what limited form of unified memory the Kepler architecture supports. Does it still mean that it's not possible to run alphafold with unified memory on K80?

**Comment by Augustin-Zidek** [comment]
This problem was addressed in https://github.com/deepmind/alphafold/releases/tag/v2.1.2, feel free to reopen if this is still an issue.
