### ISSUE TITLE
ImageNotFound error

### ISSUE THREAD

**Issue by Sunyp-IM** [deepmind/alphafold#302]
Dear all,

I setup alphafold according to the README file. However, when I run the example:

```
python3 docker/run_docker.py \
  --fasta_paths=T1050.fasta \
  --max_template_date=2020-05-14 \
  --data_dir=$DOWNLOAD_DIR
```

I get the follow error:

```
I1210 19:48:28.392767 139827030099776 run_docker.py:119] Mounting /run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/alphafold -> /mnt/fasta_path_0
I1210 19:48:28.392866 139827030099776 run_docker.py:119] Mounting /run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/datebases/uniref90 -> /mnt/uniref90_database_path
I1210 19:48:28.392926 139827030099776 run_docker.py:119] Mounting /run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/datebases/mgnify -> /mnt/mgnify_database_path
I1210 19:48:28.392979 139827030099776 run_docker.py:119] Mounting /run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/datebases/pdb70 -> /mnt/pdb70_database_path
I1210 19:48:28.393077 139827030099776 run_docker.py:119] Mounting /run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2 -> /mnt/data_dir
I1210 19:48:28.393131 139827030099776 run_docker.py:119] Mounting /run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/datebases/pdb_mmcif -> /mnt/template_mmcif_dir
I1210 19:48:28.393180 139827030099776 run_docker.py:119] Mounting /run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/datebases/pdb_mmcif -> /mnt/obsolete_pdbs_path
I1210 19:48:28.393228 139827030099776 run_docker.py:119] Mounting /run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/datebases/uniclust30/uniclust30_2018_08 -> /mnt/uniclust30_database_path
I1210 19:48:28.393281 139827030099776 run_docker.py:119] Mounting /run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/datebases/bfd -> /mnt/bfd_database_path
Traceback (most recent call last):
  File "/run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/alphafold/docker/docker/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/alphafold/docker/docker/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/alphafold/docker/docker/lib/python3.8/site-packages/docker/models/containers.py", line 811, in run
    container = self.create(image=image, command=command,
  File "/run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/alphafold/docker/docker/lib/python3.8/site-packages/docker/models/containers.py", line 870, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/alphafold/docker/docker/lib/python3.8/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/alphafold/docker/docker/lib/python3.8/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/alphafold/docker/docker/lib/python3.8/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/alphafold/docker/docker/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/alphafold/docker/docker/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.41/containers/create: Not Found ("No such image: alphafold:latest")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/alphafold/docker/docker/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/alphafold/docker/docker/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/images/create?tag=latest&fromImage=alphafold

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/run_docker.py", line 201, in <module>
    app.run(main)
  File "/run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/alphafold/docker/docker/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/alphafold/docker/docker/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "docker/run_docker.py", line 173, in main
    container = client.containers.run(
  File "/run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/alphafold/docker/docker/lib/python3.8/site-packages/docker/models/containers.py", line 814, in run
    self.client.images.pull(image, platform=platform)
  File "/run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/alphafold/docker/docker/lib/python3.8/site-packages/docker/models/images.py", line 446, in pull
    pull_log = self.client.api.pull(
  File "/run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/alphafold/docker/docker/lib/python3.8/site-packages/docker/api/image.py", line 430, in pull
    self._raise_for_status(response)
  File "/run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/alphafold/docker/docker/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/alphafold/docker/docker/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=latest&fromImage=alphafold: Not Found ("pull access denied for alphafold, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")
```

Do you know how to solve this problem.

Any hint or help will be deeply appreciated!

Best regards

**Comment by Sunyp-IM** [comment]
Hello @Augustin Zidek,

You are right. After I ran the dock build command, the error disappear.
Thank you very much :)
