### ISSUE TITLE
ValueError: jaxlib is version 0.1.69, but this version of jax requires version 0.1.74.

### ISSUE THREAD

**Issue by Sunyp-IM** [deepmind/alphafold#304]
Hello everyone,

I have setup alphafold but when I tried to run the run_docker.py I got the following error code:
```
I1212 13:37:27.910260 139790687459136 run_docker.py:87] Mounting /run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/test -> /mnt/fasta_path_0
I1212 13:37:27.910366 139790687459136 run_docker.py:87] Mounting /run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/datebases/uniref90 -> /mnt/uniref90_database_path
I1212 13:37:27.910423 139790687459136 run_docker.py:87] Mounting /run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/datebases/mgnify -> /mnt/mgnify_database_path
I1212 13:37:27.910473 139790687459136 run_docker.py:87] Mounting /run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2 -> /mnt/data_dir
I1212 13:37:27.910523 139790687459136 run_docker.py:87] Mounting /run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/datebases/pdb_mmcif -> /mnt/template_mmcif_dir
I1212 13:37:27.910569 139790687459136 run_docker.py:87] Mounting /run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/datebases/pdb_mmcif -> /mnt/obsolete_pdbs_path
I1212 13:37:27.910614 139790687459136 run_docker.py:87] Mounting /run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/datebases/pdb70 -> /mnt/pdb70_database_path
I1212 13:37:27.910659 139790687459136 run_docker.py:87] Mounting /run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/datebases/uniclust30/uniclust30_2018_08 -> /mnt/uniclust30_database_path
I1212 13:37:27.910708 139790687459136 run_docker.py:87] Mounting /run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/datebases/bfd -> /mnt/bfd_database_path
I1212 13:37:30.576652 139790687459136 run_docker.py:222] Traceback (most recent call last):
I1212 13:37:30.576779 139790687459136 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 37, in <module>
I1212 13:37:30.576859 139790687459136 run_docker.py:222] from alphafold.model import model
I1212 13:37:30.576920 139790687459136 run_docker.py:222] File "/app/alphafold/alphafold/model/model.py", line 21, in <module>
I1212 13:37:30.576978 139790687459136 run_docker.py:222] from alphafold.model import modules
I1212 13:37:30.577034 139790687459136 run_docker.py:222] File "/app/alphafold/alphafold/model/modules.py", line 21, in <module>
I1212 13:37:30.577090 139790687459136 run_docker.py:222] from alphafold.model import all_atom
I1212 13:37:30.577145 139790687459136 run_docker.py:222] File "/app/alphafold/alphafold/model/all_atom.py", line 39, in <module>
I1212 13:37:30.577200 139790687459136 run_docker.py:222] from alphafold.model import r3
I1212 13:37:30.577261 139790687459136 run_docker.py:222] File "/app/alphafold/alphafold/model/r3.py", line 36, in <module>
I1212 13:37:30.577314 139790687459136 run_docker.py:222] from alphafold.model import quat_affine
I1212 13:37:30.577365 139790687459136 run_docker.py:222] File "/app/alphafold/alphafold/model/quat_affine.py", line 38, in <module>
I1212 13:37:30.577415 139790687459136 run_docker.py:222] import jax
I1212 13:37:30.577464 139790687459136 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/__init__.py", line 37, in <module>
I1212 13:37:30.577513 139790687459136 run_docker.py:222] from jax import config as _config_module
I1212 13:37:30.577561 139790687459136 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/config.py", line 18, in <module>
I1212 13:37:30.577610 139790687459136 run_docker.py:222] from jax._src.config import config
I1212 13:37:30.577658 139790687459136 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/_src/config.py", line 27, in <module>
I1212 13:37:30.577706 139790687459136 run_docker.py:222] from jax._src import lib
I1212 13:37:30.577754 139790687459136 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/_src/lib/__init__.py", line 69, in <module>
I1212 13:37:30.577803 139790687459136 run_docker.py:222] _check_jaxlib_version()
I1212 13:37:30.577852 139790687459136 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/_src/lib/__init__.py", line 67, in _check_jaxlib_version
I1212 13:37:30.577900 139790687459136 run_docker.py:222] raise ValueError(msg)
I1212 13:37:30.577949 139790687459136 run_docker.py:222] ValueError: jaxlib is version 0.1.69, but this version of jax requires version 0.1.74.
```
I have install the last version of jaxlib with pip, and the "pip show" command confirms this:
```
$ pip show jaxlib
Name: jaxlib
Version: 0.1.75
Summary: XLA library for JAX
Home-page: https://github.com/google/jax
Author: JAX team
Author-email: jax-dev@google.com
License: Apache-2.0
Location: /run/media/sunyp/Seagate_Basic/F409Desktop/software/alphaFold2/alphafold-main/virpython/lib/python3.8/site-packages
Requires: absl-py, flatbuffers, numpy, scipy
Required-by: 
```
But I still have the jaxlib issue.

Does anyone can help with this. Any help will be deeply apprecaited!

Best regards

**Comment by Sunyp-IM** [comment]
I replaced the "==" in Line 68 with ">=", and the issue solved.

**Comment by wdlingit** [comment]
> I replaced the "==" in Line 68 with ">=", and the issue solved.

I got the same error message. Do you mind telling me line 68 of which file? Thank you in advance.

**Comment by wdlingit** [comment]
> > I replaced the "==" in Line 68 with ">=", and the issue solved.
> 
> I got the same error message. Do you mind telling me line 68 of which file? Thank you in advance.

Got the answer from https://pythonrepo.com/repo/deepmind-alphafold

**Comment by Sunyp-IM** [comment]
Line 68 is "&& pip3 install --upgrade jax jaxlib==0.1.69+cuda${CUDA/./} -f \"
