### ISSUE TITLE
cuSolver internal error

### ISSUE THREAD

**Issue by Sunyp-IM** [deepmind/alphafold#306]
Hello everyone,

When I try to run the run_docker command, I get the following error message:

```
I1213 13:01:26.560190 140646328219456 run_docker.py:222] I1213 05:01:26.559695 139938476273856 model.py:166] Running predict with shape(feat) = {'aatype': (4, 117), 'residue_index': (4, 117), 'seq_length': (4,), 'template_aatype': (4, 4, 117), 'template_all_atom_masks': (4, 4, 117, 37), 'template_all_atom_positions': (4, 4, 117, 37, 3), 'template_sum_probs': (4, 4, 1), 'is_distillation': (4,), 'seq_mask': (4, 117), 'msa_mask': (4, 508, 117), 'msa_row_mask': (4, 508), 'random_crop_to_size_seed': (4, 2), 'template_mask': (4, 4), 'template_pseudo_beta': (4, 4, 117, 3), 'template_pseudo_beta_mask': (4, 4, 117), 'atom14_atom_exists': (4, 117, 14), 'residx_atom14_to_atom37': (4, 117, 14), 'residx_atom37_to_atom14': (4, 117, 37), 'atom37_atom_exists': (4, 117, 37), 'extra_msa': (4, 5120, 117), 'extra_msa_mask': (4, 5120, 117), 'extra_msa_row_mask': (4, 5120), 'bert_mask': (4, 508, 117), 'true_msa': (4, 508, 117), 'extra_has_deletion': (4, 5120, 117), 'extra_deletion_value': (4, 5120, 117), 'msa_feat': (4, 508, 117, 49), 'target_feat': (4, 117, 22)}
I1213 13:01:28.021078 140646328219456 run_docker.py:222] 2021-12-13 05:01:28.020536: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:111] *** WARNING *** You are using ptxas 11.0.221, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.
I1213 13:01:28.021288 140646328219456 run_docker.py:222] 
I1213 13:01:28.021411 140646328219456 run_docker.py:222] You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
I1213 13:01:28.282180 140646328219456 run_docker.py:222] 2021-12-13 05:01:28.281777: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:111] *** WARNING *** You are using ptxas 11.0.221, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.
I1213 13:01:28.282321 140646328219456 run_docker.py:222] 
I1213 13:01:28.282390 140646328219456 run_docker.py:222] You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
I1213 13:01:28.353455 140646328219456 run_docker.py:222] 2021-12-13 05:01:28.353062: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:111] *** WARNING *** You are using ptxas 11.0.221, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.
I1213 13:01:28.353577 140646328219456 run_docker.py:222] 
I1213 13:01:28.353635 140646328219456 run_docker.py:222] You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
I1213 13:01:28.434881 140646328219456 run_docker.py:222] 2021-12-13 05:01:28.433757: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:111] *** WARNING *** You are using ptxas 11.0.221, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.
I1213 13:01:28.435456 140646328219456 run_docker.py:222] 
I1213 13:01:28.435850 140646328219456 run_docker.py:222] You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
I1213 13:02:04.720309 140646328219456 run_docker.py:222] 2021-12-13 05:02:04.719275: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
I1213 13:02:05.956853 140646328219456 run_docker.py:222] Traceback (most recent call last):
I1213 13:02:05.957460 140646328219456 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 427, in <module>
I1213 13:02:05.957916 140646328219456 run_docker.py:222] app.run(main)
I1213 13:02:05.958564 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
I1213 13:02:05.958970 140646328219456 run_docker.py:222] _run_main(main, args)
I1213 13:02:05.959267 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I1213 13:02:05.959523 140646328219456 run_docker.py:222] sys.exit(main(argv))
I1213 13:02:05.959763 140646328219456 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 412, in main
I1213 13:02:05.960000 140646328219456 run_docker.py:222] is_prokaryote=is_prokaryote)
I1213 13:02:05.960252 140646328219456 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 194, in predict_structure
I1213 13:02:05.960494 140646328219456 run_docker.py:222] random_seed=model_random_seed)
I1213 13:02:05.960728 140646328219456 run_docker.py:222] File "/app/alphafold/alphafold/model/model.py", line 167, in predict
I1213 13:02:05.960962 140646328219456 run_docker.py:222] result = self.apply(self.params, jax.random.PRNGKey(random_seed), feat)
I1213 13:02:05.961197 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/transform.py", line 125, in apply_fn
I1213 13:02:05.961449 140646328219456 run_docker.py:222] out, state = f.apply(params, {}, *args, **kwargs)
I1213 13:02:05.961683 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/transform.py", line 313, in apply_fn
I1213 13:02:05.961916 140646328219456 run_docker.py:222] out = f(*args, **kwargs)
I1213 13:02:05.962150 140646328219456 run_docker.py:222] File "/app/alphafold/alphafold/model/model.py", line 87, in _forward_fn
I1213 13:02:05.962399 140646328219456 run_docker.py:222] ensemble_representations=True)
I1213 13:02:05.962634 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/module.py", line 428, in wrapped
I1213 13:02:05.962866 140646328219456 run_docker.py:222] out = f(*args, **kwargs)
I1213 13:02:05.963097 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/module.py", line 279, in run_interceptors
I1213 13:02:05.963432 140646328219456 run_docker.py:222] return bound_method(*args, **kwargs)
I1213 13:02:05.963726 140646328219456 run_docker.py:222] File "/app/alphafold/alphafold/model/modules.py", line 379, in __call__
I1213 13:02:05.963972 140646328219456 run_docker.py:222] (0, prev))
I1213 13:02:05.964263 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/stateful.py", line 610, in while_loop
I1213 13:02:05.964532 140646328219456 run_docker.py:222] val, state = jax.lax.while_loop(pure_cond_fun, pure_body_fun, init_val)
I1213 13:02:05.964793 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/stateful.py", line 605, in pure_body_fun
I1213 13:02:05.965052 140646328219456 run_docker.py:222] val = body_fun(val)
I1213 13:02:05.965333 140646328219456 run_docker.py:222] File "/app/alphafold/alphafold/model/modules.py", line 370, in <lambda>
I1213 13:02:05.965595 140646328219456 run_docker.py:222] compute_loss=False)))
I1213 13:02:05.965852 140646328219456 run_docker.py:222] File "/app/alphafold/alphafold/model/modules.py", line 342, in do_call
I1213 13:02:05.966113 140646328219456 run_docker.py:222] ensemble_representations=ensemble_representations)
I1213 13:02:05.966384 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/module.py", line 428, in wrapped
I1213 13:02:05.966646 140646328219456 run_docker.py:222] out = f(*args, **kwargs)
I1213 13:02:05.966902 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/module.py", line 279, in run_interceptors
I1213 13:02:05.967166 140646328219456 run_docker.py:222] return bound_method(*args, **kwargs)
I1213 13:02:05.967444 140646328219456 run_docker.py:222] File "/app/alphafold/alphafold/model/modules.py", line 161, in __call__
I1213 13:02:05.967703 140646328219456 run_docker.py:222] representations = evoformer_module(batch0, is_training)
I1213 13:02:05.967957 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/module.py", line 428, in wrapped
I1213 13:02:05.968213 140646328219456 run_docker.py:222] out = f(*args, **kwargs)
I1213 13:02:05.968482 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/module.py", line 279, in run_interceptors
I1213 13:02:05.968739 140646328219456 run_docker.py:222] return bound_method(*args, **kwargs)
I1213 13:02:05.968996 140646328219456 run_docker.py:222] File "/app/alphafold/alphafold/model/modules.py", line 1782, in __call__
I1213 13:02:05.969269 140646328219456 run_docker.py:222] is_training=is_training)
I1213 13:02:05.969527 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/module.py", line 428, in wrapped
I1213 13:02:05.969791 140646328219456 run_docker.py:222] out = f(*args, **kwargs)
I1213 13:02:05.970051 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/module.py", line 279, in run_interceptors
I1213 13:02:05.970328 140646328219456 run_docker.py:222] return bound_method(*args, **kwargs)
I1213 13:02:05.970586 140646328219456 run_docker.py:222] File "/app/alphafold/alphafold/model/modules.py", line 2074, in __call__
I1213 13:02:05.970842 140646328219456 run_docker.py:222] template_batch)
I1213 13:02:05.971097 140646328219456 run_docker.py:222] File "/app/alphafold/alphafold/model/mapping.py", line 182, in mapped_fn
I1213 13:02:05.971371 140646328219456 run_docker.py:222] outputs, _ = hk.scan(scan_iteration, outputs, slice_starts)
I1213 13:02:05.971635 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/stateful.py", line 505, in scan
I1213 13:02:05.971897 140646328219456 run_docker.py:222] stateful_fun, init, xs, length, reverse, unroll=unroll)
I1213 13:02:05.972157 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/stateful.py", line 487, in stateful_fun
I1213 13:02:05.972435 140646328219456 run_docker.py:222] carry, out = f(carry, x)
I1213 13:02:05.972694 140646328219456 run_docker.py:222] File "/app/alphafold/alphafold/model/mapping.py", line 171, in scan_iteration
I1213 13:02:05.972953 140646328219456 run_docker.py:222] new_outputs = compute_shard(outputs, i, shard_size)
I1213 13:02:05.973211 140646328219456 run_docker.py:222] File "/app/alphafold/alphafold/model/mapping.py", line 165, in compute_shard
I1213 13:02:05.973484 140646328219456 run_docker.py:222] slice_out = apply_fun_to_slice(slice_start, slice_size)
I1213 13:02:05.973741 140646328219456 run_docker.py:222] File "/app/alphafold/alphafold/model/mapping.py", line 138, in apply_fun_to_slice
I1213 13:02:05.973995 140646328219456 run_docker.py:222] return fun(*input_slice)
I1213 13:02:05.974262 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/stateful.py", line 567, in mapped_fun
I1213 13:02:05.974518 140646328219456 run_docker.py:222] out, state = mapped_pure_fun(args, state)
I1213 13:02:05.974771 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/stateful.py", line 558, in pure_fun
I1213 13:02:05.975021 140646328219456 run_docker.py:222] out = fun(*args)
I1213 13:02:05.975285 140646328219456 run_docker.py:222] File "/app/alphafold/alphafold/model/modules.py", line 2071, in map_fn
I1213 13:02:05.975542 140646328219456 run_docker.py:222] return template_embedder(query_embedding, batch, mask_2d, is_training)
I1213 13:02:05.975797 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/module.py", line 428, in wrapped
I1213 13:02:05.976050 140646328219456 run_docker.py:222] out = f(*args, **kwargs)
I1213 13:02:05.976315 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/module.py", line 279, in run_interceptors
I1213 13:02:05.976570 140646328219456 run_docker.py:222] return bound_method(*args, **kwargs)
I1213 13:02:05.976824 140646328219456 run_docker.py:222] File "/app/alphafold/alphafold/model/modules.py", line 1977, in __call__
I1213 13:02:05.977075 140646328219456 run_docker.py:222] quaternion=quat_affine.rot_to_quat(rot, unstack_inputs=True),
I1213 13:02:05.977342 140646328219456 run_docker.py:222] File "/app/alphafold/alphafold/model/quat_affine.py", line 113, in rot_to_quat
I1213 13:02:05.977598 140646328219456 run_docker.py:222] _, qs = jnp.linalg.eigh(k)
I1213 13:02:05.977853 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/_src/numpy/linalg.py", line 330, in eigh
I1213 13:02:05.978122 140646328219456 run_docker.py:222] v, w = lax_linalg.eigh(a, lower=lower, symmetrize_input=symmetrize_input)
I1213 13:02:05.978400 140646328219456 run_docker.py:222] jax._src.source_info_util.JaxStackTraceBeforeTransformation: RuntimeError: jaxlib/cusolver_kernels.cc:44: operation cusolverDnCreate(&handle) failed: cuSolver internal error
I1213 13:02:05.978669 140646328219456 run_docker.py:222] 
I1213 13:02:05.978937 140646328219456 run_docker.py:222] The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.
I1213 13:02:05.979201 140646328219456 run_docker.py:222] 
I1213 13:02:05.979474 140646328219456 run_docker.py:222] --------------------
I1213 13:02:05.979733 140646328219456 run_docker.py:222] 
I1213 13:02:05.979998 140646328219456 run_docker.py:222] The above exception was the direct cause of the following exception:
I1213 13:02:05.980272 140646328219456 run_docker.py:222] 
I1213 13:02:05.980538 140646328219456 run_docker.py:222] Traceback (most recent call last):
I1213 13:02:05.980802 140646328219456 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 427, in <module>
I1213 13:02:05.981065 140646328219456 run_docker.py:222] app.run(main)
I1213 13:02:05.981344 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
I1213 13:02:05.981611 140646328219456 run_docker.py:222] _run_main(main, args)
I1213 13:02:05.981875 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I1213 13:02:05.982146 140646328219456 run_docker.py:222] sys.exit(main(argv))
I1213 13:02:05.982426 140646328219456 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 412, in main
I1213 13:02:05.982691 140646328219456 run_docker.py:222] is_prokaryote=is_prokaryote)
I1213 13:02:05.982953 140646328219456 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 194, in predict_structure
I1213 13:02:05.983218 140646328219456 run_docker.py:222] random_seed=model_random_seed)
I1213 13:02:05.983497 140646328219456 run_docker.py:222] File "/app/alphafold/alphafold/model/model.py", line 167, in predict
I1213 13:02:05.983760 140646328219456 run_docker.py:222] result = self.apply(self.params, jax.random.PRNGKey(random_seed), feat)
I1213 13:02:05.984022 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
I1213 13:02:05.984298 140646328219456 run_docker.py:222] return fun(*args, **kwargs)
I1213 13:02:05.984562 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/_src/api.py", line 427, in cache_miss
I1213 13:02:05.984828 140646328219456 run_docker.py:222] donated_invars=donated_invars, inline=inline)
I1213 13:02:05.985092 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 1661, in bind
I1213 13:02:05.985373 140646328219456 run_docker.py:222] return call_bind(self, fun, *args, **params)
I1213 13:02:05.985646 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 1652, in call_bind
I1213 13:02:05.985984 140646328219456 run_docker.py:222] outs = primitive.process(top_trace, fun, tracers, params)
I1213 13:02:05.986483 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 1664, in process
I1213 13:02:05.986879 140646328219456 run_docker.py:222] return trace.process_call(self, fun, tracers, params)
I1213 13:02:05.987170 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 633, in process_call
I1213 13:02:05.987384 140646328219456 run_docker.py:222] return primitive.impl(f, *tracers, **params)
I1213 13:02:05.987572 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/_src/dispatch.py", line 129, in _xla_call_impl
I1213 13:02:05.987760 140646328219456 run_docker.py:222] *unsafe_map(arg_spec, args))
I1213 13:02:05.987944 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/linear_util.py", line 263, in memoized_fun
I1213 13:02:05.988136 140646328219456 run_docker.py:222] ans = call(fun, *args)
I1213 13:02:05.988340 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/_src/dispatch.py", line 156, in _xla_callable_uncached
I1213 13:02:05.988531 140646328219456 run_docker.py:222] *arg_specs).compile().unsafe_call
I1213 13:02:05.988722 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/_src/profiler.py", line 206, in wrapper
I1213 13:02:05.988910 140646328219456 run_docker.py:222] return func(*args, **kwargs)
I1213 13:02:05.989097 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/_src/dispatch.py", line 232, in lower_xla_callable
I1213 13:02:05.989290 140646328219456 run_docker.py:222] arg_partitions=None, out_partitions=None)
I1213 13:02:05.989473 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/_src/profiler.py", line 206, in wrapper
I1213 13:02:05.989655 140646328219456 run_docker.py:222] return func(*args, **kwargs)
I1213 13:02:05.989839 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 758, in lower_jaxpr_to_xla_module
I1213 13:02:05.990023 140646328219456 run_docker.py:222] out_nodes = jaxpr_subcomp(ctx, jaxpr.jaxpr, xla_consts, *xla_args)
I1213 13:02:05.990206 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 586, in jaxpr_subcomp
I1213 13:02:05.990399 140646328219456 run_docker.py:222] *in_nodes, **eqn.params)
I1213 13:02:05.990582 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/_src/lax/control_flow.py", line 369, in _while_loop_translation_rule
I1213 13:02:05.990765 140646328219456 run_docker.py:222] *(y + z))
I1213 13:02:05.990945 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 586, in jaxpr_subcomp
I1213 13:02:06.020195 140646328219456 run_docker.py:222] *in_nodes, **eqn.params)
I1213 13:02:06.020461 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 1000, in f_new
I1213 13:02:06.020627 140646328219456 run_docker.py:222] *xla_args)
I1213 13:02:06.020780 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 586, in jaxpr_subcomp
I1213 13:02:06.020932 140646328219456 run_docker.py:222] *in_nodes, **eqn.params)
I1213 13:02:06.021146 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/_src/lax/control_flow.py", line 369, in _while_loop_translation_rule
I1213 13:02:06.021311 140646328219456 run_docker.py:222] *(y + z))
I1213 13:02:06.021459 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 586, in jaxpr_subcomp
I1213 13:02:06.021604 140646328219456 run_docker.py:222] *in_nodes, **eqn.params)
I1213 13:02:06.021748 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 834, in _xla_call_translation_rule
I1213 13:02:06.021892 140646328219456 run_docker.py:222] out_nodes = jaxpr_subcomp(sub_ctx, call_jaxpr, (), *args)
I1213 13:02:06.022035 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 586, in jaxpr_subcomp
I1213 13:02:06.022181 140646328219456 run_docker.py:222] *in_nodes, **eqn.params)
I1213 13:02:06.022301 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/_src/lax/linalg.py", line 513, in _eigh_cpu_gpu_translation_rule
I1213 13:02:06.022418 140646328219456 run_docker.py:222] v, w, info = syevd_impl(c, operand, lower=lower)
I1213 13:02:06.022529 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jaxlib/cusolver.py", line 272, in syevd
I1213 13:02:06.022643 140646328219456 run_docker.py:222] np.dtype(dtype), lower, batch, n)
I1213 13:02:06.022757 140646328219456 run_docker.py:222] jax._src.traceback_util.UnfilteredStackTrace: RuntimeError: jaxlib/cusolver_kernels.cc:44: operation cusolverDnCreate(&handle) failed: cuSolver internal error
I1213 13:02:06.022871 140646328219456 run_docker.py:222] 
I1213 13:02:06.022983 140646328219456 run_docker.py:222] The stack trace below excludes JAX-internal frames.
I1213 13:02:06.023095 140646328219456 run_docker.py:222] The preceding is the original exception that occurred, unmodified.
I1213 13:02:06.023208 140646328219456 run_docker.py:222] 
I1213 13:02:06.023325 140646328219456 run_docker.py:222] --------------------
I1213 13:02:06.023436 140646328219456 run_docker.py:222] 
I1213 13:02:06.023549 140646328219456 run_docker.py:222] The above exception was the direct cause of the following exception:
I1213 13:02:06.023662 140646328219456 run_docker.py:222] 
I1213 13:02:06.023775 140646328219456 run_docker.py:222] Traceback (most recent call last):
I1213 13:02:06.023889 140646328219456 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 427, in <module>
I1213 13:02:06.024003 140646328219456 run_docker.py:222] app.run(main)
I1213 13:02:06.024116 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
I1213 13:02:06.024230 140646328219456 run_docker.py:222] _run_main(main, args)
I1213 13:02:06.024347 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I1213 13:02:06.024458 140646328219456 run_docker.py:222] sys.exit(main(argv))
I1213 13:02:06.024569 140646328219456 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 412, in main
I1213 13:02:06.024679 140646328219456 run_docker.py:222] is_prokaryote=is_prokaryote)
I1213 13:02:06.024789 140646328219456 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 194, in predict_structure
I1213 13:02:06.024898 140646328219456 run_docker.py:222] random_seed=model_random_seed)
I1213 13:02:06.025007 140646328219456 run_docker.py:222] File "/app/alphafold/alphafold/model/model.py", line 167, in predict
I1213 13:02:06.025116 140646328219456 run_docker.py:222] result = self.apply(self.params, jax.random.PRNGKey(random_seed), feat)
I1213 13:02:06.025225 140646328219456 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jaxlib/cusolver.py", line 272, in syevd
I1213 13:02:06.025343 140646328219456 run_docker.py:222] np.dtype(dtype), lower, batch, n)
I1213 13:02:06.025453 140646328219456 run_docker.py:222] RuntimeError: jaxlib/cusolver_kernels.cc:44: operation cusolverDnCreate(&handle) failed: cuSolver internal error
```

Does anyone know what causes this issue and can help with this? Any help will be deeply apprecaited!

Best regards

**Comment by Sunyp-IM** [comment]
I replaced Line 15 "ARG CUDA=10.1" with "ARG CUDA=11.1" in the Dockfile and the issue solved.
