### ISSUE TITLE
Issues with cuda and jaxlib

### ISSUE THREAD

**Issue by rdean064** [deepmind/alphafold#329]
I keep getting the following error when running alphafold. I have tried updating the Dockerfile according to Issue #306 but it does not seem to be working. Also I have updated to cuda11.1 but it continues to give me the error.

```
I0110 16:35:08.873017 139862869276480 run_docker.py:222] 2022-01-10 21:35:08.872085: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:111] *** WARNING *** You are using ptxas 11.0.221, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.
I0110 16:35:08.873405 139862869276480 run_docker.py:222] 
I0110 16:35:08.873674 139862869276480 run_docker.py:222] You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
I0110 16:35:08.989490 139862869276480 run_docker.py:222] 2022-01-10 21:35:08.988953: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:111] *** WARNING *** You are using ptxas 11.0.221, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.
I0110 16:35:08.989714 139862869276480 run_docker.py:222] 
I0110 16:35:08.989858 139862869276480 run_docker.py:222] You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
I0110 16:35:09.057756 139862869276480 run_docker.py:222] 2022-01-10 21:35:09.056811: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:111] *** WARNING *** You are using ptxas 11.0.221, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.
I0110 16:35:09.058145 139862869276480 run_docker.py:222] 
I0110 16:35:09.058418 139862869276480 run_docker.py:222] You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
I0110 16:35:09.135087 139862869276480 run_docker.py:222] 2022-01-10 21:35:09.134682: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:111] *** WARNING *** You are using ptxas 11.0.221, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.
I0110 16:35:09.135260 139862869276480 run_docker.py:222] 
I0110 16:35:09.135323 139862869276480 run_docker.py:222] You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
I0110 16:35:46.436159 139862869276480 run_docker.py:222] 2022-01-10 21:35:46.435644: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
I0110 16:35:46.509424 139862869276480 run_docker.py:222] Traceback (most recent call last):
I0110 16:35:46.509591 139862869276480 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 427, in <module>
I0110 16:35:46.509655 139862869276480 run_docker.py:222] app.run(main)
I0110 16:35:46.509777 139862869276480 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
I0110 16:35:46.509846 139862869276480 run_docker.py:222] _run_main(main, args)
I0110 16:35:46.509973 139862869276480 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I0110 16:35:46.510023 139862869276480 run_docker.py:222] sys.exit(main(argv))
I0110 16:35:46.510072 139862869276480 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 412, in main
I0110 16:35:46.510121 139862869276480 run_docker.py:222] is_prokaryote=is_prokaryote)
I0110 16:35:46.510169 139862869276480 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 194, in predict_structure
I0110 16:35:46.510217 139862869276480 run_docker.py:222] random_seed=model_random_seed)
I0110 16:35:46.510265 139862869276480 run_docker.py:222] File "/app/alphafold/alphafold/model/model.py", line 167, in predict
I0110 16:35:46.510312 139862869276480 run_docker.py:222] result = self.apply(self.params, jax.random.PRNGKey(random_seed), feat)
I0110 16:35:46.510361 139862869276480 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/transform.py", line 125, in apply_fn
I0110 16:35:46.510408 139862869276480 run_docker.py:222] out, state = f.apply(params, {}, *args, **kwargs)
I0110 16:35:46.510456 139862869276480 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/transform.py", line 313, in apply_fn
I0110 16:35:46.510505 139862869276480 run_docker.py:222] out = f(*args, **kwargs)
I0110 16:35:46.510553 139862869276480 run_docker.py:222] File "/app/alphafold/alphafold/model/model.py", line 87, in _forward_fn
I0110 16:35:46.510601 139862869276480 run_docker.py:222] ensemble_representations=True)
I0110 16:35:46.510649 139862869276480 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/module.py", line 428, in wrapped
I0110 16:35:46.510696 139862869276480 run_docker.py:222] out = f(*args, **kwargs)
I0110 16:35:46.510744 139862869276480 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/module.py", line 279, in run_interceptors
I0110 16:35:46.510793 139862869276480 run_docker.py:222] return bound_method(*args, **kwargs)
I0110 16:35:46.510841 139862869276480 run_docker.py:222] File "/app/alphafold/alphafold/model/modules.py", line 379, in __call__
I0110 16:35:46.510888 139862869276480 run_docker.py:222] (0, prev))
I0110 16:35:46.510935 139862869276480 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/stateful.py", line 610, in while_loop
I0110 16:35:46.510983 139862869276480 run_docker.py:222] val, state = jax.lax.while_loop(pure_cond_fun, pure_body_fun, init_val)
I0110 16:35:46.511030 139862869276480 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/stateful.py", line 605, in pure_body_fun
I0110 16:35:46.511077 139862869276480 run_docker.py:222] val = body_fun(val)
I0110 16:35:46.511124 139862869276480 run_docker.py:222] File "/app/alphafold/alphafold/model/modules.py", line 370, in <lambda>
I0110 16:35:46.511211 139862869276480 run_docker.py:222] compute_loss=False)))
I0110 16:35:46.511259 139862869276480 run_docker.py:222] File "/app/alphafold/alphafold/model/modules.py", line 342, in do_call
I0110 16:35:46.511307 139862869276480 run_docker.py:222] ensemble_representations=ensemble_representations)
I0110 16:35:46.511354 139862869276480 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/module.py", line 428, in wrapped
I0110 16:35:46.511401 139862869276480 run_docker.py:222] out = f(*args, **kwargs)
I0110 16:35:46.511449 139862869276480 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/module.py", line 279, in run_interceptors
I0110 16:35:46.511497 139862869276480 run_docker.py:222] return bound_method(*args, **kwargs)
I0110 16:35:46.511545 139862869276480 run_docker.py:222] File "/app/alphafold/alphafold/model/modules.py", line 161, in __call__
I0110 16:35:46.511593 139862869276480 run_docker.py:222] representations = evoformer_module(batch0, is_training)
I0110 16:35:46.511641 139862869276480 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/module.py", line 428, in wrapped
I0110 16:35:46.511688 139862869276480 run_docker.py:222] out = f(*args, **kwargs)
I0110 16:35:46.511736 139862869276480 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/module.py", line 279, in run_interceptors
I0110 16:35:46.511784 139862869276480 run_docker.py:222] return bound_method(*args, **kwargs)
I0110 16:35:46.511831 139862869276480 run_docker.py:222] File "/app/alphafold/alphafold/model/modules.py", line 1782, in __call__
I0110 16:35:46.511878 139862869276480 run_docker.py:222] is_training=is_training)
I0110 16:35:46.511926 139862869276480 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/module.py", line 428, in wrapped
I0110 16:35:46.511974 139862869276480 run_docker.py:222] out = f(*args, **kwargs)
I0110 16:35:46.512021 139862869276480 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/module.py", line 279, in run_interceptors
I0110 16:35:46.512068 139862869276480 run_docker.py:222] return bound_method(*args, **kwargs)
I0110 16:35:46.512115 139862869276480 run_docker.py:222] File "/app/alphafold/alphafold/model/modules.py", line 2074, in __call__
I0110 16:35:46.512162 139862869276480 run_docker.py:222] template_batch)
I0110 16:35:46.512210 139862869276480 run_docker.py:222] File "/app/alphafold/alphafold/model/mapping.py", line 182, in mapped_fn
I0110 16:35:46.512258 139862869276480 run_docker.py:222] outputs, _ = hk.scan(scan_iteration, outputs, slice_starts)
I0110 16:35:46.512306 139862869276480 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/stateful.py", line 505, in scan
I0110 16:35:46.512354 139862869276480 run_docker.py:222] stateful_fun, init, xs, length, reverse, unroll=unroll)
I0110 16:35:46.512402 139862869276480 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/stateful.py", line 487, in stateful_fun
I0110 16:35:46.512450 139862869276480 run_docker.py:222] carry, out = f(carry, x)
I0110 16:35:46.512498 139862869276480 run_docker.py:222] File "/app/alphafold/alphafold/model/mapping.py", line 171, in scan_iteration
I0110 16:35:46.512546 139862869276480 run_docker.py:222] new_outputs = compute_shard(outputs, i, shard_size)
I0110 16:35:46.512593 139862869276480 run_docker.py:222] File "/app/alphafold/alphafold/model/mapping.py", line 165, in compute_shard
I0110 16:35:46.512641 139862869276480 run_docker.py:222] slice_out = apply_fun_to_slice(slice_start, slice_size)
I0110 16:35:46.512689 139862869276480 run_docker.py:222] File "/app/alphafold/alphafold/model/mapping.py", line 138, in apply_fun_to_slice
I0110 16:35:46.512737 139862869276480 run_docker.py:222] return fun(*input_slice)
I0110 16:35:46.512784 139862869276480 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/stateful.py", line 567, in mapped_fun
I0110 16:35:46.512831 139862869276480 run_docker.py:222] out, state = mapped_pure_fun(args, state)
I0110 16:35:46.512879 139862869276480 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/stateful.py", line 558, in pure_fun
I0110 16:35:46.512926 139862869276480 run_docker.py:222] out = fun(*args)
I0110 16:35:46.512973 139862869276480 run_docker.py:222] File "/app/alphafold/alphafold/model/modules.py", line 2071, in map_fn
I0110 16:35:46.513020 139862869276480 run_docker.py:222] return template_embedder(query_embedding, batch, mask_2d, is_training)
I0110 16:35:46.513067 139862869276480 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/module.py", line 428, in wrapped
I0110 16:35:46.513115 139862869276480 run_docker.py:222] out = f(*args, **kwargs)
I0110 16:35:46.513163 139862869276480 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/module.py", line 279, in run_interceptors
I0110 16:35:46.513211 139862869276480 run_docker.py:222] return bound_method(*args, **kwargs)
I0110 16:35:46.513258 139862869276480 run_docker.py:222] File "/app/alphafold/alphafold/model/modules.py", line 1977, in __call__
I0110 16:35:46.513306 139862869276480 run_docker.py:222] quaternion=quat_affine.rot_to_quat(rot, unstack_inputs=True),
I0110 16:35:46.513354 139862869276480 run_docker.py:222] File "/app/alphafold/alphafold/model/quat_affine.py", line 113, in rot_to_quat
I0110 16:35:46.513402 139862869276480 run_docker.py:222] _, qs = jnp.linalg.eigh(k)
I0110 16:35:46.513449 139862869276480 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/jax/_src/numpy/linalg.py", line 330, in eigh
I0110 16:35:46.513497 139862869276480 run_docker.py:222] v, w = lax_linalg.eigh(a, lower=lower, symmetrize_input=symmetrize_input)
I0110 16:35:46.513546 139862869276480 run_docker.py:222] jax._src.source_info_util.JaxStackTraceBeforeTransformation: RuntimeError: jaxlib/cusolver_kernels.cc:44: operation cusolverDnCreate(&handle) failed: cuSolver internal error
```

**Comment by rdean064** [comment]
I updated the ARG CUDA=11 to CUDA=11.1 and it worked nevermind

**Comment by MIHIRKHAMBETE** [comment]
Where did you make this change @rdean064?  Is this an environment variable I can set in my conda environment?

Thanks so much for your help!

**Comment by rdean064** [comment]
I made this change in the Dockerfile, I believe it was line 15, close to the start
