### ISSUE TITLE
Missing Fasta Path

### ISSUE THREAD

**Issue by jesseaiton** [deepmind/alphafold#336]
Hello, we've had multiple error while trying to get AlphaFold to run.  Here's the latest.  

Thank you for your help!

- Jesse

ubuntu@ec2-docker-alphafold-01:~$  python3 /home/ubuntu/alphafold/docker/run_docker.py --fasta_paths=/data/userinput/YAP1_SOS1S1134.fasta --max_template_date=2020-05-14 --data_dir=/data --output_dir=/data/output
I0114 00:52:38.473187 140525888497472 run_docker.py:87] Mounting /data/userinput -> /mnt/fasta_path_0
I0114 00:52:38.473382 140525888497472 run_docker.py:87] Mounting /data/uniref90 -> /mnt/uniref90_database_path
I0114 00:52:38.473484 140525888497472 run_docker.py:87] Mounting /data/mgnify -> /mnt/mgnify_database_path
I0114 00:52:38.473573 140525888497472 run_docker.py:87] Mounting / -> /mnt/data_dir
I0114 00:52:38.473658 140525888497472 run_docker.py:87] Mounting /data/pdb_mmcif -> /mnt/template_mmcif_dir
I0114 00:52:38.473740 140525888497472 run_docker.py:87] Mounting /data/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0114 00:52:38.473819 140525888497472 run_docker.py:87] Mounting /data/pdb70 -> /mnt/pdb70_database_path
I0114 00:52:38.473898 140525888497472 run_docker.py:87] Mounting /data/uniclust30/uniclust30_2018_08 -> /mnt/uniclust30_database_path
I0114 00:52:38.473977 140525888497472 run_docker.py:87] Mounting /data/bfd -> /mnt/bfd_database_path
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.41/containers/6e372e5faa422c7adb1597229a0cb34e5cb353766d7c2feb86a15e29d22366d3/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/alphafold/docker/run_docker.py", line 231, in <module>
    app.run(main)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/ubuntu/alphafold/docker/run_docker.py", line 214, in main
    'XLA_PYTHON_CLIENT_MEM_FRACTION': '4.0',
  File "/home/ubuntu/.local/lib/python3.6/site-packages/docker/models/containers.py", line 818, in run
    container.start()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/docker/models/containers.py", line 404, in start
    return self.client.api.start(self.id, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/docker/api/container.py", line 1111, in start
    self._raise_for_status(res)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.41/containers/6e372e5faa422c7adb1597229a0cb34e5cb353766d7c2feb86a15e29d22366d3/start: Bad Request ("OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "--fasta_paths=/mnt/fasta_path_0/YAP1_SOS1S1134.fasta": stat --fasta_paths=/mnt/fasta_path_0/YAP1_SOS1S1134.fasta: no such file or directory: unknown")

**Comment by jesseaiton** [comment]
ubuntu@ec2-docker-alphafold-01:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
ubuntu@ec2-docker-alphafold-01:~$ docker -v
Docker version 20.10.12, build e91ed57

**Comment by jesseaiton** [comment]
Error gone after rebuilding everything from scratch.

Thanks,

Jesse
