### ISSUE TITLE
run_docker.py:247 Permission denied: '/mnt/output/T1050

### ISSUE THREAD

**Issue by CFDavidHou** [deepmind/alphafold#389]
Hi everyone,

First time installing Alphafold on a Ubuntu 20.04 workstation. I am able to download alphafold, docker and all database. I am also able to run nvidia-smi on docker. But when I trying to run the test run for alphafold using:
```
python3 docker/run_docker.py   --fasta_paths=T1050.fasta   --max_template_date=2020-05-14   --data_dir=/data/alphafold_database/ --gpu_devices 0 --output_dir=/tmp/alphafold/
```
I got
```
I0303 14:32:24.256715 140104902784832 run_docker.py:107] Mounting /data/alphafold -> /mnt/fasta_path_0
I0303 14:32:24.256878 140104902784832 run_docker.py:107] Mounting /data/alphafold_database/uniref90 -> /mnt/uniref90_database_path
I0303 14:32:24.256971 140104902784832 run_docker.py:107] Mounting /data/alphafold_database/mgnify -> /mnt/mgnify_database_path
I0303 14:32:24.257039 140104902784832 run_docker.py:107] Mounting /data -> /mnt/data_dir
I0303 14:32:24.257117 140104902784832 run_docker.py:107] Mounting /data/alphafold_database/pdb_mmcif -> /mnt/template_mmcif_dir
I0303 14:32:24.257225 140104902784832 run_docker.py:107] Mounting /data/alphafold_database/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0303 14:32:24.257325 140104902784832 run_docker.py:107] Mounting /data/alphafold_database/pdb70 -> /mnt/pdb70_database_path
I0303 14:32:24.257424 140104902784832 run_docker.py:107] Mounting /data/alphafold_database/uniclust30/uniclust30_2018_08 -> /mnt/uniclust30_database_path
I0303 14:32:24.257513 140104902784832 run_docker.py:107] Mounting /data/alphafold_database/bfd -> /mnt/bfd_database_path
I0303 14:32:34.304409 140104902784832 run_docker.py:247] I0303 19:32:34.302805 139841092417344 templates.py:857] Using precomputed obsolete pdbs /mnt/obsolete_pdbs_path/obsolete.dat.
I0303 14:32:34.579797 140104902784832 run_docker.py:247] I0303 19:32:34.578758 139841092417344 tpu_client.py:54] Starting the local TPU driver.
I0303 14:32:34.580289 140104902784832 run_docker.py:247] I0303 19:32:34.579347 139841092417344 xla_bridge.py:212] Unable to initialize backend 'tpu_driver': Not found: Unable to find driver in registry given worker: local://
I0303 14:32:35.488935 140104902784832 run_docker.py:247] I0303 19:32:35.487795 139841092417344 xla_bridge.py:212] Unable to initialize backend 'tpu': Invalid argument: TpuPlatform is not available.
I0303 14:32:40.530183 140104902784832 run_docker.py:247] I0303 19:32:40.529017 139841092417344 run_alphafold.py:398] Have 5 models: ['model_1', 'model_2', 'model_3', 'model_4', 'model_5']
I0303 14:32:40.530673 140104902784832 run_docker.py:247] I0303 19:32:40.529268 139841092417344 run_alphafold.py:414] Using random seed 382384219773899376 for the data pipeline
I0303 14:32:40.530990 140104902784832 run_docker.py:247] I0303 19:32:40.529708 139841092417344 run_alphafold.py:163] Predicting T1050
I0303 14:32:40.532187 140104902784832 run_docker.py:247] Traceback (most recent call last):
I0303 14:32:40.532524 140104902784832 run_docker.py:247] File "/app/alphafold/run_alphafold.py", line 445, in <module>
I0303 14:32:40.532783 140104902784832 run_docker.py:247] app.run(main)
I0303 14:32:40.533045 140104902784832 run_docker.py:247] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
I0303 14:32:40.533277 140104902784832 run_docker.py:247] _run_main(main, args)
I0303 14:32:40.533502 140104902784832 run_docker.py:247] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I0303 14:32:40.533723 140104902784832 run_docker.py:247] sys.exit(main(argv))
I0303 14:32:40.533959 140104902784832 run_docker.py:247] File "/app/alphafold/run_alphafold.py", line 429, in main
I0303 14:32:40.534217 140104902784832 run_docker.py:247] is_prokaryote=is_prokaryote)
I0303 14:32:40.534440 140104902784832 run_docker.py:247] File "/app/alphafold/run_alphafold.py", line 167, in predict_structure
I0303 14:32:40.534656 140104902784832 run_docker.py:247] os.makedirs(output_dir)
I0303 14:32:40.534886 140104902784832 run_docker.py:247] File "/opt/conda/lib/python3.7/os.py", line 223, in makedirs
I0303 14:32:40.535103 140104902784832 run_docker.py:247] mkdir(name, mode)
I0303 14:32:40.535315 140104902784832 run_docker.py:247] PermissionError: [Errno 13] Permission denied: '/mnt/output/T1050'

```
I am not sure why it need to mkdir to /mnt/output while I have indicated to use /tmp/output
I also chmod 770 to /mnt/output

Thank you for your help!

David

**Comment by sumanthmutte** [comment]
Hi, I also had the same issue. Adding `--docker_user=0` worked for me.

**Comment by CFDavidHou** [comment]
Thank you sumanthmutte,

That fixed the issue and I need to download and specify the input folder.

Best,

David

**Comment by Augustin-Zidek** [comment]
Great that the issue got solved, thanks @sumanthmutte! Closing the issue now.
