### ISSUE TITLE
Folding multiple proteins one after another

### ISSUE THREAD

**Issue by ioioba** [deepmind/alphafold#398]
Hi!
I am not able to sequentially fold proteins. After Monomer1 is successfully predicted, I will get a RuntimeError for Jackhmmer. Any ideas how I could fix that?

```
python3 docker/run_docker.py \
  --fasta_paths=monomer1.fasta,monomer2.fasta,monomer3.fasta,monomer4.fasta,monomer5.fasta,monomer6.fasta,monomer7.fasta,monomer8.fasta,monomer9.fasta,monomer10.fasta,monomer11.fasta,monomer12.fasta,monomer13.fasta,monomer14.fasta,monomer15.fasta,monomer16.fasta,monomer17.fasta \
  --max_template_date=2021-11-01 \
  --model_preset=monomer \
  --data_dir=/alphafold2/geneticdb
```

```
I0313 22:03:13.001301 140516391523136 run_docker.py:87] Mounting /home/orpheus/alphafold -> /mnt/fasta_path_0
I0313 22:03:13.001447 140516391523136 run_docker.py:87] Mounting /home/orpheus/alphafold -> /mnt/fasta_path_1
I0313 22:03:13.001525 140516391523136 run_docker.py:87] Mounting /home/orpheus/alphafold -> /mnt/fasta_path_2
I0313 22:03:13.001590 140516391523136 run_docker.py:87] Mounting /home/orpheus/alphafold -> /mnt/fasta_path_3
I0313 22:03:13.001650 140516391523136 run_docker.py:87] Mounting /home/orpheus/alphafold -> /mnt/fasta_path_4
I0313 22:03:13.001708 140516391523136 run_docker.py:87] Mounting /home/orpheus/alphafold -> /mnt/fasta_path_5
I0313 22:03:13.001766 140516391523136 run_docker.py:87] Mounting /home/orpheus/alphafold -> /mnt/fasta_path_6
I0313 22:03:13.001822 140516391523136 run_docker.py:87] Mounting /home/orpheus/alphafold -> /mnt/fasta_path_7
I0313 22:03:13.001878 140516391523136 run_docker.py:87] Mounting /home/orpheus/alphafold -> /mnt/fasta_path_8
I0313 22:03:13.001934 140516391523136 run_docker.py:87] Mounting /home/orpheus/alphafold -> /mnt/fasta_path_9
I0313 22:03:13.001990 140516391523136 run_docker.py:87] Mounting /home/orpheus/alphafold -> /mnt/fasta_path_10
I0313 22:03:13.002045 140516391523136 run_docker.py:87] Mounting /home/orpheus/alphafold -> /mnt/fasta_path_11
I0313 22:03:13.002100 140516391523136 run_docker.py:87] Mounting /home/orpheus/alphafold -> /mnt/fasta_path_12
I0313 22:03:13.002156 140516391523136 run_docker.py:87] Mounting /home/orpheus/alphafold -> /mnt/fasta_path_13
I0313 22:03:13.002211 140516391523136 run_docker.py:87] Mounting /home/orpheus/alphafold -> /mnt/fasta_path_14
I0313 22:03:13.002304 140516391523136 run_docker.py:87] Mounting /home/orpheus/alphafold -> /mnt/fasta_path_15
I0313 22:03:13.002362 140516391523136 run_docker.py:87] Mounting /home/orpheus/alphafold -> /mnt/fasta_path_16
I0313 22:03:13.002428 140516391523136 run_docker.py:87] Mounting /media/orpheus/Volume/alphafold2/geneticdb/uniref90 -> /mnt/uniref90_database_path
I0313 22:03:13.002483 140516391523136 run_docker.py:87] Mounting /media/orpheus/Volume/alphafold2/geneticdb/mgnify -> /mnt/mgnify_database_path
I0313 22:03:13.002540 140516391523136 run_docker.py:87] Mounting /media/orpheus/Volume/alphafold2 -> /mnt/data_dir
I0313 22:03:13.002595 140516391523136 run_docker.py:87] Mounting /media/orpheus/Volume/alphafold2/geneticdb/pdb_mmcif -> /mnt/template_mmcif_dir
I0313 22:03:13.002647 140516391523136 run_docker.py:87] Mounting /media/orpheus/Volume/alphafold2/geneticdb/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0313 22:03:13.002699 140516391523136 run_docker.py:87] Mounting /media/orpheus/Volume/alphafold2/geneticdb/pdb70 -> /mnt/pdb70_database_path
I0313 22:03:13.002753 140516391523136 run_docker.py:87] Mounting /media/orpheus/Volume/alphafold2/geneticdb/uniclust30/uniclust30_2018_08 -> /mnt/uniclust30_database_path
I0313 22:03:13.002809 140516391523136 run_docker.py:87] Mounting /media/orpheus/Volume/alphafold2/geneticdb/bfd -> /mnt/bfd_database_path
I0313 22:03:18.772360 140516391523136 run_docker.py:222] I0313 21:03:18.770702 140687586509376 templates.py:857] Using precomputed obsolete pdbs /mnt/obsolete_pdbs_path/obsolete.dat.
I0313 22:03:19.656363 140516391523136 run_docker.py:222] I0313 21:03:19.655210 140687586509376 xla_bridge.py:232] Unable to initialize backend 'tpu_driver': Not found: Unable to find driver in registry given worker:
I0313 22:03:19.968801 140516391523136 run_docker.py:222] I0313 21:03:19.967914 140687586509376 xla_bridge.py:232] Unable to initialize backend 'tpu': Invalid argument: TpuPlatform is not available.
I0313 22:03:28.249876 140516391523136 run_docker.py:222] I0313 21:03:28.248956 140687586509376 run_alphafold.py:385] Have 5 models: ['model_1', 'model_2', 'model_3', 'model_4', 'model_5']
I0313 22:03:28.250254 140516391523136 run_docker.py:222] I0313 21:03:28.249117 140687586509376 run_alphafold.py:397] Using random seed 367833323599017463 for the data pipeline
I0313 22:03:28.250464 140516391523136 run_docker.py:222] I0313 21:03:28.249301 140687586509376 run_alphafold.py:150] Predicting monomer1
I0313 22:03:28.250652 140516391523136 run_docker.py:222] I0313 21:03:28.249737 140687586509376 jackhmmer.py:130] Launching subprocess "/usr/bin/jackhmmer -o /dev/null -A /tmp/tmp8mv8kjhd/output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 /mnt/fasta_path_0/monomer1.fasta /mnt/uniref90_database_path/uniref90.fasta"
I0313 22:03:28.336877 140516391523136 run_docker.py:222] I0313 21:03:28.335646 140687586509376 utils.py:36] Started Jackhmmer (uniref90.fasta) query
I0313 22:08:27.289564 140516391523136 run_docker.py:222] I0313 21:08:27.287927 140687586509376 utils.py:40] Finished Jackhmmer (uniref90.fasta) query in 298.952 seconds
I0313 22:08:30.136481 140516391523136 run_docker.py:222] I0313 21:08:30.135757 140687586509376 jackhmmer.py:130] Launching subprocess "/usr/bin/jackhmmer -o /dev/null -A /tmp/tmp3761cm1p/output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 /mnt/fasta_path_0/monomer1.fasta /mnt/mgnify_database_path/mgy_clusters_2018_12.fa"
I0313 22:08:30.253056 140516391523136 run_docker.py:222] I0313 21:08:30.251883 140687586509376 utils.py:36] Started Jackhmmer (mgy_clusters_2018_12.fa) query
I0313 22:13:29.656303 140516391523136 run_docker.py:222] I0313 21:13:29.655318 140687586509376 utils.py:40] Finished Jackhmmer (mgy_clusters_2018_12.fa) query in 299.403 seconds
I0313 22:13:53.586398 140516391523136 run_docker.py:222] I0313 21:13:53.585451 140687586509376 hhsearch.py:85] Launching subprocess "/usr/bin/hhsearch -i /tmp/tmpd4vdjick/query.a3m -o /tmp/tmpd4vdjick/output.hhr -maxseq 1000000 -d /mnt/pdb70_database_path/pdb70"
I0313 22:13:53.726624 140516391523136 run_docker.py:222] I0313 21:13:53.725453 140687586509376 utils.py:36] Started HHsearch query
I0313 22:14:50.214117 140516391523136 run_docker.py:222] I0313 21:14:50.213157 140687586509376 utils.py:40] Finished HHsearch query in 56.487 seconds
I0313 22:17:08.262918 140516391523136 run_docker.py:222] I0313 21:17:08.261912 140687586509376 hhblits.py:128] Launching subprocess "/usr/bin/hhblits -i /mnt/fasta_path_0/monomer1.fasta -cpu 4 -oa3m /tmp/tmph3p5cu1u/output.a3m -o /dev/null -n 3 -e 0.001 -maxseq 1000000 -realign_max 100000 -maxfilt 100000 -min_prefilter_hits 1000 -d /mnt/bfd_database_path/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt -d /mnt/uniclust30_database_path/uniclust30_2018_08"
I0313 22:17:08.406514 140516391523136 run_docker.py:222] I0313 21:17:08.405243 140687586509376 utils.py:36] Started HHblits query
I0313 22:36:11.271251 140516391523136 run_docker.py:222] I0313 21:36:11.266434 140687586509376 utils.py:40] Finished HHblits query in 1142.860 seconds
I0313 22:36:11.425054 140516391523136 run_docker.py:222] I0313 21:36:11.424136 140687586509376 templates.py:878] Searching for template for: M...
```

```
I0313 22:54:22.337987 140516391523136 run_docker.py:222] I0313 21:54:22.337053 140687586509376 run_alphafold.py:150] Predicting monomer2
I0313 22:54:22.338453 140516391523136 run_docker.py:222] I0313 21:54:22.337955 140687586509376 jackhmmer.py:130] Launching subprocess "/usr/bin/jackhmmer -o /dev/null -A /tmp/tmptccpjr8w/output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 /mnt/fasta_path_1/monomer2.fasta /mnt/uniref90_database_path/uniref90.fasta"
I0313 22:54:22.605316 140516391523136 run_docker.py:222] I0313 21:54:22.603882 140687586509376 utils.py:36] Started Jackhmmer (uniref90.fasta) query
I0313 22:59:24.319112 140516391523136 run_docker.py:222] I0313 21:59:24.318029 140687586509376 utils.py:40] Finished Jackhmmer (uniref90.fasta) query in 301.713 seconds
I0313 22:59:27.217394 140516391523136 run_docker.py:222] I0313 21:59:27.216411 140687586509376 jackhmmer.py:130] Launching subprocess "/usr/bin/jackhmmer -o /dev/null -A /tmp/tmpdqnybrr2/output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 /mnt/fasta_path_1/monomer2.fasta /mnt/mgnify_database_path/mgy_clusters_2018_12.fa"
I0313 22:59:27.512285 140516391523136 run_docker.py:222] I0313 21:59:27.510892 140687586509376 utils.py:36] Started Jackhmmer (mgy_clusters_2018_12.fa) query
I0313 23:04:06.377542 140516391523136 run_docker.py:222] I0313 22:04:06.376432 140687586509376 utils.py:40] Finished Jackhmmer (mgy_clusters_2018_12.fa) query in 278.865 seconds
I0313 23:04:06.382214 140516391523136 run_docker.py:222] Traceback (most recent call last):
I0313 23:04:06.382480 140516391523136 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 427, in <module>
I0313 23:04:06.382655 140516391523136 run_docker.py:222] app.run(main)
I0313 23:04:06.382859 140516391523136 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
I0313 23:04:06.383009 140516391523136 run_docker.py:222] _run_main(main, args)
I0313 23:04:06.383154 140516391523136 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I0313 23:04:06.383295 140516391523136 run_docker.py:222] sys.exit(main(argv))
I0313 23:04:06.383433 140516391523136 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 412, in main
I0313 23:04:06.383570 140516391523136 run_docker.py:222] is_prokaryote=is_prokaryote)
I0313 23:04:06.383706 140516391523136 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 164, in predict_structure
I0313 23:04:06.383841 140516391523136 run_docker.py:222] msa_output_dir=msa_output_dir)
I0313 23:04:06.383975 140516391523136 run_docker.py:222] File "/app/alphafold/alphafold/data/pipeline.py", line 165, in process
I0313 23:04:06.384110 140516391523136 run_docker.py:222] self.use_precomputed_msas)
I0313 23:04:06.384246 140516391523136 run_docker.py:222] File "/app/alphafold/alphafold/data/pipeline.py", line 97, in run_msa_tool
I0313 23:04:06.384381 140516391523136 run_docker.py:222] result = msa_runner.query(input_fasta_path)[0]
I0313 23:04:06.384515 140516391523136 run_docker.py:222] File "/app/alphafold/alphafold/data/tools/jackhmmer.py", line 163, in query
I0313 23:04:06.384667 140516391523136 run_docker.py:222] return [self._query_chunk(input_fasta_path, self.database_path)]
I0313 23:04:06.384802 140516391523136 run_docker.py:222] File "/app/alphafold/alphafold/data/tools/jackhmmer.py", line 140, in _query_chunk
I0313 23:04:06.384937 140516391523136 run_docker.py:222] 'Jackhmmer failed\nstderr:\n%s\n' % stderr.decode('utf-8'))
I0313 23:04:06.385072 140516391523136 run_docker.py:222] RuntimeError: Jackhmmer failed
I0313 23:04:06.385208 140516391523136 run_docker.py:222] stderr:
I0313 23:04:06.385345 140516391523136 run_docker.py:222] 
I0313 23:04:06.385482 140516391523136 run_docker.py:222] 
```

**Comment by Augustin-Zidek** [comment]
Is it possible you don't have enough disk space or running out of memory? It would also be useful to try running Jackhmmer manually with the sequence that is causing the issue: 

```
/usr/bin/jackhmmer -o /dev/null -A /tmp/tmpdqnybrr2/output.sto --noali \
--F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 \
/mnt/fasta_path_1/monomer2.fasta \
/mnt/mgnify_database_path/mgy_clusters_2018_12.fa
```

**Comment by Augustin-Zidek** [comment]
Closing this now, feel free to reopen if this is still an issue.
