### ISSUE TITLE
On docker after some time: No compatible CUDA device is available

### ISSUE THREAD

**Issue by Wolf-Z** [deepmind/alphafold#403]
The Environment:
================

Running on Docker 20.10.12-3 on RHEL 7.9 with 4x NVIDIA Corporation GV100GL [Tesla V100 PCIe 32GB] cards.
CUDA version on this host is 11.4.

I also get this version reported, when doing a 
```
  docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi
```
Seems fine to me?

The Problem:
============

So I am running alphafold (version from beginning of march 2022) like this:

```
python3 /software/alphafold2/alphafold/docker/run_docker.py \
--fasta_paths=/software/db/alphafold2/example_input/T1050.fasta \
--max_template_date=2020-05-14 --data_dir=/software/db/alphafold2/alldata
```
This is using python3 from a venv installed like this:

```
    python3 -m venv $envPath
    source $envPath/bin/activate
    pip3 install --upgrade pip
    pip3 install -r /software/alphafold2/alphafold/docker/requirements.txt
```

After quite some hours this is comming up exactly a 100 times:    
  
```
I0316 18:50:27.090867 140103983331136 run_docker.py:247] I0316 17:50:27.090230 139823954499392 amber_minimize.py:408] Minimizing protein, attempt 100 of 100.
I0316 18:50:29.051809 140103983331136 run_docker.py:247] I0316 17:50:29.049898 139823954499392 amber_minimize.py:69] Restraining 6213 / 12189 particles.
I0316 18:50:29.170636 140103983331136 run_docker.py:247] I0316 17:50:29.170062 139823954499392 amber_minimize.py:417] No compatible CUDA device is available
```

... ultimately leading to this:

```
I0316 18:50:29.207758 140103983331136 run_docker.py:247] Traceback (most recent call last):
I0316 18:50:29.207883 140103983331136 run_docker.py:247] File "/app/alphafold/run_alphafold.py", line 445, in <module>                                           I0316 18:50:29.207957 140103983331136 run_docker.py:247] app.run(main)
I0316 18:50:29.208023 140103983331136 run_docker.py:247] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run                             I0316 18:50:29.208087 140103983331136 run_docker.py:247] _run_main(main, args)
I0316 18:50:29.208148 140103983331136 run_docker.py:247] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I0316 18:50:29.208209 140103983331136 run_docker.py:247] sys.exit(main(argv))
I0316 18:50:29.208268 140103983331136 run_docker.py:247] File "/app/alphafold/run_alphafold.py", line 429, in main
I0316 18:50:29.208327 140103983331136 run_docker.py:247] is_prokaryote=is_prokaryote)
I0316 18:50:29.208385 140103983331136 run_docker.py:247] File "/app/alphafold/run_alphafold.py", line 250, in predict_structure
I0316 18:50:29.208454 140103983331136 run_docker.py:247] relaxed_pdb_str, _, _ = amber_relaxer.process(prot=unrelaxed_protein)
I0316 18:50:29.208513 140103983331136 run_docker.py:247] File "/app/alphafold/alphafold/relax/relax.py", line 66, in process
I0316 18:50:29.208570 140103983331136 run_docker.py:247] use_gpu=self._use_gpu)
I0316 18:50:29.208626 140103983331136 run_docker.py:247] File "/app/alphafold/alphafold/relax/amber_minimize.py", line 483, in run_pipeline                      I0316 18:50:29.208684 140103983331136 run_docker.py:247] use_gpu=use_gpu)
I0316 18:50:29.208741 140103983331136 run_docker.py:247] File "/app/alphafold/alphafold/relax/amber_minimize.py", line 419, in _run_one_iteration
I0316 18:50:29.208799 140103983331136 run_docker.py:247] raise ValueError(f"Minimization failed after {max_attempts} attempts.")
I0316 18:50:29.208857 140103983331136 run_docker.py:247] ValueError: Minimization failed after 100 attempts.
```

The Questions: 
==============

  * What is Alphafold (docker) considering a "compatible CUDA device"?
  * As I think I have such one - what can I do to make it acknowledged by Alphafold running in docker?

**Comment by jarunan** [comment]
Hi Wolf-Z,

I saw the same exception thrown. 
Is the GPU set to the exclusive mode? The algorithm may try to create multiple GPU context (someone please confirm) but the GPU in exclusive mode prevents creating multiple contexts. https://github.com/openmm/openmm/issues/3518

### Question to AlphaFold2 developers
Is it possible to disabling the multiple GPU context creation in amber_minimize.py?

**Comment by arashnh11** [comment]
Following - same error - Nvidia has already been set to exclusive mode

**Comment by arashnh11** [comment]
@jarunan Thanks! That looks like another way of changing CUDA's operation to the default mode.. nvidia-smi -c 0 fixed it for me. 
@Augustin-Zidek You may want to mention in the requirements that GPU compute mode must be set to default or MPS should be enabled as @jarunan mentioned. 
I did not see this behavior in previous versions of alphafold.

**Comment by Wolf-Z** [comment]
By the way. 
What I've realized in the meantime:
**I don't get the error when running the container as root. Only as user.**

But running this as user is still my main aim.

Please notice: When running the test command (see original issue) then those "sub processes" from the container run fine:
  * `/usr/bin/jackhmmer` (2 times)
  * `/usr/bin/hhsearch`
  * `/usr/bin/hhblits`
  * maybe more - I've just started a new calculation some hours before and the hhblits really takes its time

Anyway - thanks for all the suggestions so far.

  * `nvidia-smi -c 0`
    * didn't help - every GPU (4 GPUs are installed within the machine) already was in default mode
  * `nvidia-cuda-mps-control -d`
    * leads to a crash right after the "TPU driver" check:
      * `I0412 [...] run_docker.py:247] Fatal Python error: Segmentation fault`

The full error in "`nvidia-cuda-mps-control -d`" mode is (deleted all the time stamps and run_docker.py prefixes):
```
Current thread 0x00007fd41dac3740 (most recent call first):
"/opt/conda/lib/python3.7/site-packages/jaxlib/xla_client.py", line 98 in make_gpu_client
"/opt/conda/lib/python3.7/site-packages/jax/lib/xla_bridge.py", line 192 in backends
"/opt/conda/lib/python3.7/site-packages/jax/lib/xla_bridge.py", line 228 in get_backend
"/opt/conda/lib/python3.7/site-packages/jax/lib/xla_bridge.py", line 249 in get_device_backen
"/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 138 in _device_put_arr
"/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 133 in device_put
"/opt/conda/lib/python3.7/site-packages/jax/_src/lax/lax.py", line 1596 in _device_put_raw
"/opt/conda/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 2996 in array
"/app/alphafold/alphafold/model/utils.py", line 80 in flat_params_to_haiku
"/app/alphafold/alphafold/model/data.py", line 39 in get_model_haiku_params
"/app/alphafold/run_alphafold.py", line 393 in main
"/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258 in _run_main
"/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312 in run
"/app/alphafold/run_alphafold.py", line 445 in <module>
/app/run_alphafold.sh: line 3:     9 Segmentation fault      python /app/alphafold/run_alphafold.py "$@"
```

My last thought (for Today):

There were suggestions that OpenMM is the source of the problem. In order to check if OpenMM is working fine, they say: Check its included test cases. Unfortunately building those test cases from inside the container is really a lot of work because of missing compilers (obviously), RO Conda Env, include paths and libpaths all over the place under /opt - not really something I'd like to do. 
All I want to check is: Can OpenMM see my Cuda devices, where does it look for those and are there maybe some permission problems?

Are there any suggestions how to check openMM without building it's test cases from within the container?

**Comment by 132nd-Entropy** [comment]
Hi, I ran into the same issue, in case others read this, maybe it helps someone. 

the error "No compatible CUDA device is available" (see orgininal post #403 ) happened to me when I on the same workstation started 2 AF-multimer predictions. 

apparently whats happening is that the program uses only the first of my (3 in total) GPUs. When I start 2 precictions, both seem to compete over the same GPU and as a result I got the No compatible CUDA device is available error. 


when I add the parameter   --gpu_devices= 0 on the first prediction and   --gpu_devices=1 to the second, both seem to be runnig without the above error. So, apparently one cannot have more than one job per GPU, and the GPU should be specified if one wants to run several predictions on the side. 

As others also had reported, I did not managed to get more than one GPU utilized per job

**Comment by akenginorhun** [comment]
I've been having the same problem, anyone have any idea how to fix it?

**Comment by prehensilecode** [comment]
I think the root cause is in `amber_minimize.py` in the `_openmm_minimize()` function. 

OpenMM does allow multiple GPUs, but you have to define `properties["DeviceIndex"]` 
to explicitly enumerate the devices available. See: http://docs.openmm.org/latest/userguide/library/04_platform_specifics.html#cuda-platform

However, [`_openmm_minimize()` in `v2.3.1`](https://github.com/deepmind/alphafold/blob/v2.3.1/alphafold/relax/amber_minimize.py) does not do so after defining the Platform. 

Wrote a bit more about this in my issue in `alphafold_singularity` that is auto-linked above.

**Comment by TJiangBio** [comment]
> 嗨，我遇到了同样的问题，如果其他人读到这篇文章，也许会对某人有所帮助。
> 
> 当我在同一工作站上开始两个多聚体预测时，发生了错误“没有可用的兼容 CUDA 设备”（请参阅​​原始帖子[#403 ）。](https://github.com/google-deepmind/alphafold/issues/403)
> 
> 显然发生的事情是该程序仅使用我的第一个（总共 3 个）GPU。当我开始 2 个预测时，两个预测似乎都在竞争同一个 GPU，因此我收到了“没有可用的兼容 CUDA 设备”错误。
> 
> 当我在第一个预测中添加参数 --gpu_devices= 0 并在第二个预测中添加参数 --gpu_devices=1 时，两者似乎都在运行而没有出现上述错误。因此，显然每个 GPU 不能有多个作业，如果想要同时运行多个预测，则应指定 GPU。 正如其他人也报告的那样，我没有设法为每个作业使用多个 GPU ，因此 --gpu_devices=0,1 与 --gpu_devices=0 相同，看起来第二个 GPU 被忽略



> Enabling MPS helps. (nvidia-cuda-mps-control -d) https://docs.nvidia.com/deploy/mps/index.html

Yes, this solution fixed. Thx

**Comment by TJiangBio** [comment]
> Enabling MPS helps. (nvidia-cuda-mps-control -d) https://docs.nvidia.com/deploy/mps/index.html

This works!~

**Comment by JieGao1111** [comment]
> ## 更新
> _由于某种原因，在**不改变任何东西的**情况下（好吧 - 我在启动之前运行了“nvidia-smi -c 0”，但它告诉我，所有 4 个 GPU 都已处于默认模式），并且仅在正在运行的容器内并行寻找一些提示 -**我以用户身份运行了示例计算。** 所以整个问题可能只是一个巨大的干扰 - 如果是这样的话，我很抱歉。 我唯一的想法是，我们有一个 systemd-tmpfiles 作业正在运行，在我第一次尝试时可能已经删除了 /tmp/alphafold 文件夹，而这对于 alphafold 容器的工作似乎非常关键。_
> 
> ## 原始评论
> 顺便说一句。与此同时 ，我意识到： **以 root 身份运行容器时，我没有收到错误。只有以用户身份运行才会收到错误。**
> 
> 但以用户身份运行它仍然是我的主要目标。
> 
> 请注意：运行测试命令时（参见原始问题），容器中的那些“子进程”运行良好：
> 
> * `/usr/bin/jackhmmer`（2次）
> * `/usr/bin/hhsearch`
> * `/usr/bin/hhblits`
> * 可能更多 - 我几个小时前才开始进行新的计算，hhblits 确实需要花费一些时间
> 
> 无论如何 - 感谢您迄今为止提出的所有建议。
> 
> * `nvidia-smi -c 0`
>   
>   * 没有帮助——每个 GPU（机器内安装了 4 个 GPU）已经处于默认模式
> * `nvidia-cuda-mps-control -d`
>   
>   * 在检查“TPU 驱动程序”后立即导致崩溃：
>     
>     * `I0412 [...] run_docker.py:247] Fatal Python error: Segmentation fault`
> 
> “”模式下的完整错误`nvidia-cuda-mps-control -d`是（删除了所有时间戳和run_docker.py前缀）：
> 
> ```
> Current thread 0x00007fd41dac3740 (most recent call first):
> "/opt/conda/lib/python3.7/site-packages/jaxlib/xla_client.py", line 98 in make_gpu_client
> "/opt/conda/lib/python3.7/site-packages/jax/lib/xla_bridge.py", line 192 in backends
> "/opt/conda/lib/python3.7/site-packages/jax/lib/xla_bridge.py", line 228 in get_backend
> "/opt/conda/lib/python3.7/site-packages/jax/lib/xla_bridge.py", line 249 in get_device_backen
> "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 138 in _device_put_arr
> "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 133 in device_put
> "/opt/conda/lib/python3.7/site-packages/jax/_src/lax/lax.py", line 1596 in _device_put_raw
> "/opt/conda/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 2996 in array
> "/app/alphafold/alphafold/model/utils.py", line 80 in flat_params_to_haiku
> "/app/alphafold/alphafold/model/data.py", line 39 in get_model_haiku_params
> "/app/alphafold/run_alphafold.py", line 393 in main
> "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258 in _run_main
> "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312 in run
> "/app/alphafold/run_alphafold.py", line 445 in <module>
> /app/run_alphafold.sh: line 3:     9 Segmentation fault      python /app/alphafold/run_alphafold.py "$@"
> ```
> 
> 我今天最后一个想法是：
> 
> 有人认为 OpenMM 是问题的根源。为了检查 OpenMM 是否正常工作，他们说：检查其包含的测试用例。不幸的是，从容器内部构建这些测试用例确实是一项艰巨的工作，因为缺少编译器（显然）、RO Conda Env、包含路径和 libpath 遍布 /opt 下 - 这不是我真正想做的事情。我想检查的 是：OpenMM 是否可以看到我的 Cuda 设备，它在哪里寻找这些设备，是否可能存在一些权限问题？
> 
> 有没有什么建议可以在不从容器内部构建测试用例的情况下检查 openMM？

I am also encountering the same problem, has your problem been solved?

**Comment by mandalapr0** [comment]
Check Table 3 under this link to check if your driver version is up to date / compatible with your cuda version. https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html. For me i had to update my driver version for some reason the latest drivers were not installed.
