### ISSUE TITLE
ValueError: Cannot create a tensor proto whose content is larger than 2GB.

### ISSUE THREAD

**Issue by SSchott** [deepmind/alphafold#43]
Got a system for which the features.pkl is 5 GB. Any workaround for this?

```
Traceback (most recent call last):
  File "/X/alphafold/run_alphafold.py", line 283, in <module>
    app.run(main)
  File "/X/miniconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/X/miniconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/X/alphafold/run_alphafold.py", line 255, in main
    predict_structure(
  File "/X/alphafold/run_alphafold.py", line 132, in predict_structure
    processed_feature_dict = model_runner.process_features(
  File "/X/alphafold/alphafold/model/model.py", line 103, in process_features
    return features.np_example_to_features(
  File "/X/alphafold/alphafold/model/features.py", line 93, in np_example_to_features
    tensor_dict = proteins_dataset.np_to_tensor_dict(
  File "/X/alphafold/alphafold/model/tf/proteins_dataset.py", line 162, in np_to_tensor_dict
    tensor_dict = {k: tf.constant(v) for k, v in np_example.items()
  File "/X/alphafold/alphafold/model/tf/proteins_dataset.py", line 162, in <dictcomp>
    tensor_dict = {k: tf.constant(v) for k, v in np_example.items()
  File "/X/miniconda3/envs/alphafold/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 162, in constant_v1
    return _constant_impl(value, dtype, shape, name, verify_shape=verify_shape,
  File "/X/miniconda3/envs/alphafold/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 281, in _constant_impl
    tensor_util.make_tensor_proto(
  File "/X/miniconda3/envs/alphafold/lib/python3.8/site-packages/tensorflow/python/framework/tensor_util.py", line 527, in make_tensor_proto            raise ValueError(
ValueError: Cannot create a tensor proto whose content is larger than 2GB.
```

**Comment by abridgland** [comment]
Hi, how big is the protein you’re trying to inference? Unfortunately there’s no easy workaround for this but if the large inputs are the result of a long input sequence you will probably find that the model inference stage would fail too due to the GPU running out of memory.

**Comment by SSchott** [comment]
Hi,
Thanks for the reply. It is quite big, ~2700 residues. If there is no tweak on the tf side, then I might have to be more restrictive with the sequence search/alignment step.
Still, if that is the case, you might want to consider an if else statement checking for the length of the alignments, right?
I will just close this then, but if you have any additional suggestion, please just let me know.
Cheers,

**Comment by abridgland** [comment]
Unfortunately it is a hard limit on the TF side indeed. That’s also right around the upper limit of what we ran for the AlphaFold database (see the second FAQ here: https://alphafold.ebi.ac.uk/faq) so you may still have luck fitting it onto a GPU but it might be a tight fit. We generally see MSA construction working at that size so it’s unlikely to be very far over the limit — removing just a few residues might make the sequence fit. You could also try predicting shorter overlapping subsequences — that is the approach we took for sequence lengths over 2700 for the database release. One final suggestion, if you haven’t already tried it, is to run with `--preset=reduced_dbs` which should reduce the size of your MSA. This is the setup that was used to produce the AlphaFold database predictions.

**Comment by SSchott** [comment]
Cool, I will give it a shot. Thanks!
