### ISSUE TITLE
RuntimeError: Jackhmmer failed

### ISSUE THREAD

**Issue by JuhoChoi17** [deepmind/alphafold#465]
```
I0513 19:20:13.137548 139839010051904 run_docker.py:222] I0513 10:20:13.137169 140392097924928 jackhmmer.py:130] Launching subprocess "/usr/bin/jackhmmer -o /dev/null -A /tmp/tmpmva056s_/output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 /tmp/tmpg68lffer.fasta /mnt/uniprot_database_path/uniprot.fasta"
I0513 19:20:13.196953 139839010051904 run_docker.py:222] I0513 10:20:13.196384 140392097924928 utils.py:36] Started Jackhmmer (uniprot.fasta) query
I0513 19:20:13.374374 139839010051904 run_docker.py:222] I0513 10:20:13.373903 140392097924928 utils.py:40] Finished Jackhmmer (uniprot.fasta) query in 0.177 seconds
I0513 19:20:13.395548 139839010051904 run_docker.py:222] Traceback (most recent call last):
I0513 19:20:13.395641 139839010051904 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 427, in <module>
I0513 19:20:13.395710 139839010051904 run_docker.py:222] app.run(main)
I0513 19:20:13.395773 139839010051904 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
I0513 19:20:13.395833 139839010051904 run_docker.py:222] _run_main(main, args)
I0513 19:20:13.395893 139839010051904 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I0513 19:20:13.395951 139839010051904 run_docker.py:222] sys.exit(main(argv))
I0513 19:20:13.396009 139839010051904 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 412, in main
I0513 19:20:13.396066 139839010051904 run_docker.py:222] is_prokaryote=is_prokaryote)
I0513 19:20:13.396123 139839010051904 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 169, in predict_structure
I0513 19:20:13.396180 139839010051904 run_docker.py:222] is_prokaryote=is_prokaryote)
I0513 19:20:13.396237 139839010051904 run_docker.py:222] File "/app/alphafold/alphafold/data/pipeline_multimer.py", line 271, in process
I0513 19:20:13.396294 139839010051904 run_docker.py:222] is_homomer_or_monomer=is_homomer_or_monomer)
I0513 19:20:13.396351 139839010051904 run_docker.py:222] File "/app/alphafold/alphafold/data/pipeline_multimer.py", line 220, in _process_single_chain
I0513 19:20:13.396408 139839010051904 run_docker.py:222] chain_msa_output_dir)
I0513 19:20:13.396465 139839010051904 run_docker.py:222] File "/app/alphafold/alphafold/data/pipeline_multimer.py", line 229, in _all_seq_msa_features
I0513 19:20:13.396521 139839010051904 run_docker.py:222] self.use_precomputed_msas)
I0513 19:20:13.396578 139839010051904 run_docker.py:222] File "/app/alphafold/alphafold/data/pipeline.py", line 97, in run_msa_tool
I0513 19:20:13.396634 139839010051904 run_docker.py:222] result = msa_runner.query(input_fasta_path)[0]
I0513 19:20:13.396690 139839010051904 run_docker.py:222] File "/app/alphafold/alphafold/data/tools/jackhmmer.py", line 163, in query
I0513 19:20:13.396760 139839010051904 run_docker.py:222] return [self._query_chunk(input_fasta_path, self.database_path)]
I0513 19:20:13.396819 139839010051904 run_docker.py:222] File "/app/alphafold/alphafold/data/tools/jackhmmer.py", line 140, in _query_chunk
I0513 19:20:13.396875 139839010051904 run_docker.py:222] 'Jackhmmer failed\nstderr:\n%s\n' % stderr.decode('utf-8'))
I0513 19:20:13.396932 139839010051904 run_docker.py:222] RuntimeError: Jackhmmer failed
I0513 19:20:13.396988 139839010051904 run_docker.py:222] stderr:
I0513 19:20:13.397045 139839010051904 run_docker.py:222] 
I0513 19:20:13.397102 139839010051904 run_docker.py:222] Error: Parse failed (sequence file /mnt/uniprot_database_path/uniprot.fasta):
I0513 19:20:13.397159 139839010051904 run_docker.py:222] Line 1: unexpected char ; expected FASTA to start with >
I0513 19:20:13.397215 139839010051904 run_docker.py:222] 
I0513 19:20:13.397270 139839010051904 run_docker.py:222] 
I0513 19:20:13.397326 139839010051904 run_docker.py:222]
```

Hi, I tried to modelling of antibody-like protein (H2L2 tetramer), and got this error messages.
What is the cause of this issue? And what I have to do to solve this problem?
Thank you.

**Comment by avilella** [comment]
I get a similar issue to this every once in a while, when jackhmmer returns hits from querying uniprot.fasta and some of the hits contain the wrong type of characters (utf-8 error). I'll link this bug to the other one.

**Comment by koster20** [comment]
Check your .fasta file. It's should start with ">". There is example:

```
>mreb
MLSKLLGVLSADMAIDLGTANTLVYVKGRGIVLNEPSVVAIANVRGKKQVLAVGDEAKMMLGRTPGNIQA
IRPLRDGVIADFEVAEEMIKHFIRKVHNRRSFASPQVIICVPSGSTAVERRAIQESAEAAGARRVFLIEE
PMAAAIGAGLPVTEPTGSMVVDIGGGTTEVAVLSLGGIVYSRSVRVGGDKMDEAIIGYIRRTHNLLVGEG
SAERIKKEIGSACPPEDGEGRILEIKGRDLMNGVPKELIISERQIAESLAEPVSAIVEAVKVALEHTAPE
LAADIVDKGIVLTGGGALLGNLDFVLRHATGLPVSIADDPLSCVALGTGRALEEMKTLRNVLVSAY
```
