### ISSUE TITLE
Jackhmmer failed without error message

### ISSUE THREAD

**Issue by RodenLuo** [deepmind/alphafold#477]
Hi, I have one run that failed at the Jackhmmer step while the other run passed it. The one failed did not give any error message. But I guess it might be related to memory. Just in case you wanna debug it, I'm attaching the info for reproducing it. 

### The one failed

The requested node parameter: one A100, 2GB RAM, 1vCPU.

Log:
```
...
I0526 10:11:57.089518 47358737559232 utils.py:36] Started Jackhmmer (uniref90.fasta) query

I0526 10:34:06.416362 47358737559232 utils.py:40] Finished Jackhmmer (uniref90.fasta) query in 1329.325 seconds
Traceback (most recent call last):
  File "/sw/csg/alphafold/2.2.0/el7.9_python_jupyter/alphafold/run_alphafold.py", line 422, in <module>
    app.run(main)
  File "/sw/csg/alphafold/2.2.0/el7.9_python_jupyter/miniconda3/envs/alphafold_v2.2.0/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/sw/csg/alphafold/2.2.0/el7.9_python_jupyter/miniconda3/envs/alphafold_v2.2.0/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/sw/csg/alphafold/2.2.0/el7.9_python_jupyter/alphafold/run_alphafold.py", line 398, in main
    predict_structure(
  File "/sw/csg/alphafold/2.2.0/el7.9_python_jupyter/alphafold/run_alphafold.py", line 172, in predict_structure
    feature_dict = data_pipeline.process(
  File "/sw/csg/alphafold/2.2.0/el7.9_python_jupyter/alphafold/alphafold/data/pipeline_multimer.py", line 264, in process
    chain_features = self._process_single_chain(
  File "/sw/csg/alphafold/2.2.0/el7.9_python_jupyter/alphafold/alphafold/data/pipeline_multimer.py", line 212, in _process_single_chain
    chain_features = self._monomer_data_pipeline.process(
  File "/sw/csg/alphafold/2.2.0/el7.9_python_jupyter/alphafold/alphafold/data/pipeline.py", line 163, in process
    jackhmmer_uniref90_result = run_msa_tool(
  File "/sw/csg/alphafold/2.2.0/el7.9_python_jupyter/alphafold/alphafold/data/pipeline.py", line 94, in run_msa_tool
    result = msa_runner.query(input_fasta_path, max_sto_sequences)[0]  # pytype: disable=wrong-arg-count
  File "/sw/csg/alphafold/2.2.0/el7.9_python_jupyter/alphafold/alphafold/data/tools/jackhmmer.py", line 171, in query
    single_chunk_result = self._query_chunk(
  File "/sw/csg/alphafold/2.2.0/el7.9_python_jupyter/alphafold/alphafold/data/tools/jackhmmer.py", line 142, in _query_chunk
    raise RuntimeError(
RuntimeError: Jackhmmer failed
stderr:
$
```

### The one passed

The requested node parameter: four A100, 64GB RAM, 32vCPU.

Log:
```
I0526 10:15:50.349001 47566618599104 utils.py:36] Started Jackhmmer (uniref90.fasta) query
I0526 10:23:10.575799 47566618599104 utils.py:40] Finished Jackhmmer (uniref90.fasta) query in 440.226 seconds
I0526 10:23:36.492806 47566618599104 jackhmmer.py:133] Launching subprocess "/sw/csg/alphafold/2.2.0/el7.9_python_jupyter/miniconda3/envs/alphafold_v2.2.0/bin/jackhmmer -o /dev/null -A /tmp/tmp6ao2aae4/output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 /tmp/tmpu5uqvbyz.fasta /ibex/ai/reference/alphafold/2.1.1/all_alphafold_data/mgnify/mgy_clusters_2018_12.fa"
```

**Comment by JingxianFu** [comment]
I have the same problem, did I you fix it?

**Comment by RodenLuo** [comment]
It did not happen often later. So, I did not fix it.

**Comment by JingxianFu** [comment]
已收到，谢谢！
