### ISSUE TITLE
WSL Windows 10 conda environment Issues

### ISSUE THREAD

**Issue by carrellsj** [deepmind/alphafold#486]
I have tried reinstalling everything, setting up a new environment multiple times. I always end up at the same errors.

I0529 14:35:21.879115 139758355961664 run_docker.py:113] Mounting /mnt/b/ALPHAFOLDTEST/alphafold -> /mnt/fasta_path_0
I0529 14:35:21.882387 139758355961664 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/uniref90 -> /mnt/uniref90_database_path
I0529 14:35:21.885341 139758355961664 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/mgnify -> /mnt/mgnify_database_path
I0529 14:35:21.886965 139758355961664 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA -> /mnt/data_dir
I0529 14:35:21.889369 139758355961664 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/pdb_mmcif -> /mnt/template_mmcif_dir
I0529 14:35:21.891610 139758355961664 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0529 14:35:21.893869 139758355961664 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/pdb70 -> /mnt/pdb70_database_path
I0529 14:35:21.896905 139758355961664 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/uniclust30/uniclust30_2018_08 -> /mnt/uniclust30_database_path
I0529 14:35:21.899384 139758355961664 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/bfd -> /mnt/bfd_database_path
I0529 14:35:23.328556 139758355961664 run_docker.py:255] Traceback (most recent call last):
I0529 14:35:23.328725 139758355961664 run_docker.py:255] File "/app/alphafold/run_alphafold.py", line 38, in <module>
I0529 14:35:23.328804 139758355961664 run_docker.py:255] from alphafold.model import model
I0529 14:35:23.328878 139758355961664 run_docker.py:255] File "/app/alphafold/alphafold/model/model.py", line 20, in <module>
I0529 14:35:23.328949 139758355961664 run_docker.py:255] from alphafold.model import features
I0529 14:35:23.329088 139758355961664 run_docker.py:255] File "/app/alphafold/alphafold/model/features.py", line 19, in <module>
I0529 14:35:23.329163 139758355961664 run_docker.py:255] from alphafold.model.tf import input_pipeline
I0529 14:35:23.329234 139758355961664 run_docker.py:255] File "/app/alphafold/alphafold/model/tf/input_pipeline.py", line 17, in <module>
I0529 14:35:23.329307 139758355961664 run_docker.py:255] from alphafold.model.tf import data_transforms
I0529 14:35:23.329380 139758355961664 run_docker.py:255] File "/app/alphafold/alphafold/model/tf/data_transforms.py", line 18, in <module>
I0529 14:35:23.329453 139758355961664 run_docker.py:255] from alphafold.model.tf import shape_helpers
I0529 14:35:23.329526 139758355961664 run_docker.py:255] File "/app/alphafold/alphafold/model/tf/shape_helpers.py", line 16, in <module>
I0529 14:35:23.329598 139758355961664 run_docker.py:255] import tensorflow.compat.v1 as tf
I0529 14:35:23.329670 139758355961664 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/tensorflow/__init__.py", line 41, in <module>
I0529 14:35:23.329741 139758355961664 run_docker.py:255] from tensorflow.python.tools import module_util as _module_util
I0529 14:35:23.329812 139758355961664 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 40, in <module>
I0529 14:35:23.329885 139758355961664 run_docker.py:255] from tensorflow.python.eager import context
I0529 14:35:23.329955 139758355961664 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 32, in <module>
I0529 14:35:23.330038 139758355961664 run_docker.py:255] from tensorflow.core.framework import function_pb2
I0529 14:35:23.330111 139758355961664 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
I0529 14:35:23.330181 139758355961664 run_docker.py:255] from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
I0529 14:35:23.330253 139758355961664 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
I0529 14:35:23.330325 139758355961664 run_docker.py:255] from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
I0529 14:35:23.330396 139758355961664 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
I0529 14:35:23.330467 139758355961664 run_docker.py:255] from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
I0529 14:35:23.330540 139758355961664 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
I0529 14:35:23.330612 139758355961664 run_docker.py:255] from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
I0529 14:35:23.330724 139758355961664 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 42, in <module>
I0529 14:35:23.330796 139758355961664 run_docker.py:255] serialized_options=None, file=DESCRIPTOR),
I0529 14:35:23.330867 139758355961664 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 560, in __new__
I0529 14:35:23.330940 139758355961664 run_docker.py:255] _message.Message._CheckCalledFromGeneratedFile()
I0529 14:35:23.331077 139758355961664 run_docker.py:255] TypeError: Descriptors cannot not be created directly.
I0529 14:35:23.331149 139758355961664 run_docker.py:255] If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
I0529 14:35:23.331220 139758355961664 run_docker.py:255] If you cannot immediately regenerate your protos, some other possible workarounds are:
I0529 14:35:23.331290 139758355961664 run_docker.py:255] 1. Downgrade the protobuf package to 3.20.x or lower.
I0529 14:35:23.331360 139758355961664 run_docker.py:255] 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
I0529 14:35:23.331430 139758355961664 run_docker.py:255]
I0529 14:35:23.331500 139758355961664 run_docker.py:255] More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

I have tried to resolve this by using:

pip3 install --upgrade protobuf==3.20.0

It does nothing. I have all dependencies installed, I have everything updated, I've been through every fix in the issues to no avail. Help!

**Comment by carrellsj** [comment]
Otherwise I run into the following issue, again I've tried every fix, and I always come to either issue...

I0529 14:48:56.834841 140292502947648 run_docker.py:113] Mounting /mnt/b/ALPHAFOLD -> /mnt/fasta_path_0
I0529 14:48:56.838004 140292502947648 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/uniref90 -> /mnt/uniref90_database_path
I0529 14:48:56.840830 140292502947648 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/mgnify -> /mnt/mgnify_database_path
I0529 14:48:56.842459 140292502947648 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA -> /mnt/data_dir
I0529 14:48:56.844868 140292502947648 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/pdb_mmcif -> /mnt/template_mmcif_dir
I0529 14:48:56.848009 140292502947648 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0529 14:48:56.850758 140292502947648 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/pdb70 -> /mnt/pdb70_database_path
I0529 14:48:56.853745 140292502947648 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/uniclust30/uniclust30_2018_08 -> /mnt/uniclust30_database_path
I0529 14:48:56.855993 140292502947648 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/bfd -> /mnt/bfd_database_path
I0529 14:48:57.501621 140292502947648 run_docker.py:255] Traceback (most recent call last):
I0529 14:48:57.501799 140292502947648 run_docker.py:255] File "/app/alphafold/run_alphafold.py", line 29, in <module>
I0529 14:48:57.501874 140292502947648 run_docker.py:255] from alphafold.common import protein
I0529 14:48:57.501943 140292502947648 run_docker.py:255] ImportError: cannot import name 'protein' from 'alphafold.common' (unknown location)

**Comment by carrellsj** [comment]
Not sure which is 'closer' to actually running, but any help would be amazing!

**Comment by carrellsj** [comment]
Now I've managed to get this 'far' 
I0529 15:05:30.020782 139712992151360 run_docker.py:113] Mounting /mnt/b/ALPHAFOLDTEST -> /mnt/fasta_path_0
I0529 15:05:30.023548 139712992151360 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/uniref90 -> /mnt/uniref90_database_path
I0529 15:05:30.026195 139712992151360 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/mgnify -> /mnt/mgnify_database_path
I0529 15:05:30.027773 139712992151360 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA -> /mnt/data_dir
I0529 15:05:30.030064 139712992151360 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/pdb_mmcif -> /mnt/template_mmcif_dir
I0529 15:05:30.032368 139712992151360 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0529 15:05:30.034910 139712992151360 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/pdb70 -> /mnt/pdb70_database_path
I0529 15:05:30.037729 139712992151360 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/uniclust30/uniclust30_2018_08 -> /mnt/uniclust30_database_path
I0529 15:05:30.040165 139712992151360 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/bfd -> /mnt/bfd_database_path
I0529 15:05:32.473541 139712992151360 run_docker.py:255] E0529 22:05:32.472573 139808622303040 templates.py:837] Could not find CIFs in /mnt/template_mmcif_dir/mmcif_files
I0529 15:05:32.474091 139712992151360 run_docker.py:255] Traceback (most recent call last):
I0529 15:05:32.474257 139712992151360 run_docker.py:255] File "/app/alphafold/run_alphafold.py", line 422, in <module>
I0529 15:05:32.474335 139712992151360 run_docker.py:255] app.run(main)
I0529 15:05:32.474409 139712992151360 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
I0529 15:05:32.474484 139712992151360 run_docker.py:255] _run_main(main, args)
I0529 15:05:32.474557 139712992151360 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I0529 15:05:32.474659 139712992151360 run_docker.py:255] sys.exit(main(argv))
I0529 15:05:32.474734 139712992151360 run_docker.py:255] File "/app/alphafold/run_alphafold.py", line 336, in main
I0529 15:05:32.474808 139712992151360 run_docker.py:255] obsolete_pdbs_path=FLAGS.obsolete_pdbs_path)
I0529 15:05:32.474880 139712992151360 run_docker.py:255] File "/app/alphafold/alphafold/data/templates.py", line 838, in __init__
I0529 15:05:32.474952 139712992151360 run_docker.py:255] raise ValueError(f'Could not find CIFs in {self._mmcif_dir}')
I0529 15:05:32.475024 139712992151360 run_docker.py:255] ValueError: Could not find CIFs in /mnt/template_mmcif_dir/mmcif_files
