### ISSUE TITLE
Cannot run AF multimer prediction-- Could not find Jackhmmer database

### ISSUE THREAD

**Issue by busrasavas** [deepmind/alphafold#516]
Hi, 
I got this error when I try to run AF multimer prediction on HPC, it works fine with the monomer prediction. Could you please help me to solve this issue? Thanks in advance.

ValueError: Could not find Jackhmmer database /mnt/uniprot_database_path/uniprot.fasta
Executing: singularity exec --nv --bind /truba/home/bsavas/kdm6a/deneme:/mnt/fasta_path_0:ro,/truba/repo/alphafold-20220608/uniref90:/mnt/uniref90_database_path:ro,/truba/repo/alphafold-20220608/mgnify:/mnt/mgnify_database_path:ro,/truba/repo:/mnt/data_dir:ro,/truba/repo/alphafold-20220608/pdb_mmcif:/mnt/template_mmcif_dir:ro,/truba/repo/alphafold-20220608/pdb_mmcif:/mnt/obsolete_pdbs_path:ro,/truba/repo/alphafold-20220608/uniprot:/mnt/uniprot_database_path:ro,/truba/repo/alphafold-20220608/pdb_seqres:/mnt/pdb_seqres_database_path:ro,/truba/repo/alphafold-20220608/uniclust30/uniclust30_2018_08:/mnt/uniclust30_database_path:ro,/truba/repo/alphafold-20220608/bfd:/mnt/bfd_database_path:ro,/truba/home/bsavas/kdm6a:/mnt/output:rw --env="NVIDIA_VISIBLE_DEVICES=all" --env="TF_FORCE_UNIFIED_MEMORY=1" --env="XLA_PYTHON_CLIENT_MEM_FRACTION=4.0" --env="OPENMM_CPU_THREADS=20" --env="MAX_CPUS=20" docker://catgumag/alphafold:2.2.0 /app/run_alphafold.sh --fasta_paths=/mnt/fasta_path_0/deneme.fasta --uniref90_database_path=/mnt/uniref90_database_path/uniref90.fasta --mgnify_database_path=/mnt/mgnify_database_path/mgy_clusters_2018_12.fa --data_dir=/mnt/data_dir/alphafold-20220608 --template_mmcif_dir=/mnt/template_mmcif_dir/mmcif_files --obsolete_pdbs_path=/mnt/obsolete_pdbs_path/obsolete.dat --uniprot_database_path=/mnt/uniprot_database_path/uniprot.fasta --pdb_seqres_database_path=/mnt/pdb_seqres_database_path/pdb_seqres.txt --uniclust30_database_path=/mnt/uniclust30_database_path/uniclust30_2018_08 --bfd_database_path=/mnt/bfd_database_path/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt --output_dir=/mnt/output/deneme --max_template_date=2022-6-8 --db_preset=full_dbs --model_preset=multimer --benchmark=True --use_precomputed_msas=False --num_multimer_predictions_per_model=5 --run_relax=True --use_gpu_relax=True --logtostderr
Traceback (most recent call last):
  File "alphafold-2.2.0.py", line 283, in <module>
    main()
  File "alphafold-2.2.0.py", line 151, in main
    p.check_returncode()
  File "/truba/sw/centos7.3/lib/anaconda3/2020.07/lib/python3.8/subprocess.py", line 444, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['singularity', 'exec', '--nv', '--bind', '/truba/home/bsavas/kdm6a/deneme:/mnt/fasta_path_0:ro,/truba/repo/alphafold-20220608/uniref90:/mnt/uniref90_database_path:ro,/truba/repo/alphafold-20220608/mgnify:/mnt/mgnify_database_path:ro,/truba/repo:/mnt/data_dir:ro,/truba/repo/alphafold-20220608/pdb_mmcif:/mnt/template_mmcif_dir:ro,/truba/repo/alphafold-20220608/pdb_mmcif:/mnt/obsolete_pdbs_path:ro,/truba/repo/alphafold-20220608/uniprot:/mnt/uniprot_database_path:ro,/truba/repo/alphafold-20220608/pdb_seqres:/mnt/pdb_seqres_database_path:ro,/truba/repo/alphafold-20220608/uniclust30/uniclust30_2018_08:/mnt/uniclust30_database_path:ro,/truba/repo/alphafold-20220608/bfd:/mnt/bfd_database_path:ro,/truba/home/bsavas/kdm6a:/mnt/output:rw', '--env="NVIDIA_VISIBLE_DEVICES=all"', '--env="TF_FORCE_UNIFIED_MEMORY=1"', '--env="XLA_PYTHON_CLIENT_MEM_FRACTION=4.0"', '--env="OPENMM_CPU_THREADS=20"', '--env="MAX_CPUS=20"', 'docker://catgumag/alphafold:2.2.0', '/app/run_alphafold.sh', '--fasta_paths=/mnt/fasta_path_0/deneme.fasta', '--uniref90_database_path=/mnt/uniref90_database_path/uniref90.fasta', '--mgnify_database_path=/mnt/mgnify_database_path/mgy_clusters_2018_12.fa', '--data_dir=/mnt/data_dir/alphafold-20220608', '--template_mmcif_dir=/mnt/template_mmcif_dir/mmcif_files', '--obsolete_pdbs_path=/mnt/obsolete_pdbs_path/obsolete.dat', '--uniprot_database_path=/mnt/uniprot_database_path/uniprot.fasta', '--pdb_seqres_database_path=/mnt/pdb_seqres_database_path/pdb_seqres.txt', '--uniclust30_database_path=/mnt/uniclust30_database_path/uniclust30_2018_08', '--bfd_database_path=/mnt/bfd_database_path/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt', '--output_dir=/mnt/output/deneme', '--max_template_date=2022-6-8', '--db_preset=full_dbs', '--model_preset=multimer', '--benchmark=True', '--use_precomputed_msas=False', '--num_multimer_predictions_per_model=5', '--run_relax=True', '--use_gpu_relax=True', '--logtostderr']' returned non-zero exit status 1.

**Comment by busrasavas** [comment]
Thanks for the really quick response! I'll contact with the HPC administrators and check the uniprot.fasta file is appropriately downloaded
