### ISSUE TITLE
RuntimeError:HHSearch failed at hhsearch.py", line 97 on a freshly built docker image.

### ISSUE THREAD

**Issue by MurphyDavid** [deepmind/alphafold#517]
```

I0624 00:47:45.397181 139668737929600 run_docker.py:113] Mounting /data/hestia/NGS_Software/alphafold -> /mnt/fasta_path_0
I0624 00:47:45.397302 139668737929600 run_docker.py:113] Mounting /data/hestia/Reference/alphafold/uniref90 -> /mnt/uniref90_database_path
I0624 00:47:45.397378 139668737929600 run_docker.py:113] Mounting /data/hestia/Reference/alphafold/mgnify -> /mnt/mgnify_database_path
I0624 00:47:45.397436 139668737929600 run_docker.py:113] Mounting /data/hestia/Reference/alphafold -> /mnt/data_dir
I0624 00:47:45.397495 139668737929600 run_docker.py:113] Mounting /data/hestia/Reference/alphafold/pdb_mmcif/mmcif_files -> /mnt/template_mmcif_dir
I0624 00:47:45.397560 139668737929600 run_docker.py:113] Mounting /data/hestia/Reference/alphafold/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0624 00:47:45.397631 139668737929600 run_docker.py:113] Mounting /data/hestia/Reference/alphafold/pdb70 -> /mnt/pdb70_database_path
I0624 00:47:45.397701 139668737929600 run_docker.py:113] Mounting /data/hestia/Reference/alphafold/small_bfd -> /mnt/small_bfd_database_path
I0624 00:47:50.164538 139668737929600 run_docker.py:255] I0624 00:47:50.163206 139990769694528 templates.py:857] Using precomputed obsolete pdbs /mnt/obsolete_pdbs_path/obsolete.dat.
I0624 00:47:50.379945 139668737929600 run_docker.py:255] I0624 00:47:50.379231 139990769694528 tpu_client.py:54] Starting the local TPU driver.
I0624 00:47:50.380170 139668737929600 run_docker.py:255] I0624 00:47:50.379602 139990769694528 xla_bridge.py:212] Unable to initialize backend 'tpu_driver': Not found: Unable to find driver in registry given worker: local://
I0624 00:47:50.380693 139668737929600 run_docker.py:255] 2022-06-24 00:47:50.379994: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
I0624 00:47:50.381006 139668737929600 run_docker.py:255] 2022-06-24 00:47:50.380023: W external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
I0624 00:47:50.381149 139668737929600 run_docker.py:255] I0624 00:47:50.380112 139990769694528 xla_bridge.py:212] Unable to initialize backend 'gpu': Failed precondition: No visible GPU devices.
I0624 00:47:50.381273 139668737929600 run_docker.py:255] I0624 00:47:50.380228 139990769694528 xla_bridge.py:212] Unable to initialize backend 'tpu': Invalid argument: TpuPlatform is not available.
I0624 00:47:50.381414 139668737929600 run_docker.py:255] W0624 00:47:50.380298 139990769694528 xla_bridge.py:215] No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
I0624 00:47:53.456072 139668737929600 run_docker.py:255] I0624 00:47:53.454855 139990769694528 run_alphafold.py:376] Have 5 models: ['model_1_pred_0', 'model_2_pred_0', 'model_3_pred_0', 'model_4_pred_0', 'model_5_pred_0']
I0624 00:47:53.456364 139668737929600 run_docker.py:255] I0624 00:47:53.455012 139990769694528 run_alphafold.py:393] Using random seed 184853831061044367 for the data pipeline
I0624 00:47:53.456532 139668737929600 run_docker.py:255] I0624 00:47:53.455229 139990769694528 run_alphafold.py:161] Predicting SEPT7
I0624 00:47:53.456666 139668737929600 run_docker.py:255] I0624 00:47:53.455786 139990769694528 jackhmmer.py:133] Launching subprocess "/usr/bin/jackhmmer -o /dev/null -A /tmp/tmp987sf2ug/output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 /mnt/fasta_path_0/SEPT7.fasta /mnt/uniref90_database_path/uniref90.fasta"
I0624 00:47:53.520350 139668737929600 run_docker.py:255] I0624 00:47:53.519232 139990769694528 utils.py:36] Started Jackhmmer (uniref90.fasta) query
I0624 00:57:26.717062 139668737929600 run_docker.py:255] I0624 00:57:26.715703 139990769694528 utils.py:40] Finished Jackhmmer (uniref90.fasta) query in 573.196 seconds
I0624 00:57:27.123824 139668737929600 run_docker.py:255] I0624 00:57:27.122690 139990769694528 jackhmmer.py:133] Launching subprocess "/usr/bin/jackhmmer -o /dev/null -A /tmp/tmpwmdrv_ql/output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 /mnt/fasta_path_0/SEPT7.fasta /mnt/mgnify_database_path/mgy_clusters_2018_12.fa"
I0624 00:57:27.192442 139668737929600 run_docker.py:255] I0624 00:57:27.191420 139990769694528 utils.py:36] Started Jackhmmer (mgy_clusters_2018_12.fa) query
I0624 01:07:21.162689 139668737929600 run_docker.py:255] I0624 01:07:21.161386 139990769694528 utils.py:40] Finished Jackhmmer (mgy_clusters_2018_12.fa) query in 593.970 seconds
I0624 01:07:28.048502 139668737929600 run_docker.py:255] I0624 01:07:28.047280 139990769694528 hhsearch.py:88] Launching subprocess "/usr/bin/hhsearch -i /tmp/tmp632wzj78/query.a3m -o /tmp/tmp632wzj78/output.hhr -maxseq 1000000 -cpu 1 -d /mnt/pdb70_database_path/pdb70"
I0624 01:07:28.115438 139668737929600 run_docker.py:255] I0624 01:07:28.114561 139990769694528 utils.py:36] Started HHsearch query
I0624 01:07:28.290230 139668737929600 run_docker.py:255] I0624 01:07:28.289237 139990769694528 utils.py:40] Finished HHsearch query in 0.174 seconds
I0624 01:07:28.292639 139668737929600 run_docker.py:255] Traceback (most recent call last):
I0624 01:07:28.292860 139668737929600 run_docker.py:255] File "/app/alphafold/run_alphafold.py", line 422, in <module>
I0624 01:07:28.292999 139668737929600 run_docker.py:255] app.run(main)
I0624 01:07:28.293124 139668737929600 run_docker.py:255] File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 312, in run
I0624 01:07:28.293257 139668737929600 run_docker.py:255] _run_main(main, args)
I0624 01:07:28.293388 139668737929600 run_docker.py:255] File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
I0624 01:07:28.293502 139668737929600 run_docker.py:255] sys.exit(main(argv))
I0624 01:07:28.293612 139668737929600 run_docker.py:255] File "/app/alphafold/run_alphafold.py", line 398, in main
I0624 01:07:28.293721 139668737929600 run_docker.py:255] predict_structure(
I0624 01:07:28.293829 139668737929600 run_docker.py:255] File "/app/alphafold/run_alphafold.py", line 172, in predict_structure
I0624 01:07:28.293938 139668737929600 run_docker.py:255] feature_dict = data_pipeline.process(
I0624 01:07:28.294046 139668737929600 run_docker.py:255] File "/app/alphafold/alphafold/data/pipeline.py", line 188, in process
I0624 01:07:28.294166 139668737929600 run_docker.py:255] pdb_templates_result = self.template_searcher.query(uniref90_msa_as_a3m)
I0624 01:07:28.294290 139668737929600 run_docker.py:255] File "/app/alphafold/alphafold/data/tools/hhsearch.py", line 97, in query
I0624 01:07:28.294399 139668737929600 run_docker.py:255] raise RuntimeError(
I0624 01:07:28.294506 139668737929600 run_docker.py:255] RuntimeError: HHSearch failed:
I0624 01:07:28.294612 139668737929600 run_docker.py:255] stdout:
I0624 01:07:28.294718 139668737929600 run_docker.py:255]
I0624 01:07:28.294825 139668737929600 run_docker.py:255]
I0624 01:07:28.294933 139668737929600 run_docker.py:255] stderr:
I0624 01:07:28.295040 139668737929600 run_docker.py:255]
I0624 01:07:28.295148 139668737929600 run_docker.py:255]

```

I thought it might be the same as this issue:

https://github.com/deepmind/alphafold/issues/132

but adding "-DHAVE_AVX2=1 " to the cmake command for hhsuite  in the dockerfile and rebuilding the docker image made no difference to the above error. 

The only other change from the default in my install is the jaxlib path as described here.
https://github.com/deepmind/alphafold/issues/510

Steps to reproduce:
```

git clone https://github.com/deepmind/alphafold.git
[update dockerfile with jaxlib path]
cd alphafold/
bash download_all_data.sh /data/Reference/alphafold/  reduced_dbs
docker build -f docker/Dockerfile -t alphafold .


python3 docker/run_docker.py    \
--fasta_paths=/data/NGS_Software/alphafold/SEPT7.fasta   \ 
--max_template_date=2020-05-14    \
--data_dir=/data/Reference/alphafold/    \
--db_preset=reduced_dbs  \
--output_dir /data/dmurphy/alphaout/  \
--use_gpu=False

```

System:Ubuntu 20.04
Host CPU: AMD EPYC 7713 64-Core Processor

**Comment by MurphyDavid** [comment]
I'm closing this as likely user error or some kind of environment problem.  

After deleting all docker images and reinstalling docker the issue was resolved after adding the

-DHAVE_AVX2=1 

flag and it now continues beyond hhsearch
