### ISSUE TITLE
docker.errors.InvalidVersion: device_requests param is not supported in API versions < 1.40

### ISSUE THREAD

**Issue by pariskang** [deepmind/alphafold#528]
I installed it on another openeuler os machine which is based on arm. But I meet the follwing error. I wondering if there is a correct method to install it on the arm machine. Thank u.
 
```
(base) [root@ecs alphafold]# python3 docker/run_docker.py \
>  --fasta_paths=/root/T1032.fasta \
>  --max_template_date=2020-05-14 \
>  --db_preset=reduced_dbs \
>  --data_dir=/root/alphafold_data
I0707 18:41:43.528490 281460623819376 run_docker.py:113] Mounting /root -> /mnt/fasta_path_0
I0707 18:41:43.528802 281460623819376 run_docker.py:113] Mounting /root/alphafold_data/uniref90 -> /mnt/uniref90_database_path
I0707 18:41:43.528947 281460623819376 run_docker.py:113] Mounting /root/alphafold_data/mgnify -> /mnt/mgnify_database_path
I0707 18:41:43.529061 281460623819376 run_docker.py:113] Mounting /root/alphafold_data -> /mnt/data_dir
I0707 18:41:43.529171 281460623819376 run_docker.py:113] Mounting /root/alphafold_data/pdb_mmcif/mmcif_files -> /mnt/template_mmcif_dir
I0707 18:41:43.529291 281460623819376 run_docker.py:113] Mounting /root/alphafold_data/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0707 18:41:43.529416 281460623819376 run_docker.py:113] Mounting /root/alphafold_data/pdb70 -> /mnt/pdb70_database_path
I0707 18:41:43.529535 281460623819376 run_docker.py:113] Mounting /root/alphafold_data/small_bfd -> /mnt/small_bfd_database_path
Traceback (most recent call last):
  File "/root/alphafold/docker/run_docker.py", line 264, in <module>
    app.run(main)
  File "/root/miniconda3/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/root/miniconda3/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/root/alphafold/docker/run_docker.py", line 234, in main
    container = client.containers.run(
  File "/root/miniconda3/lib/python3.9/site-packages/docker/models/containers.py", line 811, in run
    container = self.create(image=image, command=command,
  File "/root/miniconda3/lib/python3.9/site-packages/docker/models/containers.py", line 869, in create
    create_kwargs = _create_container_args(kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/docker/models/containers.py", line 1087, in _create_container_args
    create_kwargs['host_config'] = HostConfig(**host_config_kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/docker/types/containers.py", line 640, in __init__
    raise host_config_version_error('device_requests', '1.40')
docker.errors.InvalidVersion: device_requests param is not supported in API versions < 1.40

```

**Comment by tomwardio** [comment]
Hi @pariskang,

Unfortunately we don't actively support running Alphfold on ARM machines, but it looks like the version of Docker you have installed is too old. You could try and update to a newer version, but you'll likely run into issues running e.g. TF/JAX or the various tools we depend on. Would be interesting if you were able to get it working!

Thanks
