### ISSUE TITLE
2.2.2 build TLS issues

### ISSUE THREAD

**Issue by MrDotOne** [deepmind/alphafold#577]
Trying to build a recent clone of the repo on our HPC and i am receiving the following error:

cryptography-37.0.2  | 1.5 MB    | ########## | 100%
ocl-icd-system-1.0.0 | 4 KB      | ########## | 100%
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html

done
Retrieving notices: ...working... failed
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/conda/exceptions.py", line 1125, in __call__
  File "/opt/conda/lib/python3.9/site-packages/conda/cli/main.py", line 86, in main_subshell
  File "/opt/conda/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 93, in do_call
  File "/opt/conda/lib/python3.9/site-packages/conda/notices/core.py", line 75, in wrapper
  File "/opt/conda/lib/python3.9/site-packages/conda/notices/core.py", line 39, in display_notices
  File "/opt/conda/lib/python3.9/site-packages/conda/notices/http.py", line 36, in get_notice_responses
  File "/opt/conda/lib/python3.9/site-packages/conda/notices/http.py", line 39, in <genexpr>
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 446, in result
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
  File "/opt/conda/lib/python3.9/concurrent/futures/thread.py", line 58, in run
  File "/opt/conda/lib/python3.9/site-packages/conda/notices/http.py", line 42, in <lambda>
  File "/opt/conda/lib/python3.9/site-packages/conda/notices/cache.py", line 37, in wrapper
  File "/opt/conda/lib/python3.9/site-packages/conda/notices/http.py", line 58, in get_channel_notice_response
  File "/opt/conda/lib/python3.9/site-packages/requests/sessions.py", line 600, in get
  File "/opt/conda/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
  File "/opt/conda/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
  File "/opt/conda/lib/python3.9/site-packages/requests/adapters.py", line 460, in send
  File "/opt/conda/lib/python3.9/site-packages/requests/adapters.py", line 263, in cert_verify
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /opt/conda/lib/python3.9/site-packages/certifi/cacert.pem

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/conda/cli/main.py", line 129, in main
  File "/opt/conda/lib/python3.9/site-packages/conda/exceptions.py", line 1413, in conda_exception_handler
  File "/opt/conda/lib/python3.9/site-packages/conda/exceptions.py", line 1128, in __call__
  File "/opt/conda/lib/python3.9/site-packages/conda/exceptions.py", line 1170, in handle_exception
  File "/opt/conda/lib/python3.9/site-packages/conda/exceptions.py", line 1181, in handle_unexpected_exception
  File "/opt/conda/lib/python3.9/site-packages/conda/exceptions.py", line 1251, in print_unexpected_error_report
ModuleNotFoundError: No module named 'conda.cli.main_info'
The command '/bin/bash -c conda update -qy conda     && conda install -y -c conda-forge       openmm=7.5.1       cudatoolkit==${CUDA_VERSION}       pdbfixer       pip       python=3.7' returned a non-zero code: 1

Has anyone else seen this, and if so, how does one get around it?

Thank you.

**Comment by Augustin-Zidek** [comment]
Sorry about this! See https://github.com/deepmind/alphafold/issues/573 for a workaround, we are working on a fix.

**Comment by Augustin-Zidek** [comment]
Fixed in https://github.com/deepmind/alphafold/commit/dad1f286aeaa158702a98aeee0f5661f30de6da8.
