### ISSUE TITLE
Problem with docker build -f docker/Dockerfile -t alphafold .

### ISSUE THREAD

**Issue by fengsidu** [deepmind/alphafold#613]
The code always reports the following error, I don't know how to solve it
```
The following packages will be UPDATED:

  ca-certificates                      2022.3.29-h06a4308_1 --> 2022.07.19-h06a4308_0
  certifi                          2021.10.8-py39h06a4308_2 --> 2022.9.24-py39h06a4308_0
  conda                               4.12.0-py39h06a4308_0 --> 4.13.0-py39h06a4308_0
  openssl                                 1.1.1n-h7f8727e_0 --> 1.1.1q-h7f8727e_0


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/conda/exceptions.py", line 1082, in __call__
        print(_format_exc(exc_val, exc_tb), file=sys.stderr)
      File "/opt/conda/lib/python3.9/site-packages/conda/cli/main.py", line 87, in _main
        if isinstance(exit_code, int):
      File "/opt/conda/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 84, in do_call
        def do_call(args, parser):
      File "/opt/conda/lib/python3.9/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/opt/conda/lib/python3.9/site-packages/conda/cli/install.py", line 316, in install
        #    of fns.  That way, we fall to the next fn.
      File "/opt/conda/lib/python3.9/site-packages/conda/cli/install.py", line 345, in handle_txn
      File "/opt/conda/lib/python3.9/site-packages/conda/core/link.py", line 281, in execute
        self._execute(tuple(concat(interleave(self.prefix_action_groups.values()))))
      File "/opt/conda/lib/python3.9/site-packages/conda/core/link.py", line 753, in _execute
        action.cleanup()
      File "/opt/conda/lib/python3.9/site-packages/conda/core/path_actions.py", line 1015, in cleanup
        if not isdir(self.holding_full_path):
      File "/opt/conda/lib/python3.9/site-packages/conda/gateways/disk/delete.py", line 179, in rm_rf
        remove_empty_parent_paths(path)
      File "/opt/conda/lib/python3.9/site-packages/conda/gateways/disk/delete.py", line 152, in remove_empty_parent_paths
        rmdir(parent_path)
    OSError: [Errno 22] Invalid argument: '/opt/conda/lib/python3.9/site-packages/conda-4.12.0-py3.9.egg-info'

`$ /opt/conda/bin/conda install -qy conda==4.13.0`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/opt/conda
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
                     PATH=/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sb
                          in:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.12 Linux/3.10.0-327.el7.x86_64 ubuntu/18.04.6 glibc/2.27
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

Upload successful.
The command '/bin/bash -o pipefail -c conda install -qy conda==4.13.0     && conda install -y -c conda-forge       openmm=7.5.1       cudatoolkit==${CUDA_VERSION}       pdbfixer       pip       python=3.7       && conda clean --all --force-pkgs-dirs --yes' returned a non-zero code: 1
```

**Comment by Htomlinson14** [comment]
Hi thanks for the question. I haven't been able to reproduce this error. Are you using the same Dockerfile in the latest version release or have you made some changes?

**Comment by fengsidu** [comment]
> Hi thanks for the question. I haven't been able to reproduce this error. Are you using the same Dockerfile in the latest version release or have you made some changes?

Hello, I did not make any changes to the Dockerfile during the initial installation, and this problem also occurred. This problem also occurred when I added a mirror source to the Dockerfile to speed up the download.

**Comment by hezhiqiang8909** [comment]
> 嗨，谢谢你的问题。我无法重现此错误。您是在最新版本中使用相同的 Dockerfile 还是进行了一些更改？

My machine is in Virginia, the network is very good, the dockerfile file is not modified, and the latest code pulled, the above problem also occurs

**Comment by Htomlinson14** [comment]
Hi thanks for raising. What version of docker are you using and on what type of machine?

**Comment by hezhiqiang8909** [comment]
> 您好，感谢您提出。您使用的是什么版本的 docker 以及在什么类型的机器上？

I'm very sorry, I already know the reason for this error. It is caused by compiling on a machine without a GPU driver. To use the Dockerfile in the docker directory to create a docker image, a machine with a GPU driver needs to be installed.

**Comment by Htomlinson14** [comment]
Hi @hezhiqiang8909 thank you for the update. @fengsidu does your machine have a CUDA driver?
