### ISSUE TITLE
run time eorror

### ISSUE THREAD

**Issue by LAZY118** [deepmind/alphafold#616]
Hello, I try to use the AlphafoldMultimerV2 to predict interactions between baits and candidates in pulldown mode, but every time it showed the same error, could anybody help me to deal with the error issues?

(AlphaPulldown) [LAZY@spgpu ~]$ run_multimer_jobs.py --mode=pulldown --num_cycle=3 --num_predictions_per_model=1 --output_path=/data/projects/pulldown_test/4/pridict_output/short1 --data_dir=/data/alphafold_database/alphafold2-data/ --protein_lists=/data/projects/pulldown_test/4/11.txt,/data/projects/pulldown_test/4/4_shorter.txt --monomer_objects_dir=/data/projects/pulldown_test/4/shorter1
2022-10-26 22:20:22.867691: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
I1026 22:20:24.809013 140194327537472 utils.py:169] checking if output_dir exists /data/projects/pulldown_test/4/pridict_output/short1
I1026 22:20:26.530570 140194327537472 run_multimer_jobs.py:158] done creating multimer b11_and_P00720
I1026 22:20:28.374641 140194327537472 run_multimer_jobs.py:158] done creating multimer b11_and_P00971
I1026 22:20:33.116755 140194327537472 run_multimer_jobs.py:158] done creating multimer b11_and_P04415
I1026 22:20:34.247322 140194327537472 run_multimer_jobs.py:158] done creating multimer b11_and_P04418
I1026 22:20:35.527069 140194327537472 run_multimer_jobs.py:158] done creating multimer b11_and_P04524
I1026 22:20:38.995062 140194327537472 run_multimer_jobs.py:158] done creating multimer b11_and_P07071
I1026 22:20:40.817292 140194327537472 run_multimer_jobs.py:158] done creating multimer b11_and_P12726
I1026 22:20:41.742229 140194327537472 run_multimer_jobs.py:158] done creating multimer b11_and_P13304
I1026 22:20:42.988400 140194327537472 run_multimer_jobs.py:158] done creating multimer b11_and_P13342
I1026 22:20:45.438112 140194327537472 run_multimer_jobs.py:158] done creating multimer b11_and_P16009
I1026 22:20:46.188549 140194327537472 xla_bridge.py:264] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
I1026 22:20:47.116462 140194327537472 xla_bridge.py:264] Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
I1026 22:20:54.713402 140194327537472 run_multimer_jobs.py:236] now running prediction on b11_and_P00720
I1026 22:20:54.713624 140194327537472 predict_structure.py:40] Checking for /data/projects/pulldown_test/4/pridict_output/short1/b11_and_P00720/ranking_debug.json
I1026 22:20:54.714354 140194327537472 predict_structure.py:48] Running model model_1_multimer_v2_pred_0 on b11_and_P00720
I1026 22:20:54.714848 140194327537472 model.py:166] Running predict with shape(feat) = {'aatype': (803,), 'residue_index': (803,), 'seq_length': (), 'msa': (3773, 803), 'num_alignments': (), 'template_aatype': (4, 803), 'template_all_atom_mask': (4, 803, 37), 'template_all_atom_positions': (4, 803, 37, 3), 'asym_id': (803,), 'sym_id': (803,), 'entity_id': (803,), 'deletion_matrix': (3773, 803), 'deletion_mean': (803,), 'all_atom_mask': (803, 37), 'all_atom_positions': (803, 37, 3), 'assembly_num_chains': (), 'entity_mask': (803,), 'num_templates': (), 'cluster_bias_mask': (3773,), 'bert_mask': (3773, 803), 'seq_mask': (803,), 'msa_mask': (3773, 803)}
2022-10-26 22:20:54.951156: E external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:105] You are using ptxas 8.x, but TF requires ptxas 9.x (and strongly prefers >= 11.1).  Compilation of XLA kernels below will likely fail.

You may not need to update CUDA; cherry-picking the ptxas binary is often sufficient.
2022-10-26 22:20:55.158621: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:230] Falling back to the CUDA driver for PTX compilation; ptxas does not support CC 8.6
2022-10-26 22:20:55.158715: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:233] Used ptxas at ptxas
2022-10-26 22:20:55.163476: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:632] failed to get PTX kernel "shift_right_logical_3" from module: CUDA_ERROR_NOT_FOUND: named symbol not found
2022-10-26 22:20:55.163587: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2141] Execution of replica 0 failed: INTERNAL: Could not find the corresponding function
Traceback (most recent call last):
  File "/spshared/apps/miniconda3/envs/AlphaPulldown/bin/run_multimer_jobs.py", line 328, in <module>
    app.run(main)
  File "/spshared/apps/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/spshared/apps/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/spshared/apps/miniconda3/envs/AlphaPulldown/bin/run_multimer_jobs.py", line 324, in main
    predict_multimers(multimers)
  File "/spshared/apps/miniconda3/envs/AlphaPulldown/bin/run_multimer_jobs.py", line 275, in predict_multimers
    random_seed=random_seed,
  File "/spshared/apps/miniconda3/envs/AlphaPulldown/bin/run_multimer_jobs.py", line 249, in predict_individual_jobs
    seqs=multimer_object.input_seqs,
  File "/spshared/apps/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/alphapulldown/predict_structure.py", line 58, in predict
    processed_feature_dict, random_seed=model_random_seed
  File "/spshared/apps/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/alphafold/model/model.py", line 167, in predict
    result = self.apply(self.params, jax.random.PRNGKey(random_seed), feat)
  File "/spshared/apps/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/jax/_src/random.py", line 125, in PRNGKey
    key = prng.seed_with_impl(impl, seed)
  File "/spshared/apps/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/jax/_src/prng.py", line 232, in seed_with_impl
    return PRNGKeyArray(impl, impl.seed(seed))
  File "/spshared/apps/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/jax/_src/prng.py", line 272, in threefry_seed
    lax.shift_right_logical(seed_arr, lax_internal._const(seed_arr, 32)))
  File "/spshared/apps/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/jax/_src/lax/lax.py", line 444, in shift_right_logical
    return shift_right_logical_p.bind(x, y)
  File "/spshared/apps/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/jax/core.py", line 325, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/spshared/apps/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/jax/core.py", line 328, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/spshared/apps/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/jax/core.py", line 678, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/spshared/apps/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/jax/_src/dispatch.py", line 98, in apply_primitive
    return compiled_fun(*args)
  File "/spshared/apps/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/jax/_src/dispatch.py", line 118, in <lambda>
    return lambda *args, **kw: compiled(*args, **kw)[0]
  File "/spshared/apps/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/jax/_src/dispatch.py", line 556, in _execute_compiled
    out_bufs_flat = compiled.execute(input_bufs_flat)
RuntimeError: INTERNAL: Could not find the corresponding function

**Comment by Htomlinson14** [comment]
Hi! This looks like you are using AlphaPullDown, so I would suggest raising this issue on their github. From the stacktrace it looks like you may need to update your CUDA driver. The recommended version for the Alphafold repo is 11.1.1 and we provide a Docker image with a working environment. Thanks!
