### ISSUE TITLE
RuntimeError: hmmsearch failed

### ISSUE THREAD

**Issue by Davidswang** [deepmind/alphafold#680]
I0113 15:37:10.218779 139802328072448 utils.py:36] Started hmmbuild query
I0113 15:37:11.067894 139802328072448 hmmbuild.py:128] hmmbuild stdout:
# hmmbuild :: profile HMM construction from multiple sequence alignments
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# input alignment file:             /tmp/tmpbxli3xzr/query.msa
# output HMM file:                  /tmp/tmpbxli3xzr/output.hmm
# input alignment is asserted as:   protein
# model architecture construction:  hand-specified by RF annotation
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# idx name                  nseq  alen  mlen eff_nseq re/pos description
#---- -------------------- ----- ----- ----- -------- ------ -----------
1     query                 2080  2444   493    11.66  0.590 

# CPU time: 0.83u 0.01s 00:00:00.84 Elapsed: 00:00:00.84

stderr:

I0113 15:37:11.068106 139802328072448 utils.py:40] Finished hmmbuild query in 0.849 seconds
I0113 15:37:11.069508 139802328072448 hmmsearch.py:103] Launching sub-process ['/home/davidwang/anaconda3/envs/AF2/bin/hmmsearch', '--noali', '--cpu', '8', '--F1', '0.1', '--F2', '0.1', '--F3', '0.1', '--incE', '100', '-E', '100', '--domE', '100', '--incdomE', '100', '-A', '/tmp/tmp9634bocj/output.sto', '/tmp/tmp9634bocj/query.hmm', '../database/pdb_seqres/pdb_seqres.txt']
I0113 15:37:11.166798 139802328072448 utils.py:36] Started hmmsearch (pdb_seqres.txt) query
I0113 15:37:22.792661 139802328072448 utils.py:40] Finished hmmsearch (pdb_seqres.txt) query in 11.626 seconds
Traceback (most recent call last):
  File "/home/davidwang/Alphafold/alphafold-main/run_alphafold.py", line 432, in <module>
    app.run(main)
  File "/home/davidwang/anaconda3/envs/AF2/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/davidwang/anaconda3/envs/AF2/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/davidwang/Alphafold/alphafold-main/run_alphafold.py", line 408, in main
    predict_structure(
  File "/home/davidwang/Alphafold/alphafold-main/run_alphafold.py", line 172, in predict_structure
    feature_dict = data_pipeline.process(
  File "/home/davidwang/Alphafold/alphafold-main/alphafold/data/pipeline_multimer.py", line 264, in process
    chain_features = self._process_single_chain(
  File "/home/davidwang/Alphafold/alphafold-main/alphafold/data/pipeline_multimer.py", line 212, in _process_single_chain
    chain_features = self._monomer_data_pipeline.process(
  File "/home/davidwang/Alphafold/alphafold-main/alphafold/data/pipeline.py", line 185, in process
    pdb_templates_result = self.template_searcher.query(msa_for_templates)
  File "/home/davidwang/Alphafold/alphafold-main/alphafold/data/tools/hmmsearch.py", line 79, in query
    return self.query_with_hmm(hmm)
  File "/home/davidwang/Alphafold/alphafold-main/alphafold/data/tools/hmmsearch.py", line 112, in query_with_hmm
    raise RuntimeError(
RuntimeError: hmmsearch failed:
stdout:
# hmmsearch :: search profile(s) against a sequence database
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# query HMM file:                  /tmp/tmp9634bocj/query.hmm
# target sequence database:        ../database/pdb_seqres/pdb_seqres.txt
# MSA of all hits saved to file:   /tmp/tmp9634bocj/output.sto
# show alignments in output:       no
# sequence reporting threshold:    E-value <= 100
# domain reporting threshold:      E-value <= 100
# sequence inclusion threshold:    E-value <= 100
# domain inclusion threshold:      E-value <= 100
# MSV filter P threshold:       <= 0.1
# Vit filter P threshold:       <= 0.1
# Fwd filter P threshold:       <= 0.1
# number of worker threads:        8
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Query:       query  [M=493]

stderr:
Parse failed (sequence file ../database/pdb_seqres/pdb_seqres.txt):
Line 1366886: illegal character 0

**Comment by Augustin-Zidek** [comment]
This has been fixed in the PDB seqres download script in v2.3.0 - there are some sequences that need to be filtered out.

You can do that manually on your existing PDB seqres by running:

```bash
grep --after-context=1 --no-group-separator '>.* mol:protein' pdb_seqres.txt > pdb_seqres_filtered.txt && mv pdb_seqres_filtered.txt pdb_seqres.txt
```

**Comment by Augustin-Zidek** [comment]
Closing this issue for now, feel free to reopen this issue or open a new issue if this is still a problem.
