### ISSUE TITLE
TypeError: Dtype object is not a valid JAX array type.

### ISSUE THREAD

**Issue by Joshsamuel101** [deepmind/alphafold#694]
I'm trying to run the AF2-Multimer model without docker, however, I am not able to generate prediction results due to certain string-like feature objects (e.g. Sequence, domain_name). It looks like it is currently breaking in the `predict()` function in `model.py` here: 

`result = self.apply(self.params, jax.random.PRNGKey(random_seed), feat)`

I am confused where these object features, which are initially created as objects with `make_sequence_features()` function in `pipeline.py`, are converted into a numerical representation for JAX. See below for the full error output:

python3 run_alphafold.py --fasta_paths=multi_sequence_fasta.fasta --output_dir=test_output --use_gpu_relax=True --model_preset=multimer --data_dir='/home/josh/github_repos/alphafold' --no_db_predict=True
I0215 15:49:01.108000 140333781575488 xla_bridge.py:355] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
I0215 15:49:01.108138 140333781575488 xla_bridge.py:355] Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
I0215 15:49:01.108185 140333781575488 xla_bridge.py:355] Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
I0215 15:49:01.108542 140333781575488 xla_bridge.py:355] Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
I0215 15:49:01.108612 140333781575488 xla_bridge.py:355] Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
W0215 15:49:01.108659 140333781575488 xla_bridge.py:362] No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
I0215 15:49:03.409754 140333781575488 run_alphafold.py:497] Have 25 models: ['model_1_multimer_v3_pred_0', 'model_1_multimer_v3_pred_1', 'model_1_multimer_v3_pred_2', 'model_1_multimer_v3_pred_3', 'model_1_multimer_v3_pred_4', 'model_2_multimer_v3_pred_0', 'model_2_multimer_v3_pred_1', 'model_2_multimer_v3_pred_2', 'model_2_multimer_v3_pred_3', 'model_2_multimer_v3_pred_4', 'model_3_multimer_v3_pred_0', 'model_3_multimer_v3_pred_1', 'model_3_multimer_v3_pred_2', 'model_3_multimer_v3_pred_3', 'model_3_multimer_v3_pred_4', 'model_4_multimer_v3_pred_0', 'model_4_multimer_v3_pred_1', 'model_4_multimer_v3_pred_2', 'model_4_multimer_v3_pred_3', 'model_4_multimer_v3_pred_4', 'model_5_multimer_v3_pred_0', 'model_5_multimer_v3_pred_1', 'model_5_multimer_v3_pred_2', 'model_5_multimer_v3_pred_3', 'model_5_multimer_v3_pred_4']
I0215 15:49:03.409890 140333781575488 run_alphafold.py:511] Using random seed 133863477447302851 for the data pipeline
I0215 15:49:03.410050 140333781575488 run_alphafold.py:228] Predicting multi_sequence_fasta
I0215 15:49:03.411233 140333781575488 run_alphafold.py:285] Running model model_1_multimer_v3_pred_0 on multi_sequence_fasta
I0215 15:49:03.411429 140333781575488 model.py:167] Running predict with shape(feat) = {'aatype': (215, 21), 'between_segment_residues': (215,), 'domain_name': (1,), 'residue_index': (215,), 'seq_length': (215,), 'sequence': (1,), 'template_all_atom_positions': (1, 215, 37, 3), 'template_all_atom_masks': (1, 215, 37), 'template_sequence': (1,), 'template_aatype': (1, 215, 22), 'template_confidence_scores': (1, 215), 'template_domain_names': (1,), 'template_release_date': (1,)}
Traceback (most recent call last):
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/dispatch.py", line 616, in _valid_jaxtype
    xla.abstractify(arg)  # faster than core.get_aval
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/interpreters/xla.py", line 267, in abstractify
    if aval_fn: return aval_fn(x)
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/interpreters/xla.py", line 288, in _make_shaped_array_for_numpy_array
    dtypes.check_valid_dtype(dtype)
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/dtypes.py", line 613, in check_valid_dtype
    raise TypeError(f"Dtype {dtype} is not a valid JAX array "
TypeError: Dtype object is not a valid JAX array type. Only arrays of numeric types are supported by JAX.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_alphafold.py", line 541, in <module>
    app.run(main)
  File "/home/josh/.local/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/josh/.local/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "run_alphafold.py", line 516, in main
    predict_structure(
  File "run_alphafold.py", line 297, in predict_structure
    prediction_result = model_runner.predict(processed_feature_dict,
  File "/home/josh/github_repos/alphafold/alphafold/model/model.py", line 171, in predict
    result = self.apply(self.params, jax.random.PRNGKey(random_seed), feat)
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 163, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/api.py", line 676, in cache_miss
    dispatch.check_arg(arg)
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/dispatch.py", line 623, in check_arg
    if not (isinstance(arg, core.Tracer) or _valid_jaxtype(arg)):
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/dispatch.py", line 618, in _valid_jaxtype
    return core.valid_jaxtype(arg)
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/core.py", line 1243, in valid_jaxtype
    concrete_aval(x)
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/core.py", line 1258, in concrete_aval
    if handler: return handler(x)
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/abstract_arrays.py", line 53, in canonical_concrete_aval
    return ConcreteArray(dtypes.canonicalize_dtype(np.result_type(val)), val,
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/core.py", line 1489, in __init__
    assert self.dtype != np.dtype('O'), val
jax._src.traceback_util.UnfilteredStackTrace: AssertionError: [b'hiding_description']

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_alphafold.py", line 541, in <module>
    app.run(main)
  File "/home/josh/.local/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/josh/.local/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "run_alphafold.py", line 516, in main
    predict_structure(
  File "run_alphafold.py", line 297, in predict_structure
    prediction_result = model_runner.predict(processed_feature_dict,
  File "/home/josh/github_repos/alphafold/alphafold/model/model.py", line 171, in predict
    result = self.apply(self.params, jax.random.PRNGKey(random_seed), feat)
AssertionError: [b'hiding_description']

**Comment by KayDiederichs** [comment]
AF does not find your GPU, and the error messages point to jaxlib. If you actually have a Nvidia GPU, I guess you did not install the CUDA version of jaxlib. Try
pip uninstall jaxlib
pip install --upgrade "jax[cuda]>=<jax Version>,<0.4" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
where <jax Version> stands for your current jax version, e.g. 0.3.25
Hope this helps - Kay

**Comment by Joshsamuel101** [comment]
Hi Kay, thanks for your response!

I've uninstalled jaxlib and installed the CUDA version of jaxlib as I do have an NVIDIA GPU. Running the script again has fixed the TypeError, but I now have the following error:

E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:429] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

See below the full error:

```
python3 run_alphafold.py --fasta_paths=multi_sequence_fasta.fasta --output_dir=test_output --use_gpu_relax=True --model_preset=multimer --data_dir='/home/josh/github_repos/alphafold' --no_db_predict=True
I0215 16:32:36.650632 140009814734656 xla_bridge.py:355] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
I0215 16:32:36.768457 140009814734656 xla_bridge.py:355] Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: Host CUDA Interpreter
I0215 16:32:36.768665 140009814734656 xla_bridge.py:355] Unable to initialize backend 'tpu': module 'jaxlib.xla_extension' has no attribute 'get_tpu_client'
I0215 16:32:36.768731 140009814734656 xla_bridge.py:355] Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
I0215 16:32:39.209744 140009814734656 run_alphafold.py:497] Have 25 models: ['model_1_multimer_v3_pred_0', 'model_1_multimer_v3_pred_1', 'model_1_multimer_v3_pred_2', 'model_1_multimer_v3_pred_3', 'model_1_multimer_v3_pred_4', 'model_2_multimer_v3_pred_0', 'model_2_multimer_v3_pred_1', 'model_2_multimer_v3_pred_2', 'model_2_multimer_v3_pred_3', 'model_2_multimer_v3_pred_4', 'model_3_multimer_v3_pred_0', 'model_3_multimer_v3_pred_1', 'model_3_multimer_v3_pred_2', 'model_3_multimer_v3_pred_3', 'model_3_multimer_v3_pred_4', 'model_4_multimer_v3_pred_0', 'model_4_multimer_v3_pred_1', 'model_4_multimer_v3_pred_2', 'model_4_multimer_v3_pred_3', 'model_4_multimer_v3_pred_4', 'model_5_multimer_v3_pred_0', 'model_5_multimer_v3_pred_1', 'model_5_multimer_v3_pred_2', 'model_5_multimer_v3_pred_3', 'model_5_multimer_v3_pred_4']
I0215 16:32:39.209875 140009814734656 run_alphafold.py:511] Using random seed 312124108456027963 for the data pipeline
I0215 16:32:39.210032 140009814734656 run_alphafold.py:228] Predicting multi_sequence_fasta
I0215 16:32:39.211248 140009814734656 run_alphafold.py:285] Running model model_1_multimer_v3_pred_0 on multi_sequence_fasta
I0215 16:32:39.211434 140009814734656 model.py:167] Running predict with shape(feat) = {'aatype': (215, 21), 'between_segment_residues': (215,), 'domain_name': (1,), 'residue_index': (215,), 'seq_length': (215,), 'sequence': (1,), 'template_all_atom_positions': (1, 215, 37, 3), 'template_all_atom_masks': (1, 215, 37), 'template_sequence': (1,), 'template_aatype': (1, 215, 22), 'template_confidence_scores': (1, 215), 'template_domain_names': (1,), 'template_release_date': (1,)}
2023-02-15 16:32:39.217007: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:429] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2023-02-15 16:32:39.217601: E external/org_tensorflow/tensorflow/compiler/xla/status_macros.cc:57] INTERNAL: RET_CHECK failure (external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:626) dnn != nullptr 
*** Begin stack trace ***
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	PyCFunction_Call
	_PyObject_MakeTpCall
	
	
	_PyFunction_Vectorcall
	PyVectorcall_Call
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	
	_PyFunction_Vectorcall
	
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	PyVectorcall_Call
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	
	_PyEval_EvalCodeWithName
	
	
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	PyVectorcall_Call
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	PyVectorcall_Call
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	PyVectorcall_Call
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	PyVectorcall_Call
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	_PyObject_FastCallDict
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	
	_PyFunction_Vectorcall
	
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	
	_PyFunction_Vectorcall
	
	_PyFunction_Vectorcall
	
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	PyVectorcall_Call
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	
	_PyFunction_Vectorcall
	
	_PyEval_EvalCodeWithName
	
	
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	
	_PyFunction_Vectorcall
	
	_PyFunction_Vectorcall
	
	_PyEval_EvalCodeWithName
	
	
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	
	_PyFunction_Vectorcall
	
	_PyFunction_Vectorcall
	
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	
	_PyEval_EvalCodeWithName
	PyEval_EvalCodeEx
	PyEval_EvalCode
	
	
	PyRun_FileExFlags
	PyRun_SimpleFileExFlags
	Py_RunMain
	Py_BytesMain
	__libc_start_main
	
*** End stack trace ***

Traceback (most recent call last):
  File "run_alphafold.py", line 541, in <module>
    app.run(main)
  File "/home/josh/.local/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/josh/.local/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "run_alphafold.py", line 516, in main
    predict_structure(
  File "run_alphafold.py", line 297, in predict_structure
    prediction_result = model_runner.predict(processed_feature_dict,
  File "/home/josh/github_repos/alphafold/alphafold/model/model.py", line 171, in predict
    result = self.apply(self.params, jax.random.PRNGKey(random_seed), feat)
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/random.py", line 136, in PRNGKey
    key = prng.seed_with_impl(impl, seed)
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/prng.py", line 267, in seed_with_impl
    return random_seed(seed, impl=impl)
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/prng.py", line 570, in random_seed
    return random_seed_p.bind(seeds_arr, impl=impl)
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/core.py", line 343, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/core.py", line 346, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/core.py", line 728, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/prng.py", line 582, in random_seed_impl
    base_arr = random_seed_impl_base(seeds, impl=impl)
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/prng.py", line 587, in random_seed_impl_base
    return seed(seeds)
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/prng.py", line 822, in threefry_seed
    lax.shift_right_logical(seed, lax_internal._const(seed, 32)))
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/lax/lax.py", line 511, in shift_right_logical
    return shift_right_logical_p.bind(x, y)
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/core.py", line 343, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/core.py", line 346, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/core.py", line 728, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/dispatch.py", line 122, in apply_primitive
    compiled_fun = xla_primitive_callable(prim, *unsafe_map(arg_spec, args),
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/util.py", line 253, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/util.py", line 246, in cached
    return f(*args, **kwargs)
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/dispatch.py", line 201, in xla_primitive_callable
    compiled = _xla_callable_uncached(lu.wrap_init(prim_fun), device, None,
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/dispatch.py", line 354, in _xla_callable_uncached
    return computation.compile(_allow_propagation_to_outputs=allow_prop).unsafe_call
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 3203, in compile
    executable = self._compile_unloaded(
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 3174, in _compile_unloaded
    return UnloadedMeshExecutable.from_hlo(
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 3456, in from_hlo
    xla_executable = dispatch.compile_or_get_cached(
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/dispatch.py", line 1081, in compile_or_get_cached
    return backend_compile(backend, serialized_computation, compile_options,
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/josh/miniconda3/envs/af2/lib/python3.8/site-packages/jax/_src/dispatch.py", line 1026, in backend_compile
    return backend.compile(built_c, compile_options=options)
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: RET_CHECK failure (external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:626) dnn != nullptr
```

**Comment by KayDiederichs** [comment]
I'd like to see the output of
pip list | egrep 'absl-py|biopython|chex|dm-haiku|dm-tree|docker|immutabledict|jax|ml-collections|numpy|pandas|protobuf|scipy|tensorflow-cpu'
(modify such that it matches the packages in requirements.txt) .
For me, this returns
absl-py                      1.0.0
biopython                    1.79
chex                         0.0.7
dm-haiku                     0.0.10.dev0
dm-tree                      0.1.6
immutabledict                2.0.0
jax                          0.3.25
jaxlib                       0.3.25+cuda11.cudnn82
ml-collections               0.1.0
numpy                        1.22.4
pandas                       1.3.5
protobuf                     3.20.1
scipy                        1.7.0
tensorflow-cpu               2.9.0

Which CUDA did you install,  and which GPU do you have, and which AlphaFold version is installed?

By the way, this. editor seems to eat strings between acute brackets, so what I wrote above was garbled - it had "jax version" between acute brackets in two places (ah I see now that the acute brackets should be around code). But I think you got the ideas.
