### ISSUE TITLE
v2.3.1 generates errors for multimer

### ISSUE THREAD

**Issue by nmrworker** [deepmind/alphafold#713]
v2.3.1 runs ok with monomer, and same complex ran fine in v2.2.0. Thanks in advance for any help.

I0307 13:49:31.936174 140117654611776 run_docker.py:258] Traceback (most recent call last):
I0307 13:49:31.936233 140117654611776 run_docker.py:258] File "/app/alphafold/run_alphafold.py", line 468, in <module>
I0307 13:49:31.936311 140117654611776 run_docker.py:258] app.run(main)
I0307 13:49:31.936362 140117654611776 run_docker.py:258] File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 312, in run
I0307 13:49:31.936411 140117654611776 run_docker.py:258] _run_main(main, args)
I0307 13:49:31.936461 140117654611776 run_docker.py:258] File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
I0307 13:49:31.936508 140117654611776 run_docker.py:258] sys.exit(main(argv))
I0307 13:49:31.936554 140117654611776 run_docker.py:258] File "/app/alphafold/run_alphafold.py", line 443, in main
I0307 13:49:31.936602 140117654611776 run_docker.py:258] predict_structure(
I0307 13:49:31.936650 140117654611776 run_docker.py:258] File "/app/alphafold/run_alphafold.py", line 196, in predict_structure
I0307 13:49:31.936697 140117654611776 run_docker.py:258] feature_dict = data_pipeline.process(
I0307 13:49:31.936744 140117654611776 run_docker.py:258] File "/app/alphafold/alphafold/data/pipeline_multimer.py", line 264, in process
I0307 13:49:31.936791 140117654611776 run_docker.py:258] chain_features = self._process_single_chain(
I0307 13:49:31.936838 140117654611776 run_docker.py:258] File "/app/alphafold/alphafold/data/pipeline_multimer.py", line 212, in _process_single_chain
I0307 13:49:31.936885 140117654611776 run_docker.py:258] chain_features = self._monomer_data_pipeline.process(
I0307 13:49:31.936933 140117654611776 run_docker.py:258] File "/app/alphafold/alphafold/data/pipeline.py", line 185, in process
I0307 13:49:31.936989 140117654611776 run_docker.py:258] pdb_templates_result = self.template_searcher.query(msa_for_templates)
I0307 13:49:31.937038 140117654611776 run_docker.py:258] File "/app/alphafold/alphafold/data/tools/hmmsearch.py", line 79, in query
I0307 13:49:31.937087 140117654611776 run_docker.py:258] return self.query_with_hmm(hmm)
I0307 13:49:31.937134 140117654611776 run_docker.py:258] File "/app/alphafold/alphafold/data/tools/hmmsearch.py", line 112, in query_with_hmm
I0307 13:49:31.937181 140117654611776 run_docker.py:258] raise RuntimeError(
I0307 13:49:31.937229 140117654611776 run_docker.py:258] RuntimeError: hmmsearch failed:
I0307 13:49:31.937277 140117654611776 run_docker.py:258] stdout:
I0307 13:49:31.937325 140117654611776 run_docker.py:258] # hmmsearch :: search profile(s) against a sequence database
I0307 13:49:31.937371 140117654611776 run_docker.py:258] # HMMER 3.1b2 (February 2015); http://hmmer.org/
I0307 13:49:31.937417 140117654611776 run_docker.py:258] # Copyright (C) 2015 Howard Hughes Medical Institute.
I0307 13:49:31.937464 140117654611776 run_docker.py:258] # Freely distributed under the GNU General Public License (GPLv3).
I0307 13:49:31.937512 140117654611776 run_docker.py:258] # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
I0307 13:49:31.937559 140117654611776 run_docker.py:258] # query HMM file:                  /tmp/tmpmvi828ro/query.hmm
I0307 13:49:31.937606 140117654611776 run_docker.py:258] # target sequence database:        /mnt/pdb_seqres_database_path/pdb_seqres.txt
I0307 13:49:31.937654 140117654611776 run_docker.py:258] # MSA of all hits saved to file:   /tmp/tmpmvi828ro/output.sto
I0307 13:49:31.937700 140117654611776 run_docker.py:258] # show alignments in output:       no
I0307 13:49:31.937747 140117654611776 run_docker.py:258] # sequence reporting threshold:    E-value <= 100
I0307 13:49:31.937793 140117654611776 run_docker.py:258] # domain reporting threshold:      E-value <= 100
I0307 13:49:31.937840 140117654611776 run_docker.py:258] # sequence inclusion threshold:    E-value <= 100
I0307 13:49:31.937888 140117654611776 run_docker.py:258] # domain inclusion threshold:      E-value <= 100
I0307 13:49:31.937935 140117654611776 run_docker.py:258] # MSV filter P threshold:       <= 0.1
I0307 13:49:31.937987 140117654611776 run_docker.py:258] # Vit filter P threshold:       <= 0.1
I0307 13:49:31.938035 140117654611776 run_docker.py:258] # Fwd filter P threshold:       <= 0.1
I0307 13:49:31.938083 140117654611776 run_docker.py:258] # number of worker threads:        8
I0307 13:49:31.938131 140117654611776 run_docker.py:258] # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
I0307 13:49:31.938179 140117654611776 run_docker.py:258] 
I0307 13:49:31.938225 140117654611776 run_docker.py:258] Query:       query  [M=280]
I0307 13:49:31.938272 140117654611776 run_docker.py:258] 
I0307 13:49:31.938319 140117654611776 run_docker.py:258] 
I0307 13:49:31.938365 140117654611776 run_docker.py:258] stderr:
I0307 13:49:31.938413 140117654611776 run_docker.py:258] Parse failed (sequence file /mnt/pdb_seqres_database_path/pdb_seqres.txt):
I0307 13:49:31.938460 140117654611776 run_docker.py:258] Line 1366902: illegal character 0
I0307 13:49:31.938515 140117654611776 run_docker.py:258]

**Comment by Laurent-ipbs** [comment]
Hi,
it seems that the sequence file sequence file /mnt/pdb_seqres_database_path/pdb_seqres.txt contains 5 or 6 sequences with the character 0 in them. As these are DNA or RNA sequences, it's likely that there are of no use to alphafold... Just replace the offending "0" character with C for instance, and it will work.
I have no idea why DNA / RNA sequences are present in this file.

**Comment by DininduSenanayake** [comment]
I was under the assumption this is fixed in latest download_db script https://github.com/deepmind/alphafold/blob/main/scripts/download_pdb_seqres.sh  as the last few lines of corresponding file is 
```
# Keep only protein sequences.
grep --after-context=1 --no-group-separator '>.* mol:protein' "${ROOT_DIR}/pdb_seqres.txt" > "${ROOT_DIR}/pdb_seqres_filtered.txt"
mv "${ROOT_DIR}/pdb_seqres_filtered.txt" "${ROOT_DIR}/pdb_seqres.txt"
```

**Comment by yamule** [comment]
I think pdb_seqres.txt doesn't have sequences with "0" in the latest version.
But removing DNA and RNA in advance is a reasonable procedure, of course.
