### ISSUE TITLE
Image Not found, pull access denied

### ISSUE THREAD

**Issue by mbassalbioinformatics** [deepmind/alphafold#725]
Same problem here

```
I0318 15:37:57.281701 140650922673984 run_docker.py:116] Mounting /mnt/md16/Dropbox/AAAA_WORKING/alphafold_predictions -> /mnt/fasta_path_0
I0318 15:37:57.322554 140650922673984 run_docker.py:116] Mounting /mnt/md18/alphafold_data/uniref90 -> /mnt/uniref90_database_path
I0318 15:37:57.325361 140650922673984 run_docker.py:116] Mounting /mnt/md18/alphafold_data/mgnify -> /mnt/mgnify_database_path
I0318 15:37:57.325487 140650922673984 run_docker.py:116] Mounting /mnt/md18/alphafold_data -> /mnt/data_dir
I0318 15:37:57.333701 140650922673984 run_docker.py:116] Mounting /mnt/md18/alphafold_data/pdb_mmcif/mmcif_files -> /mnt/template_mmcif_dir
I0318 15:37:57.333879 140650922673984 run_docker.py:116] Mounting /mnt/md18/alphafold_data/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0318 15:37:57.342173 140650922673984 run_docker.py:116] Mounting /mnt/md18/alphafold_data/pdb70 -> /mnt/pdb70_database_path
I0318 15:37:57.350134 140650922673984 run_docker.py:116] Mounting /mnt/md18/alphafold_data/uniref30 -> /mnt/uniref30_database_path
I0318 15:37:57.358787 140650922673984 run_docker.py:116] Mounting /mnt/md18/alphafold_data/bfd -> /mnt/bfd_database_path
Traceback (most recent call last):
  File "/home/mbassal/anaconda3/lib/python3.9/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/mbassal/anaconda3/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.42/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mbassal/anaconda3/lib/python3.9/site-packages/docker/models/containers.py", line 811, in run
    container = self.create(image=image, command=command,
  File "/home/mbassal/anaconda3/lib/python3.9/site-packages/docker/models/containers.py", line 870, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/home/mbassal/anaconda3/lib/python3.9/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/home/mbassal/anaconda3/lib/python3.9/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/home/mbassal/anaconda3/lib/python3.9/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/mbassal/anaconda3/lib/python3.9/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/mbassal/anaconda3/lib/python3.9/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.42/containers/create: Not Found ("No such image: alphafold:latest")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mbassal/anaconda3/lib/python3.9/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/mbassal/anaconda3/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.42/images/create?tag=latest&fromImage=alphafold

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mbassal/tools/alphafold/./docker/run_docker.py", line 267, in <module>
    app.run(main)
  File "/home/mbassal/anaconda3/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/mbassal/anaconda3/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/mbassal/tools/alphafold/./docker/run_docker.py", line 237, in main
    container = client.containers.run(
  File "/home/mbassal/anaconda3/lib/python3.9/site-packages/docker/models/containers.py", line 814, in run
    self.client.images.pull(image, platform=platform)
  File "/home/mbassal/anaconda3/lib/python3.9/site-packages/docker/models/images.py", line 446, in pull
    pull_log = self.client.api.pull(
  File "/home/mbassal/anaconda3/lib/python3.9/site-packages/docker/api/image.py", line 430, in pull
    self._raise_for_status(response)
  File "/home/mbassal/anaconda3/lib/python3.9/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/mbassal/anaconda3/lib/python3.9/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.42/images/create?tag=latest&fromImage=alphafold: Not Found ("pull access denied for alphafold, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")
```

output of 
```
docker images
````

```
REPOSITORY    TAG                       IMAGE ID       CREATED          SIZE
alphafold     latest                    1104503218f3   19 minutes ago   7.78GB
nvidia/cuda   12.1.0-base-ubuntu22.04   2f9bc027c2fb   10 days ago      238MB
nginx         latest                    904b8cb13b93   2 weeks ago      142MB
ubuntu        latest                    74f2314a03de   2 weeks ago      77.8MB
hello-world   latest                    feb5d9fea6a5   18 months ago    13.3kB
```

and i built the docker image using 
```
docker build -f docker/Dockerfile -t alphafold .
```

To the best of my knowledge i have also setup docker in rootless mode as well... so kinda stumped whats going on atm... help plz? 
I have tried the fixes in previous issues ato no avail unfortunately. Unless ive missed something...

**Comment by AnthonyShea1** [comment]
Did you find a fix? running into the same issue

**Comment by mbassalbioinformatics** [comment]
> Did you find a fix? running into the same issue

I ended up using this fix instead <https://github.com/google-deepmind/alphafold/issues/727>
