### ISSUE TITLE
no module named openmm

### ISSUE THREAD

**Issue by DrJesseHansen** [deepmind/alphafold#737]
Hello,

We are running Alphafold 2.3.1 on a Linux HPC through SLURM submission.  The databases were downloaded to our cluster for AF2 to run correctly.  We were able to successfully run 2.2.4, but with 2.3.1 we are now receiving the error below.  

We usually aim to submit to the GPU with the most memory, specs: Nvidia A40 (8 GPUs per node) with AMD EPYC 7452 32-core processor, 128 threads, 64 cores, 1024 RAM.  However we have tried submitting to other GPUs and same issue.

I have tried adding loading different modules of openmm (e.g. openmm/7.5.1) with the job submission script but that does not change anything.

Any input would be appreciated!   Thank you.

**Job submission script:**
```
#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=200GB

#SBATCH --time=48:00:00
#SBATCH --no-requeue

#SBATCH --partition=gpu
#SBATCH --gres=gpu:1


MY_PROTEIN_PATH=/(fullpath)/sequence.fasta

echo $HOSTNAME

module purge
module load alphafold/2.3.1

export OPENMM_CUDA_COMPILER=$(which nvcc)
export TF_FORCE_UNIFIED_MEMORY=1
export XLA_PYTHON_CLIENT_MEM_FRACTION="4.0"

python3 /mnt/nfs/clustersw/Debian/bullseye/cuda/11.2/alphafold/2.3.1/alphafold-2.3.1/run_alphafold.py \
	--model_preset=multimer \
	--fasta_paths=$MY_PROTEIN_PATH \
	--output_dir=$(dirname $MY_PROTEIN_PATH) \
	--data_dir=/nfs/scistore14/rcsb/alphafold.databases/ \
	--mgnify_database_path=/nfs/scistore14/rcsb/alphafold.databases/mgnify/mgy_clusters_2022_05.fa \
	--template_mmcif_dir=/nfs/scistore14/rcsb/alphafold.databases.v2/pdb_mmcif/mmcif_files/ \
	--max_template_date=2023-05-14 \
	--obsolete_pdbs_path=/nfs/scistore14/rcsb/alphafold.databases.v2/pdb_mmcif/obsolete.dat \
	--use_gpu_relax=true \
	--bfd_database_path=/nfs/scistore14/rcsb/alphafold.databases/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt \
        --uniref30_database_path=/nfs/scistore14/rcsb/alphafold.databases/uniref30/UniRef30_2021_03 \
	--uniref90_database_path=/nfs/scistore14/rcsb/alphafold.databases/uniref90/uniref90.fasta \
	--pdb_seqres_database_path=/nfs/scistore14/rcsb/alphafold.databases/pdb_seqres/pdb_seqres.txt \
	--uniprot_database_path=/nfs/scistore14/rcsb/alphafold.databases/uniprot/uniprot.fasta

```

**SLURM job output:**
```
Usage:
	python
/mnt/nfs/clustersw/Debian/bullseye/cuda/11.2/alphafold/2.3.1/alphafold-2.3.1/run_alphafold.py
--help
	python
/mnt/nfs/clustersw/Debian/bullseye/cuda/11.2/alphafold/2.3.1/alphafold-2.3.1/run_alphafold.py
--data_dir=/nfs/scistore14/rcsb/alphafold.databases/ ...	
	 
Traceback (most recent call last):
  File "/mnt/nfs/clustersw/Debian/bullseye/cuda/11.2/alphafold/2.3.1/alphafold-2.3.1/run_alphafold.py", line 39, in <module>
    from alphafold.relax import relax
  File "/nfs/scistore07/clustersw/debian/bullseye/cuda11.2/alphafold/2.3.1/alphafold-2.3.1/alphafold/relax/relax.py", line 18, in <module>
    from alphafold.relax import amber_minimize
  File "/nfs/scistore07/clustersw/debian/bullseye/cuda11.2/alphafold/2.3.1/alphafold-2.3.1/alphafold/relax/amber_minimize.py", line 25, in <module>
    from alphafold.relax import cleanup
  File "/nfs/scistore07/clustersw/debian/bullseye/cuda11.2/alphafold/2.3.1/alphafold-2.3.1/alphafold/relax/cleanup.py", line 22, in <module>
    import pdbfixer
  File "/mnt/nfs/clustersw/Debian/bullseye/cuda/11.2/alphafold/2.3.1/lib/python3.9/site-packages/pdbfixer-1.8.1-py3.9.egg/pdbfixer/__init__.py", line 2, in <module>
    from .pdbfixer import PDBFixer
  File "/mnt/nfs/clustersw/Debian/bullseye/cuda/11.2/alphafold/2.3.1/lib/python3.9/site-packages/pdbfixer-1.8.1-py3.9.egg/pdbfixer/pdbfixer.py", line 35, in <module>
    import openmm as mm
ModuleNotFoundError: No module named 'openmm'

```

**Comment by smturzo** [comment]
Wondering if you have already tried creating conda/virtual environment and installing openmm?
something like this: conda install -c conda-forge openmm
Link to installation for openmm below:
https://anaconda.org/conda-forge/openmm

**Comment by ichxw** [comment]
Have you solved this issue? 

Got the same issue here with openmm 7.5.1. After upgrading to openmm 8, it will throw out another error: 
ModuleNotFoundError: No module named 'simtk.openmm.app.internal.

**Comment by mainguyenanhvu** [comment]
@ichxw The authors did not support internal. Thus, there is only one way to import simtk.openmm.app.internal is using version 7.5.1.
Or using openmm.app.internal

Ref: https://github.com/google-deepmind/alphafold/issues/175#issuecomment-921866277
Ref: https://github.com/google-deepmind/alphafold/issues/410

**Comment by mainguyenanhvu** [comment]
I faced the error:
```
/python3.9/site-packages/openmmtools/utils/equilibration.py", line 6, in <module>
    from openmm import unit, OpenMMException
ModuleNotFoundError: No module named 'openmm'
```

When installing `conda -c conda-forge openmm=7.5.1`.  I double check with `conda list`:
```
opencl-headers            2024.10.24           h5888daf_0    conda-forge
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openmm                    7.5.1            py39h71eca04_1    conda-forge
openmmtools               0.24.0             pyhff2d567_0    conda-forge
openmoltools              0.8.8              pyhd8ed1ab_1    conda-forge
```

Please help me to solve it. Thank you very much.
