### ISSUE TITLE
Out of GPU memory on A100 80GB

### ISSUE THREAD

**Issue by hypothalamus01** [deepmind/alphafold#740]
https://www.rbvi.ucsf.edu/chimerax/data/alphafold-jan2022/afspeed.html

I was trying to predict a 3200 a.a. protein on our cluster with 2 A100 80GB GPU. Base on the page above, 48 GB seems sufficient for my protein length. However, I keep getting the out of GPU memory error as below. Can anyone help me with this?

2023-04-02 10:20:17.390936: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2040] Execution of replica 0 failed: Resource exhausted: Out of memory while trying to allocate 64793134928 bytes.
Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 422, in <module>
    app.run(main)
  File "/opt/alphafoldenv/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/alphafoldenv/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/app/alphafold/run_alphafold.py", line 398, in main
    predict_structure(
  File "/app/alphafold/run_alphafold.py", line 198, in predict_structure
    prediction_result = model_runner.predict(processed_feature_dict,
  File "/app/alphafold/alphafold/model/model.py", line 167, in predict
    result = self.apply(self.params, jax.random.PRNGKey(random_seed), feat)
  File "/opt/alphafoldenv/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 183, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/opt/alphafoldenv/lib/python3.8/site-packages/jax/_src/api.py", line 424, in cache_miss
    out_flat = xla.xla_call(
  File "/opt/alphafoldenv/lib/python3.8/site-packages/jax/core.py", line 1560, in bind
    return call_bind(self, fun, *args, **params)
  File "/opt/alphafoldenv/lib/python3.8/site-packages/jax/core.py", line 1551, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/opt/alphafoldenv/lib/python3.8/site-packages/jax/core.py", line 1563, in process
    return trace.process_call(self, fun, tracers, params)
  File "/opt/alphafoldenv/lib/python3.8/site-packages/jax/core.py", line 606, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/opt/alphafoldenv/lib/python3.8/site-packages/jax/interpreters/xla.py", line 595, in _xla_call_impl
    return compiled_fun(*args)
  File "/opt/alphafoldenv/lib/python3.8/site-packages/jax/interpreters/xla.py", line 893, in _execute_compiled
    out_bufs = compiled.execute(input_bufs)
jax._src.traceback_util.UnfilteredStackTrace: RuntimeError: Resource exhausted: Out of memory while trying to allocate 64793134928 bytes.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 422, in <module>
    app.run(main)
  File "/opt/alphafoldenv/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/alphafoldenv/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/app/alphafold/run_alphafold.py", line 398, in main
    predict_structure(
  File "/app/alphafold/run_alphafold.py", line 198, in predict_structure
    prediction_result = model_runner.predict(processed_feature_dict,
  File "/app/alphafold/alphafold/model/model.py", line 167, in predict
    result = self.apply(self.params, jax.random.PRNGKey(random_seed), feat)
  File "/opt/alphafoldenv/lib/python3.8/site-packages/jax/interpreters/xla.py", line 893, in _execute_compiled
    out_bufs = compiled.execute(input_bufs)
RuntimeError: Resource exhausted: Out of memory while trying to allocate 64793134928 bytes.

**Comment by smturzo** [comment]
I have faced similar issues before. In my cluster, i set up my slurm script like this. If you have a slurm environment this maybe worth trying:
#SBATCH --nodes=1
#SBATCH --ntasks=48
#SBATCH --gpus-per-node=2
#SBATCH --gpu_cmode=shared

export TF_FORCE_UNIFIED_MEMORY=${TF_FORCE_UNIFIED_MEMORY:-0}
export XLA_PYTHON_CLIENT_MEM_FRACTION=${XLA_PYTHON_CLIENT_MEM_FRACTION:-4.0}

**Comment by hypothalamus01** [comment]
> I have faced similar issues before. In my cluster, i set up my slurm script like this. If you have a slurm environment this maybe worth trying: #SBATCH --nodes=1 #SBATCH --ntasks=48 #SBATCH --gpus-per-node=2 #SBATCH --gpu_cmode=shared
> 
> export TF_FORCE_UNIFIED_MEMORY=${TF_FORCE_UNIFIED_MEMORY:-0} export XLA_PYTHON_CLIENT_MEM_FRACTION=${XLA_PYTHON_CLIENT_MEM_FRACTION:-4.0}

"--gpu_cmode=shared" does not work for our cluster. Below are the options we have. Could you suggest me how to set it?

GPU scheduling options:
      --cpus-per-gpu=n        number of CPUs required per allocated GPU
  -G, --gpus=n                count of GPUs required for the job
      --gpu-bind=...          task to gpu binding options
      --gpu-freq=...          frequency and voltage of GPUs
      --gpus-per-node=n       number of GPUs required per allocated node
      --gpus-per-socket=n     number of GPUs required per allocated socket
      --gpus-per-task=n       number of GPUs required per spawned task
      --mem-per-gpu=n         real memory required per allocated GPU

**Comment by smturzo** [comment]
have tried playing around with these two environment variables in your slurm script before just before running the run_alphafold.py [...] [...] ... ... [...] ?

As for slurm script this maybe a question you want to ask your cluster manager/help desk as they might be able to provide you more help with the job is running out of memory.

```
export TF_FORCE_UNIFIED_MEMORY=${TF_FORCE_UNIFIED_MEMORY:-0}
export XLA_PYTHON_CLIENT_MEM_FRACTION=${XLA_PYTHON_CLIENT_MEM_FRACTION:-4.0}

```
Explanation below:
TF_FORCE_UNIFIED_MEMORY: This environment variable is used to enable or disable the TensorFlow's Unified Memory allocator. When set to 1, it enables the use of the Unified Memory allocator, which allows TensorFlow to share memory between CPU and GPU more efficiently. When set to 0 (or not set at all), TensorFlow will use the default memory allocator.

XLA_PYTHON_CLIENT_MEM_FRACTION: This environment variable is used to control the memory usage of XLA (Accelerated Linear Algebra) runtime for TensorFlow. It specifies the fraction of available host memory that the XLA Python client can use. The default value is 2.0, which means that XLA can use up to half of the available host memory. Setting it to a higher value, like 4.0, will allow XLA to use more memory, which can improve performance but may also increase the risk of running out of memory.

**Comment by hypothalamus01** [comment]
> have tried playing around with these two environment variables in your slurm script before just before running the run_alphafold.py [...] [...] ... ... [...] ?
> 
> As for slurm script this maybe a question you want to ask your cluster manager/help desk as they might be able to provide you more help with the job is running out of memory.
> 
> ```
> export TF_FORCE_UNIFIED_MEMORY=${TF_FORCE_UNIFIED_MEMORY:-0}
> export XLA_PYTHON_CLIENT_MEM_FRACTION=${XLA_PYTHON_CLIENT_MEM_FRACTION:-4.0}
> ```
> 
> Explanation below: TF_FORCE_UNIFIED_MEMORY: This environment variable is used to enable or disable the TensorFlow's Unified Memory allocator. When set to 1, it enables the use of the Unified Memory allocator, which allows TensorFlow to share memory between CPU and GPU more efficiently. When set to 0 (or not set at all), TensorFlow will use the default memory allocator.
> 
> XLA_PYTHON_CLIENT_MEM_FRACTION: This environment variable is used to control the memory usage of XLA (Accelerated Linear Algebra) runtime for TensorFlow. It specifies the fraction of available host memory that the XLA Python client can use. The default value is 2.0, which means that XLA can use up to half of the available host memory. Setting it to a higher value, like 4.0, will allow XLA to use more memory, which can improve performance but may also increase the risk of running out of memory.

It works for me. Thank you so much for your help!! I really appreciate it.
