### ISSUE TITLE
Alphafold-multimer fails trying to create features file

### ISSUE THREAD

**Issue by Casih** [deepmind/alphafold#757]
When trying to run the multimer pipeline, the program ends while trying to create the features file.

```
Traceback (most recent call last):
  File "/n/app/alphafold/2.3.1/alphafold_env/bin/run_alphafold.py", line 432, in <module>
    app.run(main)
  File "/n/app/alphafold/2.3.1/alphafold_env/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/n/app/alphafold/2.3.1/alphafold_env/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/n/app/alphafold/2.3.1/alphafold_env/bin/run_alphafold.py", line 408, in main
    predict_structure(
  File "/n/app/alphafold/2.3.1/alphafold_env/bin/run_alphafold.py", line 172, in predict_structure
    feature_dict = data_pipeline.process(
  File "/n/app/alphafold/2.3.1/alphafold_env/lib/python3.8/site-packages/alphafold-2.3.1-py3.8.egg/alphafold/data/pipeline_multimer.py", line 264, in process
    chain_features = self._process_single_chain(
  File "/n/app/alphafold/2.3.1/alphafold_env/lib/python3.8/site-packages/alphafold-2.3.1-py3.8.egg/alphafold/data/pipeline_multimer.py", line 212, in _process_single_chain
    chain_features = self._monomer_data_pipeline.process(
  File "/n/app/alphafold/2.3.1/alphafold_env/lib/python3.8/site-packages/alphafold-2.3.1-py3.8.egg/alphafold/data/pipeline.py", line 223, in process
    templates_result = self.template_featurizer.get_templates(
  File "/n/app/alphafold/2.3.1/alphafold_env/lib/python3.8/site-packages/alphafold-2.3.1-py3.8.egg/alphafold/data/templates.py", line 960, in get_templates
    result = _process_single_hit(
  File "/n/app/alphafold/2.3.1/alphafold_env/lib/python3.8/site-packages/alphafold-2.3.1-py3.8.egg/alphafold/data/templates.py", line 755, in _process_single_hit
    features, realign_warning = _extract_template_features(
  File "/n/app/alphafold/2.3.1/alphafold_env/lib/python3.8/site-packages/alphafold-2.3.1-py3.8.egg/alphafold/data/templates.py", line 596, in _extract_template_features
    (pdb_id, chain_id, min(mapping.values()) + mapping_offset,
ValueError: min() arg is an empty sequence.
```

**Comment by macwiatrak** [comment]
I've encountered the same issue, do you know what is behind it and how to fix it @Casih?

**Comment by RiccPicc** [comment]
> I've encountered the same issue, do you know what is behind it and how to fix it [@Casih](https://github.com/Casih)?

Same here
