### ISSUE TITLE
RuntimeError: jaxlib/gpu/solver_kernels.cc:45: operation gpusolverDnCreate(&handle) failed: cuSolver internal error

### ISSUE THREAD

**Issue by von-elfen** [deepmind/alphafold#758]
`I0503 03:19:43.859731 140282960090944 run_alphafold.py:216] Running model model_1_pred_0 on 1GFL
W0503 03:19:44.374880 140282960090944 deprecation.py:350] From /home/elfen/anaconda3/lib/python3.10/site-packages/tensorflow/python/autograph/pyct/static_analysis/liveness.py:83: Analyzer.lamba_check (from tensorflow.python.autograph.pyct.static_analysis.liveness) is deprecated and will be removed after 2023-09-23.
Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089
I0503 03:19:47.596941 140282960090944 model.py:165] Running predict with shape(feat) = {'aatype': (4, 238), 'residue_index': (4, 238), 'seq_length': (4,), 'template_aatype': (4, 4, 238), 'template_all_atom_masks': (4, 4, 238, 37), 'template_all_atom_positions': (4, 4, 238, 37, 3), 'template_sum_probs': (4, 4, 1), 'is_distillation': (4,), 'seq_mask': (4, 238), 'msa_mask': (4, 508, 238), 'msa_row_mask': (4, 508), 'random_crop_to_size_seed': (4, 2), 'template_mask': (4, 4), 'template_pseudo_beta': (4, 4, 238, 3), 'template_pseudo_beta_mask': (4, 4, 238), 'atom14_atom_exists': (4, 238, 14), 'residx_atom14_to_atom37': (4, 238, 14), 'residx_atom37_to_atom14': (4, 238, 37), 'atom37_atom_exists': (4, 238, 37), 'extra_msa': (4, 5120, 238), 'extra_msa_mask': (4, 5120, 238), 'extra_msa_row_mask': (4, 5120), 'bert_mask': (4, 508, 238), 'true_msa': (4, 508, 238), 'extra_has_deletion': (4, 5120, 238), 'extra_deletion_value': (4, 5120, 238), 'msa_feat': (4, 508, 238, 49), 'target_feat': (4, 238, 22)}
Traceback (most recent call last):
  File "/home/elfen/.local/lib/python3.10/site-packages/jax/interpreters/mlir.py", line 1113, in _lower_jaxpr_to_fun_cached
    func_op = ctx.cached_call_jaxpr_lowerings[key]
KeyError: ('eigh', { lambda ; a:f32[1,238,4,4]. let
    b:f32[1,238,4,4] = transpose[permutation=(0, 1, 3, 2)] a
    c:f32[1,238,4,4] = add a b
    d:f32[1,238,4,4] = div c 2.0
    e:f32[1,238,4,4] f:f32[1,238,4] = eigh[lower=True sort_eigenvalues=True] d
  in (f, e) }, ())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/elfen/software/alphafold/./run_alphafold.py", line 468, in <module>
    app.run(main)
  File "/home/elfen/anaconda3/lib/python3.10/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/elfen/anaconda3/lib/python3.10/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/elfen/software/alphafold/./run_alphafold.py", line 443, in main
    predict_structure(
  File "/home/elfen/software/alphafold/./run_alphafold.py", line 224, in predict_structure
    prediction_result = model_runner.predict(processed_feature_dict,
  File "/home/elfen/software/alphafold/alphafold/model/model.py", line 167, in predict
    result = self.apply(self.params, jax.random.PRNGKey(random_seed), feat)
  File "/home/elfen/anaconda3/lib/python3.10/site-packages/haiku/_src/transform.py", line 128, in apply_fn
    out, state = f.apply(params, {}, *args, **kwargs)
  File "/home/elfen/anaconda3/lib/python3.10/site-packages/haiku/_src/transform.py", line 357, in apply_fn
    out = f(*args, **kwargs)
  File "/home/elfen/software/alphafold/alphafold/model/model.py", line 83, in _forward_fn
    return model(
  File "/home/elfen/anaconda3/lib/python3.10/site-packages/haiku/_src/module.py", line 426, in wrapped
    out = f(*args, **kwargs)
  File "/home/elfen/anaconda3/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/elfen/anaconda3/lib/python3.10/site-packages/haiku/_src/module.py", line 272, in run_interceptors
    return bound_method(*args, **kwargs)
  File "/home/elfen/software/alphafold/alphafold/model/modules.py", line 383, in __call__
    _, prev = hk.while_loop(
  File "/home/elfen/anaconda3/lib/python3.10/site-packages/haiku/_src/stateful.py", line 898, in while_loop
    val, state = jax.lax.while_loop(pure_cond_fun, pure_body_fun, init_val)
  File "/home/elfen/anaconda3/lib/python3.10/site-packages/haiku/_src/stateful.py", line 891, in pure_body_fun
    val = body_fun(val)
  File "/home/elfen/software/alphafold/alphafold/model/modules.py", line 376, in <lambda>
    get_prev(do_call(x[1], recycle_idx=x[0],
  File "/home/elfen/software/alphafold/alphafold/model/modules.py", line 343, in do_call
    return impl(
  File "/home/elfen/anaconda3/lib/python3.10/site-packages/haiku/_src/module.py", line 426, in wrapped
    out = f(*args, **kwargs)
  File "/home/elfen/anaconda3/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/elfen/anaconda3/lib/python3.10/site-packages/haiku/_src/module.py", line 272, in run_interceptors
    return bound_method(*args, **kwargs)
  File "/home/elfen/software/alphafold/alphafold/model/modules.py", line 167, in __call__
    representations = evoformer_module(batch0, is_training)
  File "/home/elfen/anaconda3/lib/python3.10/site-packages/haiku/_src/module.py", line 426, in wrapped
    out = f(*args, **kwargs)
  File "/home/elfen/anaconda3/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/elfen/anaconda3/lib/python3.10/site-packages/haiku/_src/module.py", line 272, in run_interceptors
    return bound_method(*args, **kwargs)
  File "/home/elfen/software/alphafold/alphafold/model/modules.py", line 1868, in __call__
    template_pair_representation = TemplateEmbedding(c.template, gc)(
  File "/home/elfen/anaconda3/lib/python3.10/site-packages/haiku/_src/module.py", line 426, in wrapped
    out = f(*args, **kwargs)
  File "/home/elfen/anaconda3/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/elfen/anaconda3/lib/python3.10/site-packages/haiku/_src/module.py", line 272, in run_interceptors
    return bound_method(*args, **kwargs)
  File "/home/elfen/software/alphafold/alphafold/model/modules.py", line 2163, in __call__
    template_pair_representation = mapping.sharded_map(map_fn, in_axes=0)(
  File "/home/elfen/software/alphafold/alphafold/model/mapping.py", line 187, in mapped_fn
    outputs, _ = hk.scan(scan_iteration, outputs, slice_starts)
  File "/home/elfen/anaconda3/lib/python3.10/site-packages/haiku/_src/stateful.py", line 640, in scan
    (carry, state), ys = jax.lax.scan(
  File "/home/elfen/anaconda3/lib/python3.10/site-packages/haiku/_src/stateful.py", line 623, in stateful_fun
    carry, out = f(carry, x)
  File "/home/elfen/software/alphafold/alphafold/model/mapping.py", line 176, in scan_iteration
    new_outputs = compute_shard(outputs, i, shard_size)
  File "/home/elfen/software/alphafold/alphafold/model/mapping.py", line 170, in compute_shard
    slice_out = apply_fun_to_slice(slice_start, slice_size)
  File "/home/elfen/software/alphafold/alphafold/model/mapping.py", line 143, in apply_fun_to_slice
    return fun(*input_slice)
  File "/home/elfen/anaconda3/lib/python3.10/site-packages/haiku/_src/stateful.py", line 833, in mapped_fun
    out, state = mapped_pure_fun(args, state)
  File "/home/elfen/anaconda3/lib/python3.10/site-packages/haiku/_src/stateful.py", line 812, in pure_fun
    out = fun(*args)
  File "/home/elfen/software/alphafold/alphafold/model/modules.py", line 2161, in map_fn
    return template_embedder(query_embedding, batch, mask_2d, is_training)
  File "/home/elfen/anaconda3/lib/python3.10/site-packages/haiku/_src/module.py", line 426, in wrapped
    out = f(*args, **kwargs)
  File "/home/elfen/anaconda3/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/elfen/anaconda3/lib/python3.10/site-packages/haiku/_src/module.py", line 272, in run_interceptors
    return bound_method(*args, **kwargs)
  File "/home/elfen/software/alphafold/alphafold/model/modules.py", line 2067, in __call__
    quaternion=quat_affine.rot_to_quat(rot, unstack_inputs=True),
  File "/home/elfen/software/alphafold/alphafold/model/quat_affine.py", line 113, in rot_to_quat
    _, qs = jnp.linalg.eigh(k)
  File "/home/elfen/.local/lib/python3.10/site-packages/jax/_src/numpy/linalg.py", line 400, in eigh
    v, w = lax_linalg.eigh(a, lower=lower, symmetrize_input=symmetrize_input)
jax._src.source_info_util.JaxStackTraceBeforeTransformation: RuntimeError: jaxlib/gpu/solver_kernels.cc:45: operation gpusolverDnCreate(&handle) failed: cuSolver internal error

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/elfen/software/alphafold/./run_alphafold.py", line 468, in <module>
    app.run(main)
  File "/home/elfen/anaconda3/lib/python3.10/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/elfen/anaconda3/lib/python3.10/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/elfen/software/alphafold/./run_alphafold.py", line 443, in main
    predict_structure(
  File "/home/elfen/software/alphafold/./run_alphafold.py", line 224, in predict_structure
    prediction_result = model_runner.predict(processed_feature_dict,
  File "/home/elfen/software/alphafold/alphafold/model/model.py", line 167, in predict
    result = self.apply(self.params, jax.random.PRNGKey(random_seed), feat)
  File "/home/elfen/.local/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/elfen/.local/lib/python3.10/site-packages/jax/_src/api.py", line 622, in cache_miss
    execute = dispatch._xla_call_impl_lazy(fun_, *tracers, **params)
  File "/home/elfen/.local/lib/python3.10/site-packages/jax/_src/dispatch.py", line 236, in _xla_call_impl_lazy
    return xla_callable(fun, device, backend, name, donated_invars, keep_unused,
  File "/home/elfen/.local/lib/python3.10/site-packages/jax/linear_util.py", line 303, in memoized_fun
    ans = call(fun, *args)
  File "/home/elfen/.local/lib/python3.10/site-packages/jax/_src/dispatch.py", line 359, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars, False,
  File "/home/elfen/.local/lib/python3.10/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/elfen/.local/lib/python3.10/site-packages/jax/_src/dispatch.py", line 515, in lower_xla_callable
    lowering_result = mlir.lower_jaxpr_to_module(
  File "/home/elfen/.local/lib/python3.10/site-packages/jax/interpreters/mlir.py", line 642, in lower_jaxpr_to_module
    lower_jaxpr_to_fun(
  File "/home/elfen/.local/lib/python3.10/site-packages/jax/interpreters/mlir.py", line 912, in lower_jaxpr_to_fun
    out_vals, tokens_out = jaxpr_subcomp(ctx.replace(name_stack=callee_name_stack),
  File "/home/elfen/.local/lib/python3.10/site-packages/jax/interpreters/mlir.py", line 1036, in jaxpr_subcomp
    ans = rule(rule_ctx, *map(_unwrap_singleton_ir_values, in_nodes),
  File "/home/elfen/.local/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py", line 1521, in _while_lowering
    new_z, tokens_out = mlir.jaxpr_subcomp(body_ctx, body_jaxpr.jaxpr,
  File "/home/elfen/.local/lib/python3.10/site-packages/jax/interpreters/mlir.py", line 1036, in jaxpr_subcomp
    ans = rule(rule_ctx, *map(_unwrap_singleton_ir_values, in_nodes),
  File "/home/elfen/.local/lib/python3.10/site-packages/jax/interpreters/mlir.py", line 1099, in f_lowered
    out, tokens = jaxpr_subcomp(
  File "/home/elfen/.local/lib/python3.10/site-packages/jax/interpreters/mlir.py", line 1036, in jaxpr_subcomp
    ans = rule(rule_ctx, *map(_unwrap_singleton_ir_values, in_nodes),
  File "/home/elfen/.local/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py", line 1521, in _while_lowering
    new_z, tokens_out = mlir.jaxpr_subcomp(body_ctx, body_jaxpr.jaxpr,
  File "/home/elfen/.local/lib/python3.10/site-packages/jax/interpreters/mlir.py", line 1036, in jaxpr_subcomp
    ans = rule(rule_ctx, *map(_unwrap_singleton_ir_values, in_nodes),
  File "/home/elfen/.local/lib/python3.10/site-packages/jax/interpreters/mlir.py", line 1145, in _xla_call_lower
    out_nodes, tokens = _call_lowering(
  File "/home/elfen/.local/lib/python3.10/site-packages/jax/interpreters/mlir.py", line 1131, in _call_lowering
    symbol_name = _lower_jaxpr_to_fun_cached(ctx, fn_name, call_jaxpr, effects).name.value
  File "/home/elfen/.local/lib/python3.10/site-packages/jax/interpreters/mlir.py", line 1115, in _lower_jaxpr_to_fun_cached
    func_op = lower_jaxpr_to_fun(ctx, fn_name, call_jaxpr, effects)
  File "/home/elfen/.local/lib/python3.10/site-packages/jax/interpreters/mlir.py", line 912, in lower_jaxpr_to_fun
    out_vals, tokens_out = jaxpr_subcomp(ctx.replace(name_stack=callee_name_stack),
  File "/home/elfen/.local/lib/python3.10/site-packages/jax/interpreters/mlir.py", line 1036, in jaxpr_subcomp
    ans = rule(rule_ctx, *map(_unwrap_singleton_ir_values, in_nodes),
  File "/home/elfen/.local/lib/python3.10/site-packages/jax/_src/lax/linalg.py", line 635, in _eigh_cpu_gpu_lowering
    v, w, info = syevd_impl(operand_aval.dtype, operand, lower=lower)
  File "/home/elfen/.local/lib/python3.10/site-packages/jaxlib/gpu_solver.py", line 274, in _syevd_mhlo
    lwork, opaque = gpu_solver.build_syevj_descriptor(
jax._src.traceback_util.UnfilteredStackTrace: RuntimeError: jaxlib/gpu/solver_kernels.cc:45: operation gpusolverDnCreate(&handle) failed: cuSolver internal error

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/elfen/software/alphafold/./run_alphafold.py", line 468, in <module>
    app.run(main)
  File "/home/elfen/anaconda3/lib/python3.10/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/elfen/anaconda3/lib/python3.10/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/elfen/software/alphafold/./run_alphafold.py", line 443, in main
    predict_structure(
  File "/home/elfen/software/alphafold/./run_alphafold.py", line 224, in predict_structure
    prediction_result = model_runner.predict(processed_feature_dict,
  File "/home/elfen/software/alphafold/alphafold/model/model.py", line 167, in predict
    result = self.apply(self.params, jax.random.PRNGKey(random_seed), feat)
  File "/home/elfen/.local/lib/python3.10/site-packages/jaxlib/gpu_solver.py", line 274, in _syevd_mhlo
    lwork, opaque = gpu_solver.build_syevj_descriptor(
RuntimeError: jaxlib/gpu/solver_kernels.cc:45: operation gpusolverDnCreate(&handle) failed: cuSolver internal error`

Help! I have been suffered by this problem for a long time. Please help me.  :(

PC;
Ubuntu 22.04.2 LTS;
Nvidia RTX3050;
Cuda compilation tools, release 11.4, V11.4.120
Build cuda_11.4.r11.4/compiler.30300941_0;
cudnn8.2.4 (#define CUDNN_MAJOR 8 #define CUDNN_MINOR 2 #define CUDNN_PATCHLEVEL 4--#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)#endif /* CUDNN_VERSION_H */);
TensorRT-8.2.5.1.Linux.x86_64-gnu.cuda-11.4.cudnn8.2(I cp libnvinfer.so to libnvinfer.so.7 and libnvinfer_plugin.so to libnvinfer_plugin.so.7)
nvidia-smi (NVIDIA-SMI 470.57.01    Driver Version: 471.41       CUDA Version: 11.4);

I did not install using Docker or Conda, but instead directly installed alphafold:
python3.10.9
jax0.3.25
jaxlib0.3.25+cuda11.cudnn82
tensorflow2.11.0
(Only some important software info are listed. According to the error log, the problem seems to be on jax.)

**Comment by majobenitez** [comment]
Hi,

How did you solve this?

Thanks

**Comment by von-elfen** [comment]
> Hi,
> 
> 
> 
> How did you solve this?
> 
> 
> 
> Thanks

you got same problem?
can you list more info about the errors?
for example,error logs,hardware,system,etc

**Comment by majobenitez** [comment]
Yes, I got the following error while running the latest version of AlphaFold 2.3.2 in a Singularity container
`RuntimeError: jaxlib/gpu/solver_kernels.cc:45: operation gpusolverDnCreate(&handle)
failed: cuSolver internal error`

This was run on an HPC cluster with Rocky Linux 8.5. The container only works with CPU and fails if GPU is used.

I'll attach the full error log and the Slurm job script
[alphafold-error.zip](https://github.com/google-deepmind/alphafold/files/12916274/alphafold-error.zip)

BR

**Comment by GeorgySk** [comment]
I had the same error appearing when running tests for JAX-code using PyCharm's remote interpreter configured on Docker Compose. The same tests were running without issues when launched via terminal. Increasing `shm_size` in _compose.yaml_ file from `'1g'` to `'4g'` appears to have solved the issue for me.
