### ISSUE TITLE
error

### ISSUE THREAD

**Issue by CPU-HORDB** [deepmind/alphafold#779]
Traceback (most recent call last):
  File "/home/inspur/software/anaconda3/envs/alphafold/lib/python3.8/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/home/inspur/software/anaconda3/envs/alphafold/lib/python3.8/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/home/inspur/software/anaconda3/envs/alphafold/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/inspur/software/anaconda3/envs/alphafold/lib/python3.8/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/inspur/software/anaconda3/envs/alphafold/lib/python3.8/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/inspur/software/anaconda3/envs/alphafold/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/inspur/software/anaconda3/envs/alphafold/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/inspur/software/anaconda3/envs/alphafold/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/inspur/software/anaconda3/envs/alphafold/lib/python3.8/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/inspur/software/anaconda3/envs/alphafold/lib/python3.8/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
TypeError: request() got an unexpected keyword argument 'chunked'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/run_docker.py", line 267, in <module>
    app.run(main)
  File "/home/inspur/software/anaconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/inspur/software/anaconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "docker/run_docker.py", line 232, in main
    client = docker.from_env()
  File "/home/inspur/software/anaconda3/envs/alphafold/lib/python3.8/site-packages/docker/client.py", line 96, in from_env
    return cls(
  File "/home/inspur/software/anaconda3/envs/alphafold/lib/python3.8/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/home/inspur/software/anaconda3/envs/alphafold/lib/python3.8/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/home/inspur/software/anaconda3/envs/alphafold/lib/python3.8/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: request() got an unexpected keyword argument 'chunked'

**Comment by CPU-HORDB** [comment]
When I use alphafold, the following error occurs, please tell me how to solve it, thank you

**Comment by VarIr** [comment]
Likely related to https://github.com/docker/docker-py/issues/3113, work-around could be (with your alphafold venv activated)
``` bash
pip3 uninstall requests
pip3 install requests=2.28.1
```

**Comment by anngregory** [comment]
I keep getting the same error even after doing the uninstall/install requests.

**Comment by FelixHomma** [comment]
> Likely related to [docker/docker-py#3113](https://github.com/docker/docker-py/issues/3113), work-around could be (with your alphafold venv activated)
> 
> ```shell
> pip3 uninstall requests
> pip3 install requests=2.28.1
> ```

`pip3 install requests==2.28.1` did it for me.

**Comment by Weishuzhen** [comment]
> > Likely related to [docker/docker-py#3113](https://github.com/docker/docker-py/issues/3113), work-around could be (with your alphafold venv activated)
> > ```shell
> > pip3 uninstall requests
> > pip3 install requests=2.28.1
> > ```
> 
> `pip3 install requests==2.28.1` did it for me.

me too
