### ISSUE TITLE
Docker errors image not found

### ISSUE THREAD

**Issue by ikun821** [deepmind/alphafold#802]
Hi all,

The new dockerfile works fine when building the docker image. However, when I run the docker run run_docker.py, I got an error saying the docker errors image not found. Here is the code and error message: 

python3 docker/run_docker.py   --fasta_paths=/home/ikun/Documents/alphafold/NTD.fasta   --max_template_date=2022-01-01   --model_preset=monomer  --db_preset=full_dbs   --data_dir=/home/ikun/Documents/database   --output_dir=/home/ikun/Documents/output
I0724 13:49:02.621941 140341025580864 run_docker.py:116] Mounting /home/ikun/Documents/alphafold -> /mnt/fasta_path_0
I0724 13:49:02.622105 140341025580864 run_docker.py:116] Mounting /home/ikun/Documents/database/uniref90 -> /mnt/uniref90_database_path
I0724 13:49:02.622197 140341025580864 run_docker.py:116] Mounting /home/ikun/Documents/database/mgnify -> /mnt/mgnify_database_path
I0724 13:49:02.622262 140341025580864 run_docker.py:116] Mounting /home/ikun/Documents/database -> /mnt/data_dir
I0724 13:49:02.622329 140341025580864 run_docker.py:116] Mounting /home/ikun/Documents/database/pdb_mmcif/mmcif_files -> /mnt/template_mmcif_dir
I0724 13:49:02.622401 140341025580864 run_docker.py:116] Mounting /home/ikun/Documents/database/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0724 13:49:02.622477 140341025580864 run_docker.py:116] Mounting /home/ikun/Documents/database/pdb70 -> /mnt/pdb70_database_path
I0724 13:49:02.622550 140341025580864 run_docker.py:116] Mounting /home/ikun/Documents/database/uniref30 -> /mnt/uniref30_database_path
I0724 13:49:02.622609 140341025580864 run_docker.py:116] Mounting /home/ikun/Documents/database/bfd -> /mnt/bfd_database_path
Traceback (most recent call last):
  File "/home/ikun/anaconda3/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/ikun/anaconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.43/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ikun/anaconda3/lib/python3.10/site-packages/docker/models/containers.py", line 811, in run
    container = self.create(image=image, command=command,
  File "/home/ikun/anaconda3/lib/python3.10/site-packages/docker/models/containers.py", line 870, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/home/ikun/anaconda3/lib/python3.10/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/home/ikun/anaconda3/lib/python3.10/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/home/ikun/anaconda3/lib/python3.10/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/ikun/anaconda3/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/ikun/anaconda3/lib/python3.10/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.43/containers/create: Not Found ("No such image: alphafold:latest")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ikun/anaconda3/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/ikun/anaconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.43/images/create?tag=latest&fromImage=alphafold

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ikun/Documents/alphafold/docker/run_docker.py", line 267, in <module>
    app.run(main)
  File "/home/ikun/anaconda3/lib/python3.10/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/ikun/anaconda3/lib/python3.10/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/ikun/Documents/alphafold/docker/run_docker.py", line 237, in main
    container = client.containers.run(
  File "/home/ikun/anaconda3/lib/python3.10/site-packages/docker/models/containers.py", line 814, in run
    self.client.images.pull(image, platform=platform)
  File "/home/ikun/anaconda3/lib/python3.10/site-packages/docker/models/images.py", line 446, in pull
    pull_log = self.client.api.pull(
  File "/home/ikun/anaconda3/lib/python3.10/site-packages/docker/api/image.py", line 430, in pull
    self._raise_for_status(response)
  File "/home/ikun/anaconda3/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/ikun/anaconda3/lib/python3.10/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.43/images/create?tag=latest&fromImage=alphafold: Not Found ("pull access denied for alphafold, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")

After adding sudo before the command, I got this: 

sudo python3 docker/run_docker.py   --fasta_paths=/home/ikun/Documents/alphafold/NTD.fasta   --max_template_date=2022-01-01   --model_preset=monomer  --db_preset=full_dbs   --data_dir=/home/ikun/Documents/database   --output_dir=/home/ikun/Documents/output
[sudo] password for ikun: 
Traceback (most recent call last):
  File "/home/ikun/Documents/alphafold/docker/run_docker.py", line 22, in <module>
    from absl import app
ModuleNotFoundError: No module named 'absl'

I have tried reinstalling everything from the start and still had the same error. And restarting docker and run docker login before running run_docker.py also doesn't work.

**Comment by meerveld96** [comment]
I'm having exactly the same problem, happy to hear possible solutions.

Traceback (most recent call last):
  File "docker/run_docker.py", line 22, in <module>
    from absl import app
ModuleNotFoundError: No module named 'absl'

**Comment by C10H** [comment]
> I'm having exactly the same problem, happy to hear possible solutions.
> 
> Traceback (most recent call last): File "docker/run_docker.py", line 22, in from absl import app ModuleNotFoundError: No module named 'absl'

You need to use pip to install absl-py and docker
