### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by JbaptisteLam** [deepmind/alphafold#804]
Hi,

I've got the same issue as #239 with "list index out of range "message, but I don't know which fasta could be bad formatted,
I used alphafold 2.3.2 in  a singularity container with the small bfd database

```
I0727 17:39:17.110638 140023505205056 run_alphafold.py:424] Have 5 models: ['model_1_pred_0', 'model_2_pred_0', 'model_3_pred_0', 'model_4_pred_0', 'model_5_pred_0']
I0727 17:39:17.111208 140023505205056 run_alphafold.py:438] Using random seed 1240803667531207853 for the data pipeline
I0727 17:39:17.112161 140023505205056 run_alphafold.py:185] Predicting pdb7cby.clean
Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 468, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/app/alphafold/run_alphafold.py", line 443, in main
    predict_structure(
  File "/app/alphafold/run_alphafold.py", line 196, in predict_structure
    feature_dict = data_pipeline.process(
  File "/app/alphafold/alphafold/data/pipeline.py", line 154, in process
    input_seqs, input_descs = parsers.parse_fasta(input_fasta_str)
  File "/app/alphafold/alphafold/data/parsers.py", line 92, in parse_fasta
    sequences[index] += line
IndexError: list index out of range
```

Best,

JB

**Comment by Augustin-Zidek** [comment]
Could you share your input FASTA file here?

**Comment by JbaptisteLam** [comment]
I submited the wrong input file it's ok now
