### ISSUE TITLE
ImageNotFound: 404 Client Error

### ISSUE THREAD

**Issue by beemo2** [deepmind/alphafold#806]
Hello everyone,

I've been trying to set up Alphafold locally over the past week and have been running into a bunch of issues. Right now I got the docker image built, and when I try to run `run_docker.py` I get this error:

`python3 docker/run_docker.py   --fasta_paths=/home/minsu/Sequences/htt.fasta    --max_template_date=2022-01-01   --data_dir=/home/minsu/DATABASES   --output_dir=/home/minsu/output 
I0801 00:30:10.928977 140040178683904 run_docker.py:116] Mounting /home/minsu/Sequences -> /mnt/fasta_path_0
I0801 00:30:10.929103 140040178683904 run_docker.py:116] Mounting /home/minsu/DATABASES/uniref90 -> /mnt/uniref90_database_path
I0801 00:30:10.929182 140040178683904 run_docker.py:116] Mounting /home/minsu/DATABASES/mgnify -> /mnt/mgnify_database_path
I0801 00:30:10.929244 140040178683904 run_docker.py:116] Mounting /home/minsu/DATABASES -> /mnt/data_dir
I0801 00:30:10.929303 140040178683904 run_docker.py:116] Mounting /home/minsu/DATABASES/pdb_mmcif/mmcif_files -> /mnt/template_mmcif_dir
I0801 00:30:10.929374 140040178683904 run_docker.py:116] Mounting /home/minsu/DATABASES/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0801 00:30:10.929443 140040178683904 run_docker.py:116] Mounting /home/minsu/DATABASES/pdb70 -> /mnt/pdb70_database_path
I0801 00:30:10.929512 140040178683904 run_docker.py:116] Mounting /home/minsu/DATABASES/uniref30 -> /mnt/uniref30_database_path
I0801 00:30:10.929579 140040178683904 run_docker.py:116] Mounting /home/minsu/DATABASES/bfd -> /mnt/bfd_database_path
Traceback (most recent call last):
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.43/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/models/containers.py", line 811, in run
    container = self.create(image=image, command=command,
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/models/containers.py", line 870, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.43/containers/create: Not Found ("No such image: alphafold:latest")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.43/images/create?tag=latest&fromImage=alphafold

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/minsu/alphafold/docker/run_docker.py", line 267, in <module>
    app.run(main)
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/minsu/alphafold/docker/run_docker.py", line 237, in main
    container = client.containers.run(
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/models/containers.py", line 814, in run
    self.client.images.pull(image, platform=platform)
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/models/images.py", line 446, in pull
    pull_log = self.client.api.pull(
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/api/image.py", line 430, in pull
    self._raise_for_status(response)
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.43/images/create?tag=latest&fromImage=alphafold: Not Found ("pull access denied for alphafold, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")
(alpha-env) minsu@minsu-MS-7B79:~/alphafold$ docker images
REPOSITORY    TAG       IMAGE ID       CREATED         SIZE
alphafold     latest    7b33eab18f4b   5 minutes ago   10.3GB
<none>        <none>    d3d6b60cb43a   6 hours ago     10.3GB
hello-world   latest    9c7a54a9a43c   2 months ago    13.3kB
(alpha-env) minsu@minsu-MS-7B79:~/alphafold$ docker images
REPOSITORY    TAG       IMAGE ID       CREATED         SIZE
alphafold     latest    7b33eab18f4b   7 minutes ago   10.3GB
hello-world   latest    9c7a54a9a43c   2 months ago    13.3kB
(alpha-env) minsu@minsu-MS-7B79:~/alphafold$ python3 docker/run_docker.py   --fasta_paths=/home/minsu/Sequences/htt.fasta    --max_template_date=2022-01-01   --data_dir=/home/minsu/DATABASES   --output_dir=/home/minsu/output 
I0801 00:34:25.236747 140390681702400 run_docker.py:116] Mounting /home/minsu/Sequences -> /mnt/fasta_path_0
I0801 00:34:25.236881 140390681702400 run_docker.py:116] Mounting /home/minsu/DATABASES/uniref90 -> /mnt/uniref90_database_path
I0801 00:34:25.236961 140390681702400 run_docker.py:116] Mounting /home/minsu/DATABASES/mgnify -> /mnt/mgnify_database_path
I0801 00:34:25.237031 140390681702400 run_docker.py:116] Mounting /home/minsu/DATABASES -> /mnt/data_dir
I0801 00:34:25.237092 140390681702400 run_docker.py:116] Mounting /home/minsu/DATABASES/pdb_mmcif/mmcif_files -> /mnt/template_mmcif_dir
I0801 00:34:25.237161 140390681702400 run_docker.py:116] Mounting /home/minsu/DATABASES/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0801 00:34:25.237237 140390681702400 run_docker.py:116] Mounting /home/minsu/DATABASES/pdb70 -> /mnt/pdb70_database_path
I0801 00:34:25.237309 140390681702400 run_docker.py:116] Mounting /home/minsu/DATABASES/uniref30 -> /mnt/uniref30_database_path
I0801 00:34:25.237380 140390681702400 run_docker.py:116] Mounting /home/minsu/DATABASES/bfd -> /mnt/bfd_database_path
Traceback (most recent call last):
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.43/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/models/containers.py", line 811, in run
    container = self.create(image=image, command=command,
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/models/containers.py", line 870, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.43/containers/create: Not Found ("No such image: alphafold:latest")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.43/images/create?tag=latest&fromImage=alphafold

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/minsu/alphafold/docker/run_docker.py", line 267, in <module>
    app.run(main)
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/minsu/alphafold/docker/run_docker.py", line 237, in main
    container = client.containers.run(
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/models/containers.py", line 814, in run
    self.client.images.pull(image, platform=platform)
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/models/images.py", line 446, in pull
    pull_log = self.client.api.pull(
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/api/image.py", line 430, in pull
    self._raise_for_status(response)
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/minsu/alphafold/alpha-env/lib/python3.10/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.43/images/create?tag=latest&fromImage=alphafold: Not Found ("pull access denied for alphafold, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")`

When I run `docker images` , it shows that alphafold is there, so I'm not entirely sure how to fix it from here.
`REPOSITORY    TAG       IMAGE ID       CREATED             SIZE
alphafold     latest    7b33eab18f4b   About an hour ago   10.3GB
hello-world   latest    9c7a54a9a43c   2 months ago        13.3kB
`

**Comment by AnthonyShea1** [comment]
I am having the same issue, docker login returns:

`Authenticating with existing credentials...
Login Succeeded`

I get the same error when I try to pull from docker desktop as well, unlike my other images
