### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 116: invalid continuation byte

### ISSUE THREAD

**Issue by myorick** [deepmind/alphafold#807]
Hi there,

I have just finished the installation of v2.3.2, and trying to run a simple multimer task. but it shows up an error:

I0801 18:58:47.321497 140533688157248 run_docker.py:258] I0801 10:58:47.321051 140041777889920 pipeline.py:234] Uniref90 MSA size: 10000 sequences.
I0801 18:58:47.321589 140533688157248 run_docker.py:258] I0801 10:58:47.321125 140041777889920 pipeline.py:235] BFD MSA size: 2320 sequences.
I0801 18:58:47.321618 140533688157248 run_docker.py:258] I0801 10:58:47.321141 140041777889920 pipeline.py:236] MGnify MSA size: 501 sequences.
I0801 18:58:47.321653 140533688157248 run_docker.py:258] I0801 10:58:47.321155 140041777889920 pipeline.py:237] Final (deduplicated) MSA size: 12586 sequences.
I0801 18:58:47.321677 140533688157248 run_docker.py:258] I0801 10:58:47.321169 140041777889920 pipeline.py:239] Total number of templates (NB: this can include bad templates and is later filtered to top 4): 20.
I0801 18:58:47.335834 140533688157248 run_docker.py:258] I0801 10:58:47.335489 140041777889920 jackhmmer.py:133] Launching subprocess "/usr/bin/jackhmmer -o /dev/null -A /tmp/tmpmatbrfqi/output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 /tmp/tmp9hl135n3.fasta /mnt/uniprot_database_path/uniprot.fasta"
I0801 18:58:47.336582 140533688157248 run_docker.py:258] I0801 10:58:47.336297 140041777889920 utils.py:36] Started Jackhmmer (uniprot.fasta) query
I0801 19:04:34.800924 140533688157248 run_docker.py:258] I0801 11:04:34.800556 140041777889920 utils.py:40] Finished Jackhmmer (uniprot.fasta) query in 347.464 seconds
I0801 19:04:34.801603 140533688157248 run_docker.py:258] Traceback (most recent call last):
I0801 19:04:34.802035 140533688157248 run_docker.py:258] File "/app/alphafold/run_alphafold.py", line 570, in <module>
I0801 19:04:34.802095 140533688157248 run_docker.py:258] app.run(main)
I0801 19:04:34.802123 140533688157248 run_docker.py:258] File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 312, in run
I0801 19:04:34.802174 140533688157248 run_docker.py:258] _run_main(main, args)
I0801 19:04:34.802203 140533688157248 run_docker.py:258] File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 258, in _run_main
I0801 19:04:34.802225 140533688157248 run_docker.py:258] sys.exit(main(argv))
I0801 19:04:34.802254 140533688157248 run_docker.py:258] File "/app/alphafold/run_alphafold.py", line 543, in main
I0801 19:04:34.802276 140533688157248 run_docker.py:258] predict_structure(
I0801 19:04:34.802298 140533688157248 run_docker.py:258] File "/app/alphafold/run_alphafold.py", line 256, in predict_structure
I0801 19:04:34.802319 140533688157248 run_docker.py:258] feature_dict = data_pipeline.process(
I0801 19:04:34.802342 140533688157248 run_docker.py:258] File "/app/alphafold/alphafold/data/pipeline_multimer.py", line 264, in process
I0801 19:04:34.802370 140533688157248 run_docker.py:258] chain_features = self._process_single_chain(
I0801 19:04:34.802392 140533688157248 run_docker.py:258] File "/app/alphafold/alphafold/data/pipeline_multimer.py", line 219, in _process_single_chain
I0801 19:04:34.802426 140533688157248 run_docker.py:258] all_seq_msa_features = self._all_seq_msa_features(chain_fasta_path,
I0801 19:04:34.802446 140533688157248 run_docker.py:258] File "/app/alphafold/alphafold/data/pipeline_multimer.py", line 227, in _all_seq_msa_features
I0801 19:04:34.802468 140533688157248 run_docker.py:258] result = pipeline.run_msa_tool(
I0801 19:04:34.802490 140533688157248 run_docker.py:258] File "/app/alphafold/alphafold/data/pipeline.py", line 96, in run_msa_tool
I0801 19:04:34.802511 140533688157248 run_docker.py:258] result = msa_runner.query(input_fasta_path)[0]
I0801 19:04:34.802532 140533688157248 run_docker.py:258] File "/app/alphafold/alphafold/data/tools/jackhmmer.py", line 170, in query
I0801 19:04:34.802553 140533688157248 run_docker.py:258] return self.query_multiple([input_fasta_path], max_sequences)[0]
I0801 19:04:34.802574 140533688157248 run_docker.py:258] File "/app/alphafold/alphafold/data/tools/jackhmmer.py", line 181, in query_multiple
I0801 19:04:34.802595 140533688157248 run_docker.py:258] single_chunk_results.append([self._query_chunk(
I0801 19:04:34.802616 140533688157248 run_docker.py:258] File "/app/alphafold/alphafold/data/tools/jackhmmer.py", line 143, in _query_chunk
I0801 19:04:34.802637 140533688157248 run_docker.py:258] 'Jackhmmer failed\nstderr:\n%s\n' % stderr.decode('utf-8'))
I0801 19:04:34.802658 140533688157248 run_docker.py:258] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 116: invalid continuation byte

can some one please help me ?

my system is Ubuntu 22.04
Linux ppclab-gpu 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by myorick** [comment]
solved by changing utf-8 to ISO-8859-1 in .py

**Comment by dltacube** [comment]
> solved by changing utf-8 to ISO-8859-1 in .py

Does this mean you modified every .py file or just the one mentioned in the stacktrace?
