### ISSUE TITLE
AlphaFold multiuser error

### ISSUE THREAD

**Issue by incisrdg** [deepmind/alphafold#819]
I am having an issue about the situation that is mentioned below. Could you please help me about it.

2023-08-14 17:58:29,948 Running on GPU
2023-08-14 17:58:29,950 Found 4 citations for tools or databases
2023-08-14 17:58:29,950 Query 1/1: test_914f5_0 (length 1641)
COMPLETE: 100%|██████████| 450/450 [elapsed: 00:02 remaining: 00:00]2023-08-14 17:58:32,213 Could not get MSA/templates for test_914f5_0: invalid literal for int() with base 10: 'DUMMY'
Traceback (most recent call last):
  File "/content/colabfold/batch.py", line 1377, in run
    = get_msa_and_templates(jobname, query_sequence, a3m_lines, result_dir, msa_mode, use_templates,
  File "/content/colabfold/batch.py", line 817, in get_msa_and_templates
    a3m_lines = run_mmseqs2(
  File "/content/colabfold/colabfold.py", line 303, in run_mmseqs2
    M = int(line[1:].rstrip())
ValueError: invalid literal for int() with base 10: 'DUMMY'
2023-08-14 17:58:32,214 Done

**Comment by simoneatt11** [comment]
Hi, did you find a way to fix it?

**Comment by Ni-Ar** [comment]
Hey, I'm running colabfold locally instead of alphafold2 but I got the exact same error. 

```sh
2024-04-27 18:43:37,124 Running colabfold 1.5.2 (8c745219964d6bfb878dd6fb53b5a2a05b009391)
2024-04-27 18:43:45,887 Running on GPU
2024-04-27 18:43:47,089 Found 7 citations for tools or databases
2024-04-27 18:43:47,089 Query 1/1: ProteinA__ProteinB (length 1818)
2024-04-27 18:43:47,162 Could not get MSA/templates for ProteinA__ProteinB: invalid literal for int() with base 10: 'DUMMY'
Traceback (most recent call last):
  File "/users/software/miniconda/envs/colabfold/lib/python3.8/site-packages/colabfold/batch.py", line 1370, in run
    = get_msa_and_templates(jobname, query_sequence, result_dir, msa_mode, use_templates,
  File "/users/software/miniconda/envs/colabfold/lib/python3.8/site-packages/colabfold/batch.py", line 761, in get_msa_and_templates
    a3m_lines_mmseqs2, template_paths = run_mmseqs2(
  File "/users/software/miniconda/envs/colabfold/lib/python3.8/site-packages/colabfold/colabfold.py", line 298, in run_mmseqs2
    M = int(line[1:].rstrip())
ValueError: invalid literal for int() with base 10: 'DUMMY'
2024-04-27 18:43:47,169 Done
```

I managed to solve this error by changing the width of my input fasta file to the canonical 60 amino acids per line.  For sake of compaction in the terminal window I set each line to 110 amio acids but this deviation from the convention gave me this error. 

Hope this helps.
Nicco
