### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by cjb-apis** [deepmind/alphafold#825]
Hello, I am having an issue with a pip install in a conda environment

`pip install alphafold`

I have tried rectifying this by checking sudo apt-get update, installing gcc, meson, scipy, gfortran and creating a brand new conda environment. I always have the same issue. A colleague has been able to install with no issues, any advice would be much appreciated,

Many thanks,
Charles

Here is the output error:
```
Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [60 lines of output]
      The Meson build system
      Version: 0.62.2
      Source dir: /tmp/pip-install-txohv8x9/scipy_8efb1805b8b5438c8be288b99eb5f25c
      Build dir: /tmp/pip-install-txohv8x9/scipy_8efb1805b8b5438c8be288b99eb5f25c/.mesonpy-ml5zppr7/build
      Build type: native build
      Project name: SciPy
      Project version: 1.9.1
      C compiler for the host machine: cc (gcc 9.4.0 "cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
      C linker for the host machine: cc ld.bfd 2.34
      C++ compiler for the host machine: c++ (gcc 9.4.0 "c++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
      C++ linker for the host machine: c++ ld.bfd 2.34
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES
      Library m found: YES
      
      ../../meson.build:41:0: ERROR: Unable to detect linker for compiler "gfortran -Wl,--version -Wno-conversion"
      stdout:
      stderr: collect2 version 12.2.0
      /usr/bin/ld -plugin /home/linuxbrew/.linuxbrew/Cellar/gcc/12.2.0/bin/../libexec/gcc/x86_64-pc-linux-gnu/12/liblto_plugin.so -plugin-opt=/home/linuxbrew/.linuxbrew/Cellar/gcc/12.2.0/bin/../libexec/gcc/x86_64-pc-linux-gnu/12/lto-wrapper -plugin-opt=-fresolution=/tmp/ccC7upEO.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 --dynamic-linker /home/linuxbrew/.linuxbrew/lib/ld.so -rpath /home/linuxbrew/.linuxbrew/lib/gcc/current -pie /home/linuxbrew/.linuxbrew/Cellar/gcc/12.2.0/bin/../lib/gcc/current/gcc/x86_64-pc-linux-gnu/12/Scrt1.o /home/linuxbrew/.linuxbrew/Cellar/gcc/12.2.0/bin/../lib/gcc/current/gcc/x86_64-pc-linux-gnu/12/crti.o /home/linuxbrew/.linuxbrew/Cellar/gcc/12.2.0/bin/../lib/gcc/current/gcc/x86_64-pc-linux-gnu/12/crtbeginS.o -nostdlib -L/home/linuxbrew/.linuxbrew/Cellar/gcc/12.2.0/bin/../lib/gcc/current/gcc/x86_64-pc-linux-gnu/12 -L/home/linuxbrew/.linuxbrew/opt/glibc/lib -L/home/linuxbrew/.linuxbrew/lib/gcc/current -L/home/linuxbrew/.linuxbrew/lib --version -rpath /home/linuxbrew/.linuxbrew/lib -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /home/linuxbrew/.linuxbrew/Cellar/gcc/12.2.0/bin/../lib/gcc/current/gcc/x86_64-pc-linux-gnu/12/crtendS.o /home/linuxbrew/.linuxbrew/Cellar/gcc/12.2.0/bin/../lib/gcc/current/gcc/x86_64-pc-linux-gnu/12/crtn.o
      /usr/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/gcc/12.2.0/bin/../libexec/gcc/x86_64-pc-linux-gnu/12/liblto_plugin.so: error loading plugin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/linuxbrew/.linuxbrew/Cellar/gcc/12.2.0/bin/../libexec/gcc/x86_64-pc-linux-gnu/12/liblto_plugin.so)
      collect2: error: ld returned 1 exit status
      
      
      A full log can be found at /tmp/pip-install-txohv8x9/scipy_8efb1805b8b5438c8be288b99eb5f25c/.mesonpy-ml5zppr7/build/meson-logs/meson-log.txt
      + meson setup --native-file=/tmp/pip-install-txohv8x9/scipy_8efb1805b8b5438c8be288b99eb5f25c/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=/home/charles_bannister/anaconda3/envs/alphaenv /tmp/pip-install-txohv8x9/scipy_8efb1805b8b5438c8be288b99eb5f25c /tmp/pip-install-txohv8x9/scipy_8efb1805b8b5438c8be288b99eb5f25c/.mesonpy-ml5zppr7/build
      Traceback (most recent call last):
        File "/home/charles_bannister/anaconda3/envs/alphaenv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/charles_bannister/anaconda3/envs/alphaenv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/charles_bannister/anaconda3/envs/alphaenv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-yel10y8c/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 969, in get_requires_for_build_wheel
          with _project(config_settings) as project:
        File "/home/charles_bannister/anaconda3/envs/alphaenv/lib/python3.11/contextlib.py", line 137, in __enter__
          return next(self.gen)
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-yel10y8c/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 948, in _project
          with Project.with_temp_working_dir(
        File "/home/charles_bannister/anaconda3/envs/alphaenv/lib/python3.11/contextlib.py", line 137, in __enter__
          return next(self.gen)
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-yel10y8c/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 777, in with_temp_working_dir
          yield cls(source_dir, tmpdir, build_dir)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-yel10y8c/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 682, in __init__
          self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
        File "/tmp/pip-build-env-yel10y8c/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 713, in _configure
          self._meson(
        File "/tmp/pip-build-env-yel10y8c/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 696, in _meson
          return self._proc('meson', *args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-yel10y8c/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 691, in _proc
          subprocess.check_call(list(args))
        File "/home/charles_bannister/anaconda3/envs/alphaenv/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'setup', '--native-file=/tmp/pip-install-txohv8x9/scipy_8efb1805b8b5438c8be288b99eb5f25c/.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2', '--prefix=/home/charles_bannister/anaconda3/envs/alphaenv', '/tmp/pip-install-txohv8x9/scipy_8efb1805b8b5438c8be288b99eb5f25c', '/tmp/pip-install-txohv8x9/scipy_8efb1805b8b5438c8be288b99eb5f25c/.mesonpy-ml5zppr7/build']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by Htomlinson14** [comment]
Hi! Thanks for reaching out. This repo hasn't been set up to be pip installable as a library. The primary use case of this repo is to run the alphafold pipeline as a script, either in a docker image or your own virtual environment. In the past others have forked the repo (https://github.com/sokrypton/alphafold) and made it pip installable (e.g. for Colabfold https://github.com/sokrypton/ColabFold) as "alphafold-colabfold".
