### ISSUE TITLE
400 Client Error: Bad Request for url: http+docker://localhost/v1.41/containers/create

### ISSUE THREAD

**Issue by siwei-deng** [deepmind/alphafold#89]
Hi, 

I'm trying to run AlphaFold with a test sequence but get the following error: 

```shell
$ python3 docker/run_docker.py --preset=full_dbs --fasta_paths=/home/biology/workspace/alphafold_test/rcsb_pdb_7LUL.fasta --max_template_date=2020-05-14
I0802 19:39:11.381993 139658266580800 run_docker.py:119] Mounting /home/biology/workspace/alphafold_test -> /mnt/fasta_path_0
I0802 19:39:11.382288 139658266580800 run_docker.py:119] Mounting /home/biology/software/alphafold/geneticdb/uniref90 -> /mnt/uniref90_database_path
I0802 19:39:11.382458 139658266580800 run_docker.py:119] Mounting /home/biology/software/alphafold/geneticdb/mgnify -> /mnt/mgnify_database_path
I0802 19:39:11.382605 139658266580800 run_docker.py:119] Mounting /home/biology/software/alphafold/geneticdb/pdb70 -> /mnt/pdb70_database_path
I0802 19:39:11.382734 139658266580800 run_docker.py:119] Mounting /home/biology/software/alphafold -> /mnt/data_dir
I0802 19:39:11.382863 139658266580800 run_docker.py:119] Mounting /home/biology/software/alphafold/geneticdb/pdb_mmcif -> /mnt/template_mmcif_dir
I0802 19:39:11.383006 139658266580800 run_docker.py:119] Mounting /home/biology/software/alphafold/geneticdb/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0802 19:39:11.383131 139658266580800 run_docker.py:119] Mounting /home/biology/software/alphafold/geneticdb/uniclust30/uniclust30_2018_08 -> /mnt/uniclust30_database_path
I0802 19:39:11.383262 139658266580800 run_docker.py:119] Mounting /home/biology/software/alphafold/geneticdb/bfd -> /mnt/bfd_database_path
Traceback (most recent call last):
  File "/home/biology/alphafold/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/biology/alphafold/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.41/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/run_docker.py", line 201, in <module>
    app.run(main)
  File "/home/biology/alphafold/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/biology/alphafold/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "docker/run_docker.py", line 173, in main
    container = client.containers.run(
  File "/home/biology/alphafold/lib/python3.8/site-packages/docker/models/containers.py", line 811, in run
    container = self.create(image=image, command=command,
  File "/home/biology/alphafold/lib/python3.8/site-packages/docker/models/containers.py", line 870, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/home/biology/alphafold/lib/python3.8/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/home/biology/alphafold/lib/python3.8/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/home/biology/alphafold/lib/python3.8/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/biology/alphafold/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/biology/alphafold/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.41/containers/create: Bad Request ("Unknown runtime specified nvidia")
```

I did install the NVIDIA Container Toolkit: 
```
$ docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi
Mon Aug  2 12:01:41 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.05    Driver Version: 450.51.05    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100S-PCI...  Off  | 00000000:40:00.0 Off |                    0 |
| N/A   30C    P0    35W / 250W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100S-PCI...  Off  | 00000000:B1:00.0 Off |                    0 |
| N/A   30C    P0    35W / 250W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

Operating System: CentOS Linux 7 (Core)
Kernel: Linux 3.10.0-862.el7.x86_64
Architecture: x86-64

Thanks for any helps and comments!

**Comment by RMeli** [comment]
I solved this problem by installing `nvidia-docker2` as described in [Setting up NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#setting-up-nvidia-container-toolkit).

**Comment by siwei-deng** [comment]
> I solved this problem by installing `nvidia-docker2` as described in [Setting up NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#setting-up-nvidia-container-toolkit).

@RMeli Thank you very much! It worked!! XD

**Comment by dgzct11** [comment]
Hello,
I am trying to run alphafold on a windows 10: pro machine, and I am getting this exact same error. How would i set up nvidia-docker2 for windows?
